// Package servedapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package servedapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BodyViolationLocation.
const (
	Body BodyViolationLocation = "body"
)

// Valid indicates whether the value is a known member of the BodyViolationLocation enum.
func (e BodyViolationLocation) Valid() bool {
	switch e {
	case Body:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ACTIVERENTALEXISTS             ErrorCode = "ACTIVE_RENTAL_EXISTS"
	AUTHENTICATIONREQUIRED         ErrorCode = "AUTHENTICATION_REQUIRED"
	BODYTOOLARGE                   ErrorCode = "BODY_TOO_LARGE"
	CLOCKOUTOFSYNC                 ErrorCode = "CLOCK_OUT_OF_SYNC"
	CONCURRENCYRETRYEXHAUSTED      ErrorCode = "CONCURRENCY_RETRY_EXHAUSTED"
	CSRFINVALID                    ErrorCode = "CSRF_INVALID"
	DELIVERYCONFLICT               ErrorCode = "DELIVERY_CONFLICT"
	EMAILALREADYREGISTERED         ErrorCode = "EMAIL_ALREADY_REGISTERED"
	IDEMPOTENCYCONFLICT            ErrorCode = "IDEMPOTENCY_CONFLICT"
	IDEMPOTENCYINPROGRESS          ErrorCode = "IDEMPOTENCY_IN_PROGRESS"
	IDEMPOTENCYKEYINVALID          ErrorCode = "IDEMPOTENCY_KEY_INVALID"
	IDEMPOTENCYKEYREQUIRED         ErrorCode = "IDEMPOTENCY_KEY_REQUIRED"
	INTERNALAUTHENTICATIONREQUIRED ErrorCode = "INTERNAL_AUTHENTICATION_REQUIRED"
	INTERNALERROR                  ErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS             ErrorCode = "INVALID_CREDENTIALS"
	INVALIDCURSOR                  ErrorCode = "INVALID_CURSOR"
	INVALIDHEADER                  ErrorCode = "INVALID_HEADER"
	INVALIDRENTALSTATE             ErrorCode = "INVALID_RENTAL_STATE"
	MALFORMEDJSON                  ErrorCode = "MALFORMED_JSON"
	METHODNOTALLOWED               ErrorCode = "METHOD_NOT_ALLOWED"
	ORIGINNOTALLOWED               ErrorCode = "ORIGIN_NOT_ALLOWED"
	OUTSIDESERVICEZONE             ErrorCode = "OUTSIDE_SERVICE_ZONE"
	OUTSTANDINGINVOICE             ErrorCode = "OUTSTANDING_INVOICE"
	PAYMENTINPROGRESS              ErrorCode = "PAYMENT_IN_PROGRESS"
	RATELIMITED                    ErrorCode = "RATE_LIMITED"
	RENTALCOMPLETED                ErrorCode = "RENTAL_COMPLETED"
	RESERVATIONEXPIRED             ErrorCode = "RESERVATION_EXPIRED"
	RESOURCENOTFOUND               ErrorCode = "RESOURCE_NOT_FOUND"
	SERVICEUNAVAILABLE             ErrorCode = "SERVICE_UNAVAILABLE"
	TELEMETRYSTALE                 ErrorCode = "TELEMETRY_STALE"
	UNSUPPORTEDMEDIATYPE           ErrorCode = "UNSUPPORTED_MEDIA_TYPE"
	VALIDATIONFAILED               ErrorCode = "VALIDATION_FAILED"
	VEHICLEUNAVAILABLE             ErrorCode = "VEHICLE_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ACTIVERENTALEXISTS:
		return true
	case AUTHENTICATIONREQUIRED:
		return true
	case BODYTOOLARGE:
		return true
	case CLOCKOUTOFSYNC:
		return true
	case CONCURRENCYRETRYEXHAUSTED:
		return true
	case CSRFINVALID:
		return true
	case DELIVERYCONFLICT:
		return true
	case EMAILALREADYREGISTERED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case IDEMPOTENCYINPROGRESS:
		return true
	case IDEMPOTENCYKEYINVALID:
		return true
	case IDEMPOTENCYKEYREQUIRED:
		return true
	case INTERNALAUTHENTICATIONREQUIRED:
		return true
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDCURSOR:
		return true
	case INVALIDHEADER:
		return true
	case INVALIDRENTALSTATE:
		return true
	case MALFORMEDJSON:
		return true
	case METHODNOTALLOWED:
		return true
	case ORIGINNOTALLOWED:
		return true
	case OUTSIDESERVICEZONE:
		return true
	case OUTSTANDINGINVOICE:
		return true
	case PAYMENTINPROGRESS:
		return true
	case RATELIMITED:
		return true
	case RENTALCOMPLETED:
		return true
	case RESERVATIONEXPIRED:
		return true
	case RESOURCENOTFOUND:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case TELEMETRYSTALE:
		return true
	case UNSUPPORTEDMEDIATYPE:
		return true
	case VALIDATIONFAILED:
		return true
	case VEHICLEUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for LiveStatusStatus.
const (
	LiveStatusStatusOk LiveStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the LiveStatusStatus enum.
func (e LiveStatusStatus) Valid() bool {
	switch e {
	case LiveStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ParameterViolationLocation.
const (
	Header ParameterViolationLocation = "header"
	Path   ParameterViolationLocation = "path"
	Query  ParameterViolationLocation = "query"
)

// Valid indicates whether the value is a known member of the ParameterViolationLocation enum.
func (e ParameterViolationLocation) Valid() bool {
	switch e {
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatusCity.
const (
	Бишкек ReadyStatusCity = "Бишкек"
)

// Valid indicates whether the value is a known member of the ReadyStatusCity enum.
func (e ReadyStatusCity) Valid() bool {
	switch e {
	case Бишкек:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatusCurrency.
const (
	KGS ReadyStatusCurrency = "KGS"
)

// Valid indicates whether the value is a known member of the ReadyStatusCurrency enum.
func (e ReadyStatusCurrency) Valid() bool {
	switch e {
	case KGS:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatusStatus.
const (
	ReadyStatusStatusOk ReadyStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadyStatusStatus enum.
func (e ReadyStatusStatus) Valid() bool {
	switch e {
	case ReadyStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatusTimezone.
const (
	AsiaBishkek ReadyStatusTimezone = "Asia/Bishkek"
)

// Valid indicates whether the value is a known member of the ReadyStatusTimezone enum.
func (e ReadyStatusTimezone) Valid() bool {
	switch e {
	case AsiaBishkek:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	InsufficientEnergy   UnavailableReason = "insufficient_energy"
	OutsideServiceZone   UnavailableReason = "outside_service_zone"
	ServiceRequired      UnavailableReason = "service_required"
	TechnicalUnavailable UnavailableReason = "technical_unavailable"
	TelemetryStale       UnavailableReason = "telemetry_stale"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case InsufficientEnergy:
		return true
	case OutsideServiceZone:
		return true
	case ServiceRequired:
		return true
	case TechnicalUnavailable:
		return true
	case TelemetryStale:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Code    ErrorCode         `json:"code"`
	Details *ApiError_Details `json:"details,omitempty"`

	// Message Safe English message; clients translate known codes.
	Message string `json:"message"`

	// RequestId Example: example-request-1
	RequestId RequestId `json:"request_id"`
}

// ApiError_Details defines model for ApiError.Details.
type ApiError_Details struct {
	union json.RawMessage
}

// BodyViolation defines model for BodyViolation.
type BodyViolation struct {
	Code     string                `json:"code"`
	Location BodyViolationLocation `json:"location"`
	Message  string                `json:"message"`

	// Pointer JSON Pointer without the fragment marker.
	Pointer string `json:"pointer"`
}

// BodyViolationLocation defines model for BodyViolation.Location.
type BodyViolationLocation string

// Credentials defines model for Credentials.
type Credentials struct {
	// Email Trim surrounding whitespace, lowercase the whole address, then validate the resulting email (at most 254 characters).
	Email string `json:"email"`

	// Password 12–128 Unicode code points. No Unicode whitespace. Never trim or normalize.
	Password string `json:"password"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// LiveStatus defines model for LiveStatus.
type LiveStatus struct {
	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp        `json:"server_time"`
	Status     LiveStatusStatus `json:"status"`
}

// LiveStatusStatus defines model for LiveStatus.Status.
type LiveStatusStatus string

// ParameterViolation defines model for ParameterViolation.
type ParameterViolation struct {
	Code      string                     `json:"code"`
	Location  ParameterViolationLocation `json:"location"`
	Message   string                     `json:"message"`
	Parameter string                     `json:"parameter"`
}

// ParameterViolationLocation defines model for ParameterViolation.Location.
type ParameterViolationLocation string

// ReadyStatus defines model for ReadyStatus.
type ReadyStatus struct {
	City     ReadyStatusCity     `json:"city"`
	Currency ReadyStatusCurrency `json:"currency"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp           `json:"server_time"`
	Status     ReadyStatusStatus   `json:"status"`
	Timezone   ReadyStatusTimezone `json:"timezone"`
}

// ReadyStatusCity defines model for ReadyStatus.City.
type ReadyStatusCity string

// ReadyStatusCurrency defines model for ReadyStatus.Currency.
type ReadyStatusCurrency string

// ReadyStatusStatus defines model for ReadyStatus.Status.
type ReadyStatusStatus string

// ReadyStatusTimezone defines model for ReadyStatus.Timezone.
type ReadyStatusTimezone string

// RequestId Example: example-request-1
type RequestId = string

// ResourceId Example: 01994342-6ba7-7000-8000-000000000001
type ResourceId = string

// SessionSnapshot defines model for SessionSnapshot.
type SessionSnapshot struct {
	CsrfToken string `json:"csrf_token"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`

	// SessionExpiresAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	SessionExpiresAt Timestamp `json:"session_expires_at"`
	User             User      `json:"user"`
}

// Timestamp UTC RFC3339, exactly six fractional digits; domain commands use database time.
//
// Example: 2026-09-12T07:15:30.123456Z
type Timestamp = string

// UnavailableDetails defines model for UnavailableDetails.
type UnavailableDetails struct {
	UnavailableReasons []UnavailableReason `json:"unavailable_reasons"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// User defines model for User.
type User struct {
	// CreatedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	CreatedAt Timestamp `json:"created_at"`

	// Email Canonical email, trimmed and lowercased in full.
	Email openapi_types.Email `json:"email"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id ResourceId `json:"id"`
}

// ValidationDetails defines model for ValidationDetails.
type ValidationDetails struct {
	Violations []Violation `json:"violations"`
}

// Violation defines model for Violation.
type Violation struct {
	union json.RawMessage
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// Origin Must match an allowed browser origin. Rejection is 403 ORIGIN_NOT_ALLOWED.
	Origin string `json:"Origin"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// Origin Must match an allowed browser origin. Rejection is 403 ORIGIN_NOT_ALLOWED.
	Origin string `json:"Origin"`

	// XCSRFToken Bound to the session; expires no later than the session. Rejection is 403 CSRF_INVALID.
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`

	// Origin Must match an allowed browser origin. Rejection is 403 ORIGIN_NOT_ALLOWED.
	Origin string `json:"Origin"`
}

// GetHealthLiveParams defines parameters for GetHealthLive.
type GetHealthLiveParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetHealthReadyParams defines parameters for GetHealthReady.
type GetHealthReadyParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetMeParams defines parameters for GetMe.
type GetMeParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Credentials

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = Credentials

// AsValidationDetails returns the union data inside the ApiError_Details as a ValidationDetails
func (t ApiError_Details) AsValidationDetails() (ValidationDetails, error) {
	var body ValidationDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationDetails overwrites any union data inside the ApiError_Details as the provided ValidationDetails
func (t *ApiError_Details) FromValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationDetails performs a merge with any union data inside the ApiError_Details, using the provided ValidationDetails
func (t *ApiError_Details) MergeValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnavailableDetails returns the union data inside the ApiError_Details as a UnavailableDetails
func (t ApiError_Details) AsUnavailableDetails() (UnavailableDetails, error) {
	var body UnavailableDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnavailableDetails overwrites any union data inside the ApiError_Details as the provided UnavailableDetails
func (t *ApiError_Details) FromUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnavailableDetails performs a merge with any union data inside the ApiError_Details, using the provided UnavailableDetails
func (t *ApiError_Details) MergeUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApiError_Details) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiError_Details) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBodyViolation returns the union data inside the Violation as a BodyViolation
func (t Violation) AsBodyViolation() (BodyViolation, error) {
	var body BodyViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBodyViolation overwrites any union data inside the Violation as the provided BodyViolation
func (t *Violation) FromBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBodyViolation performs a merge with any union data inside the Violation, using the provided BodyViolation
func (t *Violation) MergeBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterViolation returns the union data inside the Violation as a ParameterViolation
func (t Violation) AsParameterViolation() (ParameterViolation, error) {
	var body ParameterViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterViolation overwrites any union data inside the Violation as the provided ParameterViolation
func (t *Violation) FromParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterViolation performs a merge with any union data inside the Violation, using the provided ParameterViolation
func (t *Violation) MergeParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Violation) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Violation) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login login
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request, params LoginParams)
	// Logout logout
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)
	// Register register
	// (POST /api/v1/auth/register)
	Register(w http.ResponseWriter, r *http.Request, params RegisterParams)
	// GetHealthLive Check the process without querying dependencies
	// (GET /api/v1/health/live)
	GetHealthLive(w http.ResponseWriter, r *http.Request, params GetHealthLiveParams)
	// GetHealthReady Check PostgreSQL, schema and PostGIS
	// (GET /api/v1/health/ready)
	GetHealthReady(w http.ResponseWriter, r *http.Request, params GetHealthReadyParams)
	// GetMe get Me
	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request, params GetMeParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login login
// (POST /api/v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request, params LoginParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout logout
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register register
// (POST /api/v1/auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request, params RegisterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealthLive Check the process without querying dependencies
// (GET /api/v1/health/live)
func (_ Unimplemented) GetHealthLive(w http.ResponseWriter, r *http.Request, params GetHealthLiveParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealthReady Check PostgreSQL, schema and PostGIS
// (GET /api/v1/health/ready)
func (_ Unimplemented) GetHealthReady(w http.ResponseWriter, r *http.Request, params GetHealthReadyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe get Me
// (GET /api/v1/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request, params GetMeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	// ------------- Optional header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = &XCSRFToken

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthLive operation middleware
func (siw *ServerInterfaceWrapper) GetHealthLive(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHealthLiveParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthLive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthReady operation middleware
func (siw *ServerInterfaceWrapper) GetHealthReady(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHealthReadyParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthReady(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMeParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health/live", wrapper.GetHealthLive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health/ready", wrapper.GetHealthReady)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/me", wrapper.GetMe)
	})

	return r
}

type LoginRequestObject struct {
	Params LoginParams
	Body   *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	CacheControl *string
	SetCookie    *string
	XRequestID   *RequestId
}

type Login200JSONResponse struct {
	Body    SessionSnapshot
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login400JSONResponse struct {
	Body    ApiError
	Headers Login400ResponseHeaders
}

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login401JSONResponse struct {
	Body    ApiError
	Headers Login401ResponseHeaders
}

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login403ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login403JSONResponse struct {
	Body    ApiError
	Headers Login403ResponseHeaders
}

func (response Login403JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Login413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login413JSONResponse struct {
	Body    ApiError
	Headers Login413ResponseHeaders
}

func (response Login413JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type Login415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login415JSONResponse struct {
	Body    ApiError
	Headers Login415ResponseHeaders
}

func (response Login415JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type Login422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login422JSONResponse struct {
	Body    ApiError
	Headers Login422ResponseHeaders
}

func (response Login422JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login429JSONResponse struct {
	Body    ApiError
	Headers Login429ResponseHeaders
}

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Login500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login500JSONResponse struct {
	Body    ApiError
	Headers Login500ResponseHeaders
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type Login503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Login503JSONResponse struct {
	Body    ApiError
	Headers Login503ResponseHeaders
}

func (response Login503JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Params LogoutParams
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	CacheControl *string
	SetCookie    *string
	XRequestID   *RequestId
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(204)
	return nil
}

type Logout400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Logout400JSONResponse struct {
	Body    ApiError
	Headers Logout400ResponseHeaders
}

func (response Logout400JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Logout403ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Logout403JSONResponse struct {
	Body    ApiError
	Headers Logout403ResponseHeaders
}

func (response Logout403JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Logout413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Logout413JSONResponse struct {
	Body    ApiError
	Headers Logout413ResponseHeaders
}

func (response Logout413JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type Logout422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Logout422JSONResponse struct {
	Body    ApiError
	Headers Logout422ResponseHeaders
}

func (response Logout422JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Logout500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Logout500JSONResponse struct {
	Body    ApiError
	Headers Logout500ResponseHeaders
}

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type Logout503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Logout503JSONResponse struct {
	Body    ApiError
	Headers Logout503ResponseHeaders
}

func (response Logout503JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Params RegisterParams
	Body   *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201ResponseHeaders struct {
	CacheControl *string
	SetCookie    *string
	XRequestID   *RequestId
}

type Register201JSONResponse struct {
	Body    SessionSnapshot
	Headers Register201ResponseHeaders
}

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register400JSONResponse struct {
	Body    ApiError
	Headers Register400ResponseHeaders
}

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register403ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register403JSONResponse struct {
	Body    ApiError
	Headers Register403ResponseHeaders
}

func (response Register403JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Register409ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register409JSONResponse struct {
	Body    ApiError
	Headers Register409ResponseHeaders
}

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register413JSONResponse struct {
	Body    ApiError
	Headers Register413ResponseHeaders
}

func (response Register413JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type Register415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register415JSONResponse struct {
	Body    ApiError
	Headers Register415ResponseHeaders
}

func (response Register415JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type Register422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register422JSONResponse struct {
	Body    ApiError
	Headers Register422ResponseHeaders
}

func (response Register422JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Register429ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register429JSONResponse struct {
	Body    ApiError
	Headers Register429ResponseHeaders
}

func (response Register429JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Register500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register500JSONResponse struct {
	Body    ApiError
	Headers Register500ResponseHeaders
}

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type Register503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type Register503JSONResponse struct {
	Body    ApiError
	Headers Register503ResponseHeaders
}

func (response Register503JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthLiveRequestObject struct {
	Params GetHealthLiveParams
}

type GetHealthLiveResponseObject interface {
	VisitGetHealthLiveResponse(w http.ResponseWriter) error
}

type GetHealthLive200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthLive200JSONResponse struct {
	Body    LiveStatus
	Headers GetHealthLive200ResponseHeaders
}

func (response GetHealthLive200JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthLive400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthLive400JSONResponse struct {
	Body    ApiError
	Headers GetHealthLive400ResponseHeaders
}

func (response GetHealthLive400JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthLive413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthLive413JSONResponse struct {
	Body    ApiError
	Headers GetHealthLive413ResponseHeaders
}

func (response GetHealthLive413JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthLive422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthLive422JSONResponse struct {
	Body    ApiError
	Headers GetHealthLive422ResponseHeaders
}

func (response GetHealthLive422JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthLive500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthLive500JSONResponse struct {
	Body    ApiError
	Headers GetHealthLive500ResponseHeaders
}

func (response GetHealthLive500JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthReadyRequestObject struct {
	Params GetHealthReadyParams
}

type GetHealthReadyResponseObject interface {
	VisitGetHealthReadyResponse(w http.ResponseWriter) error
}

type GetHealthReady200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthReady200JSONResponse struct {
	Body    ReadyStatus
	Headers GetHealthReady200ResponseHeaders
}

func (response GetHealthReady200JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthReady400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthReady400JSONResponse struct {
	Body    ApiError
	Headers GetHealthReady400ResponseHeaders
}

func (response GetHealthReady400JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthReady413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthReady413JSONResponse struct {
	Body    ApiError
	Headers GetHealthReady413ResponseHeaders
}

func (response GetHealthReady413JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthReady422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthReady422JSONResponse struct {
	Body    ApiError
	Headers GetHealthReady422ResponseHeaders
}

func (response GetHealthReady422JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthReady500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthReady500JSONResponse struct {
	Body    ApiError
	Headers GetHealthReady500ResponseHeaders
}

func (response GetHealthReady500JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthReady503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetHealthReady503JSONResponse struct {
	Body    ApiError
	Headers GetHealthReady503ResponseHeaders
}

func (response GetHealthReady503JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
	Params GetMeParams
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMe200JSONResponse struct {
	Body    SessionSnapshot
	Headers GetMe200ResponseHeaders
}

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMe400JSONResponse struct {
	Body    ApiError
	Headers GetMe400ResponseHeaders
}

func (response GetMe400JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMe401JSONResponse struct {
	Body    ApiError
	Headers GetMe401ResponseHeaders
}

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMe413JSONResponse struct {
	Body    ApiError
	Headers GetMe413ResponseHeaders
}

func (response GetMe413JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMe422JSONResponse struct {
	Body    ApiError
	Headers GetMe422ResponseHeaders
}

func (response GetMe422JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMe500JSONResponse struct {
	Body    ApiError
	Headers GetMe500ResponseHeaders
}

func (response GetMe500JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMe503JSONResponse struct {
	Body    ApiError
	Headers GetMe503ResponseHeaders
}

func (response GetMe503JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login login
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout logout
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Register register
	// (POST /api/v1/auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// GetHealthLive Check the process without querying dependencies
	// (GET /api/v1/health/live)
	GetHealthLive(ctx context.Context, request GetHealthLiveRequestObject) (GetHealthLiveResponseObject, error)
	// GetHealthReady Check PostgreSQL, schema and PostGIS
	// (GET /api/v1/health/ready)
	GetHealthReady(ctx context.Context, request GetHealthReadyRequestObject) (GetHealthReadyResponseObject, error)
	// GetMe get Me
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request, params LoginParams) {
	var request LoginRequestObject

	request.Params = params

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	var request LogoutRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request, params RegisterParams) {
	var request RegisterRequestObject

	request.Params = params

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthLive operation middleware
func (sh *strictHandler) GetHealthLive(w http.ResponseWriter, r *http.Request, params GetHealthLiveParams) {
	var request GetHealthLiveRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthLive(ctx, request.(GetHealthLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthLive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthLiveResponseObject); ok {
		if err := validResponse.VisitGetHealthLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthReady operation middleware
func (sh *strictHandler) GetHealthReady(w http.ResponseWriter, r *http.Request, params GetHealthReadyParams) {
	var request GetHealthReadyRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthReady(ctx, request.(GetHealthReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthReadyResponseObject); ok {
		if err := validResponse.VisitGetHealthReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request, params GetMeParams) {
	var request GetMeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F1fc9tIcv8qU8g+3O2Bf0TJXkuuqyxNwTazFMnjH8deS4saAU1yzgCGOzOQxN1ilfOQqlTeUnnLS/IN",
	"8pSq1D3eJ3A+QpwvkuoBQAIgKIk+nY/egx8sav72dPfMdP+6OfrZcLg/5wEEShonPxszoC4I/bFFnRm0",
	"eKAE9/B3F6Qj2FwxHhgnxgDknAcSJPFDqUjAFbkE4mAft2qYhnRm4FPsB0HoGydvjYBXpOICjAvTUIs5",
	"GCeGVIIFU2O5NI0B/BiCVG13c6q2C4FiEwaC8AlRMybJy9GoT6hS4M9VlQxg7tGFJAIUZQFRMyBcsCkL",
	"qEcuubsgIhrcZjnSvhIwMU6Mv6mtmVCLamVtTRCSNwQpGQ9anL9jsEliXE0cXU8cKuSM4tpsGdcg0UrN",
	"e4G3MEmfqtlvayYZUh+GTMFvO/TGJNdMzQgNCL2U3AsVkINGZcZDQTw2AcV8IDRwScCJ9JjLgikREMA1",
	"9apkCE4oAOfAlTIBLuFXIDSbhrqXyyS99LA88BZkwgXxuEM93aJKRjMgCaGKvwNNbgA4BAvI3w173Srp",
	"aY5ihTMD550eilwKfi1BED9UFFkhnxIaqhnKy6EK3HUFoZ7kUVfyutIaDp5XRjhTViB5vVgmlVojm3Nm",
	"CcEFfqauy3Bg6vUFn4NQDKRxMqGeBNOYp4pQw124S9p63BY2XJqGi3rk6b48gN7EOHl7e+9X1GOuXudp",
	"3HVp3t5jHNAryjyUyarLxdI0fJCSTos0jE6AWMHUY3JG4lZPieMxHJYoQQPpUQXkXcCvUQ9dkMjaHENN",
	"Y70VdtsAiWLhTtYMXdOaGXS9ufnl78FROOcz7i5eMe7RaC2fJLyNhaD+JuMlRwxu9oLjJcPWjbo5Z4EC",
	"scly1HvSj2r15uSh0ofLRNCpD4EiPhXvQCCf53gYCez1w69q1a9//bdfGUWnXJqLqwWsSTDzrC3iZkuA",
	"PhCpJ3fkJfiUFRzlI8F8IkMheBjoc+V6xhTIOXXAJB6/BuFQCXrl1zPuAaGuK0BKE4sCchUpf9RAgAw9",
	"hYPoycivqCI+l4o0Hh0RZ0YFdRQI+WvkmU9vOhBM1cw4aTw6Mg2fBcnvBxmOnp/Lr9/+8O35ubz4zbfJ",
	"h/Pz6vqj/PqrImWfUymvuSi4Uw4aH9//60HjCRkHDHmudwzRcpBV0uWr8jUvqqSrT0SF7OKCBFz41GM/",
	"QW4tB40n2bU0Mot5+8O5qpwL8sd//ON//O+/vf/4/n3l4/t/Pg8b9cYT/f/xx/f/+fEf/v3/3r+/+M3d",
	"WhTJNLXUIpVZn26pzXLW7DzvDc6sUxsV3TCNdvdVs9M+tV9azVNrkCpojQfDHhY8652+sUe9nt1pDl5Y",
	"hmmMu8Nxv98bjKxT+8w6bTft0Zs+VuiOzVG717WfN9sd69QwjTNr9LJ3and7I7vZ6fT+Xhc2x6OXVnfU",
	"bkWNB9bvxu2BdZqefWCdYotmZ2iYhnXWbHfsZmdgNU/f2APrRXs4sqIOvUH7RbubGx9vGjseSg86sgbd",
	"Zse+Zd5T66zfG1nd1hv7O+vNbVWpcVM1rV73eafdGuWK2127P+i9GFhDXMfAGvbGg5alyX3eG3dxlFfW",
	"y3arY9njbvNVs91pPusgL5utUfuVZQ+s7qjZsa3X7eEIR+iNR8NRs3va7r5AQnrtlhWNaw1eRYuyXvdj",
	"wuO+rd5Zv2ONMuyNq4aj5siKR22fWjaO0m5Z9ve9LhaPrI51Zo0Gb7ChpqrffHNmdUe5ZZ1anfYra5Bh",
	"wqA5suxO+6wdTdzq9Frf2b3xyO49t4dvui0s63Vb48FA82mgp7Fev2yOh1GPhJYsW1aitAaD3qDw2O+w",
	"KxgqqsJdT0oJ4gqEjUbXXdfkiPkgFfXnOKFcTZbsMv7OuLhrD8e9zMy0Rfu4TwX1QYH4LLfpjyGIRXS3",
	"zQwzdg12v14Tmgtqb7kRV73udScOgLqLT5K0w9QivegP//Lhv//nnz784cN/ffhD4VqdUAgInEyn714M",
	"C9v+mdXINHDkn3iQOdebktHaMyZn72AX3dOMSC0vNfjdipnx3uCG+nMPG8SfKrF9WDm446bMXpTNyve0",
	"8lO9cly1K4VXIc4reSgcyE9cPzg+Pjo8alQeX9JvKt/U6/XKE/yvvv6HtEzwClfGiRGGzM1acW/rlWNa",
	"mVz8/GRZWX0+Wla+Wf1yuKy8fXJMLy8yJcnng8Zyk2LTuKlMeWVjGbH7OAzoXM642lWFpZjY2m3D3zJW",
	"1eM8fx9ORSOSbbiZMwHSpmqn7qEEcVeHMbbZ0NcUvfEwZpoDhZQVqeyanA3jcDxqkcHz1uHh4bFJ4IY6",
	"ylsQyW7Q8HcioRCXTZmST4nLfcQcHO77NHAlCSUQlyp6qU1m5mvrcK2YjXrjcaV+XDlojOrfnBw8Ojms",
	"Vw8ah0ePHn+f1ke0pyvxGjOGsIs6iD8ayY9R9OMk8+P8vIofHi+/v78SFriku+lhuB7AFkAlD3QxU+DL",
	"O2W97jvQXfW1woJ21HmtuVQIiodTGLAfQ4irlQghryhF1BTpwebMqbOUBTKcTJiDXrYNAYipPhjBAx+U",
	"WNhSUQ9lxEMlmQs2aidzwE4dm/jrii7s68wC5lDPThFYeLaP4y2yy0kggCpwd92MW/zCFg24JjXy5Uzt",
	"+fjgakBp5Re6CBFNQs+rphU4cUvyPt7GKu+DQ6zO+LyM9aGdTJVafJGcNzGa3Xh7lZhc91fqtZV2qzLn",
	"V5WaqXAhadvvfvhUFoC5C5sqsDKXF0t95juhYGoxxIYRV+Kbq0REHxYRZcjCiHWGaQQUL2djk4frs53O",
	"2XewiBBTFkz4pkDOXvWJg2g+dVSVINfJDKinZgS1PCEJeYZXFcJb4D4lc48GAbjpNgJUKCIekKP6EfJj",
	"Lrgb6puxSpqeF9Uhk4dDi4hVpADvRh1VqMRhBZLEBKqkH156zIl6XnKXQUSMx3yGXFOcPH706PAxuVwo",
	"kFUyDmQ4n3OhOQpqxt2o/VH9EdnEGSJFanoev35KwkBjpLUJF8CmARHx+SI1xWGQWn9qYQS9oGSOI7Lp",
	"vleJRlmiVSZItUleV2LbuNI+jbU1WfJwESh6U4v8KgJR72iC+lMypwIP1wkDz81UNhpVsj7MSAxWE7yy",
	"UEZAqOcRFrgwh8CFAG0XFxQ4CtWdrA8XFBxWCJ8FTCrm6FhJTXt9NVxtQhlSHSOUtZVfRrhwI+hTMaVN",
	"mxYVw0g9V5ug2W8bpnEFQsaoW7VereMZxucQ0DkzTozDar16GDuZ+kSp0TmrXR3UcNfUPD5l+nCZc6kK",
	"glBcJcBjZrOifkRAeIRC4gquBQ+mJIHJyJRdRR2ZG+1NjxQATivlxROlPNA+8UAj8RaIgnGpJaD6rE4W",
	"9OGMjhZ4yv+X+nLT52GkjuvzML21Pi2st3FGYijTp8qJhITnBbgrDkQxRVwNXsWxxI/qh2QTeFyd4Xma",
	"IxYb6Qsfjdc09WunVLAC+PdiFW7BWz0CdQIFQeQ1zucei0CU2u8TWzZxPlYBAO02fRuXVxVIlQaQTwwr",
	"qunHJUcNY3lf9qaDE8vlMr9OXRBfBzhUo17fbQVpXzcpr2Bh5Yp6YR6quMvfKnJi010Ojje6JI5r2tS+",
	"Y5bbuM7c+6IVy3vLII8maDnkrLPQcUDKSeitT7gVxLeO/ldS4f+iGeP2tUyqgMYzVGUdKr+tZzauvjSz",
	"m/qOzum9vDSNo12USS8yF/FAK19r0Qop3YyJrKDOBPMiDg89d5UAwXFwpV29dKi1AApDknMxmAICNqI0",
	"D0nAvVVqFXkv0KUsi0yyQfFDadWnqgYCHtqAqiBP8ULZFGuO6AutTgefqE7piNUtOpUNbO2tXLNk7rEw",
	"04RGAjzcUYCbF3mR/ArjjHsnvkIq91B6BXRq4R3sKrxccLpAcBvh670T2gaFeyiwHI2RsB7tKKwtiQMF",
	"QtuaYrB3wttK6R4KcQutWpiNxo7C3Ez2KJDjZqNMol0aXn276pQCztcR6ijNK68A2IzoSdEt85mUUbBj",
	"ld5l1CJDPJtnty/KU8SePdSbTTIjlTneUWUyOSEF2pLLGdk7ceXo20NJZShEIT36BPcok2FTaMpmWuyl",
	"FZujcC8N2GwmkxbWruZPUZJUgcSKc6n2TmzFZO6h7IoIzQTLjJO3F6YhQ9+nYmGcGF6McN5U8Bqr6ACH",
	"caKDG1i4ij5oSVeSTCBjVQ4RIXmYnIdqO07epSoU1PMWiHb7c446dUIcD6hI8GxEkOPITqN+RK4xszeN",
	"qzOJoDUEClNfI7zMTSPGUjHPS3DjKnnOMW5A4AYjC8F0NQyiwhkEuMTV/wRcvcuJyEHrc4znKAWuSVjg",
	"eKFeLUrCn6tFFF6LQsmF2DsPIyi4BN+LwfcNop9hzjxGJ1N75Wm8PyQqnEcxWKZmNLOdCtaRTlTeuoK0",
	"+DNc3ynrK4ohZGD4o1si+HhMoD7BFWr3hFBPYLplfB7EWhiNptWwRJI/O5L8ZwByvwjg9tNgvvRWKxJV",
	"7jsDDwv5/7IxRpPkmPdlII6574mUAOSXBkCWmFWJWe2GWZVwSAmHlHDIPsAhkdP5kHiIgCmT8VfOtmQO",
	"xi20h6+z2hlV4C0ISMyTxC/Z07WzVmIUnyP3L5FJiUD89aT/HZTpf3+B9L9WRH0J1JQpf2XKXyblr8wY",
	"+3Izxuq7JiFsfUukQIRb2+6hIG+hdQ/FuZXaEoUr0wDLNMAyDbCEVMs0wDINsEwDLHHvEvf+xeDeYg12",
	"PhDyDVfxI86psuiFh5rHrrTwp6B1KAu7vgD1UjfD1/I+F/Z68ad+EXgnnC9hHX93fygz9XZggWIipN7s",
	"t/GBCAek1OmRyOXqHqhnmcD0hSUwlT5umWlSukVlpklpcf+lLe5l2kRr6Wg2Zm0nt3zyCLx+IwlD9Mkj",
	"Sw4D+XCWXGy16Szru802/fbtF2O3Re/tZp/ZTT+qq9/SNT/ZvEs/iZt9CXd5/+Wu3xIu0Gt83ywtdv0o",
	"lxZVafuVtl9p+5W2X2n7lbZfafv90tHWHcDUYfQMNEm/+Hy3KB5CEKd5QyVFwlPMNdUnAL5nPqHMwyRT",
	"BTcKjwmXScfj8mGTxD4L4Jqz3/tcqqmA4e86JolYpjNmsfhFe/hwRrufRlg3/lae4iL7TqlWshtF6ESB",
	"IAI8TssvQ+/Rl6FfgDr7ctDwMi/2S3gWs3Tq/lq+kbzry5Hb/hpZgdS2Nd1D8W0ndQ/luI3Y0ksvvfTS",
	"Sy+99NJLL3Oiypyoh86JSv0FobcXy0yG1BQUOYOHdNBrUZhJZXOkfChMnfKhxoIrzhzYXlH7mbnL22tr",
	"c7rYaBFw/Hv2zurPSd1SGw0igLob7QRz87QJQD+vaNx0TTSmQwMHvLtaSUVFjmF63qh2wgImZ1ur5zSU",
	"sLVWgAz9XLWigk0mOdqvYMYcD7aUFggB43+69XL5/wMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
