server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy same-origin always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'" always;

    location /api/ {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $api http://api:8080;
        proxy_pass $api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 60s;
        proxy_buffering off;
    }

    location = /health/live { access_log off; return 200 'ok'; }
    location /internal { return 404; }
    location /assets/ { try_files $uri =404; }
    location / { expires -1; try_files $uri $uri/ /index.html; }
}
