// Package internalapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package internalapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BodyViolationLocation.
const (
	Body BodyViolationLocation = "body"
)

// Valid indicates whether the value is a known member of the BodyViolationLocation enum.
func (e BodyViolationLocation) Valid() bool {
	switch e {
	case Body:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ACTIVERENTALEXISTS             ErrorCode = "ACTIVE_RENTAL_EXISTS"
	AUTHENTICATIONREQUIRED         ErrorCode = "AUTHENTICATION_REQUIRED"
	BODYTOOLARGE                   ErrorCode = "BODY_TOO_LARGE"
	CLOCKOUTOFSYNC                 ErrorCode = "CLOCK_OUT_OF_SYNC"
	CONCURRENCYRETRYEXHAUSTED      ErrorCode = "CONCURRENCY_RETRY_EXHAUSTED"
	CSRFINVALID                    ErrorCode = "CSRF_INVALID"
	DAILYLIMITREACHED              ErrorCode = "DAILY_LIMIT_REACHED"
	DELIVERYCONFLICT               ErrorCode = "DELIVERY_CONFLICT"
	EMAILALREADYREGISTERED         ErrorCode = "EMAIL_ALREADY_REGISTERED"
	IDEMPOTENCYCONFLICT            ErrorCode = "IDEMPOTENCY_CONFLICT"
	IDEMPOTENCYINPROGRESS          ErrorCode = "IDEMPOTENCY_IN_PROGRESS"
	IDEMPOTENCYKEYINVALID          ErrorCode = "IDEMPOTENCY_KEY_INVALID"
	IDEMPOTENCYKEYREQUIRED         ErrorCode = "IDEMPOTENCY_KEY_REQUIRED"
	INTERNALAUTHENTICATIONREQUIRED ErrorCode = "INTERNAL_AUTHENTICATION_REQUIRED"
	INTERNALERROR                  ErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS             ErrorCode = "INVALID_CREDENTIALS"
	INVALIDCURSOR                  ErrorCode = "INVALID_CURSOR"
	INVALIDHEADER                  ErrorCode = "INVALID_HEADER"
	INVALIDRENTALSTATE             ErrorCode = "INVALID_RENTAL_STATE"
	MALFORMEDJSON                  ErrorCode = "MALFORMED_JSON"
	METHODNOTALLOWED               ErrorCode = "METHOD_NOT_ALLOWED"
	ORIGINNOTALLOWED               ErrorCode = "ORIGIN_NOT_ALLOWED"
	OUTSIDESERVICEZONE             ErrorCode = "OUTSIDE_SERVICE_ZONE"
	OUTSTANDINGINVOICE             ErrorCode = "OUTSTANDING_INVOICE"
	PAYMENTINPROGRESS              ErrorCode = "PAYMENT_IN_PROGRESS"
	RATELIMITED                    ErrorCode = "RATE_LIMITED"
	RENTALCOMPLETED                ErrorCode = "RENTAL_COMPLETED"
	RESERVATIONEXPIRED             ErrorCode = "RESERVATION_EXPIRED"
	RESOURCENOTFOUND               ErrorCode = "RESOURCE_NOT_FOUND"
	SERVICEUNAVAILABLE             ErrorCode = "SERVICE_UNAVAILABLE"
	TELEMETRYSTALE                 ErrorCode = "TELEMETRY_STALE"
	UNSUPPORTEDMEDIATYPE           ErrorCode = "UNSUPPORTED_MEDIA_TYPE"
	VALIDATIONFAILED               ErrorCode = "VALIDATION_FAILED"
	VEHICLEUNAVAILABLE             ErrorCode = "VEHICLE_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ACTIVERENTALEXISTS:
		return true
	case AUTHENTICATIONREQUIRED:
		return true
	case BODYTOOLARGE:
		return true
	case CLOCKOUTOFSYNC:
		return true
	case CONCURRENCYRETRYEXHAUSTED:
		return true
	case CSRFINVALID:
		return true
	case DAILYLIMITREACHED:
		return true
	case DELIVERYCONFLICT:
		return true
	case EMAILALREADYREGISTERED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case IDEMPOTENCYINPROGRESS:
		return true
	case IDEMPOTENCYKEYINVALID:
		return true
	case IDEMPOTENCYKEYREQUIRED:
		return true
	case INTERNALAUTHENTICATIONREQUIRED:
		return true
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDCURSOR:
		return true
	case INVALIDHEADER:
		return true
	case INVALIDRENTALSTATE:
		return true
	case MALFORMEDJSON:
		return true
	case METHODNOTALLOWED:
		return true
	case ORIGINNOTALLOWED:
		return true
	case OUTSIDESERVICEZONE:
		return true
	case OUTSTANDINGINVOICE:
		return true
	case PAYMENTINPROGRESS:
		return true
	case RATELIMITED:
		return true
	case RENTALCOMPLETED:
		return true
	case RESERVATIONEXPIRED:
		return true
	case RESOURCENOTFOUND:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case TELEMETRYSTALE:
		return true
	case UNSUPPORTEDMEDIATYPE:
		return true
	case VALIDATIONFAILED:
		return true
	case VEHICLEUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for MarkServicedAction.
const (
	MarkServicedActionMarkServiced MarkServicedAction = "mark_serviced"
)

// Valid indicates whether the value is a known member of the MarkServicedAction enum.
func (e MarkServicedAction) Valid() bool {
	switch e {
	case MarkServicedActionMarkServiced:
		return true
	default:
		return false
	}
}

// Defines values for ParameterViolationLocation.
const (
	Header ParameterViolationLocation = "header"
	Path   ParameterViolationLocation = "path"
	Query  ParameterViolationLocation = "query"
)

// Valid indicates whether the value is a known member of the ParameterViolationLocation enum.
func (e ParameterViolationLocation) Valid() bool {
	switch e {
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for PointType.
const (
	PointTypePoint PointType = "Point"
)

// Valid indicates whether the value is a known member of the PointType enum.
func (e PointType) Valid() bool {
	switch e {
	case PointTypePoint:
		return true
	default:
		return false
	}
}

// Defines values for SetEnergyRemainingAction.
const (
	SetEnergyRemainingActionSetEnergyRemaining SetEnergyRemainingAction = "set_energy_remaining"
)

// Valid indicates whether the value is a known member of the SetEnergyRemainingAction enum.
func (e SetEnergyRemainingAction) Valid() bool {
	switch e {
	case SetEnergyRemainingActionSetEnergyRemaining:
		return true
	default:
		return false
	}
}

// Defines values for SetNextPaymentOutcomeAction.
const (
	SetNextPaymentOutcomeActionSetNextPaymentOutcome SetNextPaymentOutcomeAction = "set_next_payment_outcome"
)

// Valid indicates whether the value is a known member of the SetNextPaymentOutcomeAction enum.
func (e SetNextPaymentOutcomeAction) Valid() bool {
	switch e {
	case SetNextPaymentOutcomeActionSetNextPaymentOutcome:
		return true
	default:
		return false
	}
}

// Defines values for SetNextPaymentOutcomeOutcome.
const (
	Failed SetNextPaymentOutcomeOutcome = "failed"
	Paid   SetNextPaymentOutcomeOutcome = "paid"
)

// Valid indicates whether the value is a known member of the SetNextPaymentOutcomeOutcome enum.
func (e SetNextPaymentOutcomeOutcome) Valid() bool {
	switch e {
	case Failed:
		return true
	case Paid:
		return true
	default:
		return false
	}
}

// Defines values for SetPositionAction.
const (
	SetPositionActionSetPosition SetPositionAction = "set_position"
)

// Valid indicates whether the value is a known member of the SetPositionAction enum.
func (e SetPositionAction) Valid() bool {
	switch e {
	case SetPositionActionSetPosition:
		return true
	default:
		return false
	}
}

// Defines values for SetTelemetryStateAction.
const (
	SetTelemetryStateActionSetTelemetryState SetTelemetryStateAction = "set_telemetry_state"
)

// Valid indicates whether the value is a known member of the SetTelemetryStateAction enum.
func (e SetTelemetryStateAction) Valid() bool {
	switch e {
	case SetTelemetryStateActionSetTelemetryState:
		return true
	default:
		return false
	}
}

// Defines values for SetTelemetryStateTelemetryState.
const (
	Offline SetTelemetryStateTelemetryState = "offline"
	Online  SetTelemetryStateTelemetryState = "online"
)

// Valid indicates whether the value is a known member of the SetTelemetryStateTelemetryState enum.
func (e SetTelemetryStateTelemetryState) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	default:
		return false
	}
}

// Defines values for SourceKind.
const (
	Battery  SourceKind = "battery"
	Cng      SourceKind = "cng"
	Diesel   SourceKind = "diesel"
	Gasoline SourceKind = "gasoline"
	Lpg      SourceKind = "lpg"
)

// Valid indicates whether the value is a known member of the SourceKind enum.
func (e SourceKind) Valid() bool {
	switch e {
	case Battery:
		return true
	case Cng:
		return true
	case Diesel:
		return true
	case Gasoline:
		return true
	case Lpg:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	InsufficientEnergy   UnavailableReason = "insufficient_energy"
	OutsideServiceZone   UnavailableReason = "outside_service_zone"
	ServiceRequired      UnavailableReason = "service_required"
	TechnicalUnavailable UnavailableReason = "technical_unavailable"
	TelemetryStale       UnavailableReason = "telemetry_stale"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case InsufficientEnergy:
		return true
	case OutsideServiceZone:
		return true
	case ServiceRequired:
		return true
	case TechnicalUnavailable:
		return true
	case TelemetryStale:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Code    ErrorCode         `json:"code"`
	Details *ApiError_Details `json:"details,omitempty"`

	// Message Safe English message; clients translate known codes.
	Message string `json:"message"`

	// RequestId Example: example-request-1
	RequestId RequestId `json:"request_id"`
}

// ApiError_Details defines model for ApiError.Details.
type ApiError_Details struct {
	union json.RawMessage
}

// BodyViolation defines model for BodyViolation.
type BodyViolation struct {
	Code     string                `json:"code"`
	Location BodyViolationLocation `json:"location"`
	Message  string                `json:"message"`

	// Pointer JSON Pointer without the fragment marker.
	Pointer string `json:"pointer"`
}

// BodyViolationLocation defines model for BodyViolation.Location.
type BodyViolationLocation string

// CommandId Example: 11111111-1111-4111-8111-111111111111
type CommandId = string

// DailyLimitDetails The spent allowance and the moment it is restored, for the refusal that reports it.
type DailyLimitDetails struct {
	// DailyLimit The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
	DailyLimit DailyLimitState `json:"daily_limit"`
}

// DailyLimitState The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
type DailyLimitState struct {
	// Available Whether this account may still create a free reservation in the current service-timezone day. False means the day's allowance is spent; it is not a statement about the current moment or about a live rental, each of which the server checks again when a command arrives.
	Available bool `json:"available"`

	// ResetsAt The moment the allowance returns, being the start of the next day in the service timezone. It is the moment to display and never a Retry-After: an unfinished command answers with one second, which is not when the limit comes back.
	ResetsAt Timestamp `json:"resets_at"`
}

// DemoAction defines model for DemoAction.
type DemoAction struct {
	union json.RawMessage
}

// DemoResult defines model for DemoResult.
type DemoResult struct {
	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`
}

// EnergyDecimal Nonnegative canonical decimal, at most six fractional digits, no trailing fractional zeros or exponent.
//
// Example: 1200.125
type EnergyDecimal = string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// MarkServiced Example: {"action":"mark_serviced","action_id":"11111111-1111-4111-8111-111111111111","vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type MarkServiced struct {
	Action MarkServicedAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// MarkServicedAction defines model for MarkServiced.Action.
type MarkServicedAction string

// ParameterViolation defines model for ParameterViolation.
type ParameterViolation struct {
	Code      string                     `json:"code"`
	Location  ParameterViolationLocation `json:"location"`
	Message   string                     `json:"message"`
	Parameter string                     `json:"parameter"`
}

// ParameterViolationLocation defines model for ParameterViolation.Location.
type ParameterViolationLocation string

// Point defines model for Point.
type Point struct {
	// Coordinates WGS84 [longitude, latitude]. Latitude must be within -90..90.
	Coordinates Position  `json:"coordinates"`
	Type        PointType `json:"type"`
}

// PointType defines model for Point.Type.
type PointType string

// Position WGS84 [longitude, latitude]. Latitude must be within -90..90.
type Position = []float32

// RequestId Example: example-request-1
type RequestId = string

// ResourceId Example: 01994342-6ba7-7000-8000-000000000001
type ResourceId = string

// SetEnergyRemaining Example: {"action":"set_energy_remaining","action_id":"11111111-1111-4111-8111-111111111111","remaining":"0","source_kind":"battery","vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type SetEnergyRemaining struct {
	Action SetEnergyRemainingAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// Remaining Nonnegative canonical decimal, at most six fractional digits, no trailing fractional zeros or exponent.
	//
	// Example: 1200.125
	Remaining  EnergyDecimal `json:"remaining"`
	SourceKind SourceKind    `json:"source_kind"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// SetEnergyRemainingAction defines model for SetEnergyRemaining.Action.
type SetEnergyRemainingAction string

// SetNextPaymentOutcome Example: {"action":"set_next_payment_outcome","action_id":"11111111-1111-4111-8111-111111111111","outcome":"failed","rental_id":"01994342-6ba7-7000-8000-000000000001"}
type SetNextPaymentOutcome struct {
	Action SetNextPaymentOutcomeAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId                    `json:"action_id"`
	Outcome  SetNextPaymentOutcomeOutcome `json:"outcome"`

	// RentalId Example: 01994342-6ba7-7000-8000-000000000001
	RentalId ResourceId `json:"rental_id"`
}

// SetNextPaymentOutcomeAction defines model for SetNextPaymentOutcome.Action.
type SetNextPaymentOutcomeAction string

// SetNextPaymentOutcomeOutcome defines model for SetNextPaymentOutcome.Outcome.
type SetNextPaymentOutcomeOutcome string

// SetPosition Example: {"action":"set_position","action_id":"11111111-1111-4111-8111-111111111111","position":{"coordinates":[74.6,42.87],"type":"Point"},"vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type SetPosition struct {
	Action SetPositionAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`
	Position Point     `json:"position"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// SetPositionAction defines model for SetPosition.Action.
type SetPositionAction string

// SetTelemetryState Example: {"action":"set_telemetry_state","action_id":"11111111-1111-4111-8111-111111111111","telemetry_state":"offline","vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type SetTelemetryState struct {
	Action SetTelemetryStateAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId       CommandId                       `json:"action_id"`
	TelemetryState SetTelemetryStateTelemetryState `json:"telemetry_state"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// SetTelemetryStateAction defines model for SetTelemetryState.Action.
type SetTelemetryStateAction string

// SetTelemetryStateTelemetryState defines model for SetTelemetryState.TelemetryState.
type SetTelemetryStateTelemetryState string

// SourceKind defines model for SourceKind.
type SourceKind string

// TickRequest defines model for TickRequest.
type TickRequest struct {
	// TickId Example: 11111111-1111-4111-8111-111111111111
	TickId CommandId `json:"tick_id"`
}

// TickResult defines model for TickResult.
type TickResult struct {
	ChangedVehicleIds  []ResourceId `json:"changed_vehicle_ids"`
	CompletedRentalIds []ResourceId `json:"completed_rental_ids"`

	// ProcessedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ProcessedAt Timestamp `json:"processed_at"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`

	// TickId Example: 11111111-1111-4111-8111-111111111111
	TickId CommandId `json:"tick_id"`
}

// Timestamp UTC RFC3339, exactly six fractional digits; domain commands use database time.
//
// Example: 2026-09-12T07:15:30.123456Z
type Timestamp = string

// UnavailableDetails defines model for UnavailableDetails.
type UnavailableDetails struct {
	UnavailableReasons []UnavailableReason `json:"unavailable_reasons"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// ValidationDetails defines model for ValidationDetails.
type ValidationDetails struct {
	Violations []Violation `json:"violations"`
}

// Violation defines model for Violation.
type Violation struct {
	union json.RawMessage
}

// ApplyDemoActionParams defines parameters for ApplyDemoAction.
type ApplyDemoActionParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// SimulationTickParams defines parameters for SimulationTick.
type SimulationTickParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ApplyDemoActionJSONRequestBody defines body for ApplyDemoAction for application/json ContentType.
type ApplyDemoActionJSONRequestBody = DemoAction

// SimulationTickJSONRequestBody defines body for SimulationTick for application/json ContentType.
type SimulationTickJSONRequestBody = TickRequest

// AsValidationDetails returns the union data inside the ApiError_Details as a ValidationDetails
func (t ApiError_Details) AsValidationDetails() (ValidationDetails, error) {
	var body ValidationDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationDetails overwrites any union data inside the ApiError_Details as the provided ValidationDetails
func (t *ApiError_Details) FromValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationDetails performs a merge with any union data inside the ApiError_Details, using the provided ValidationDetails
func (t *ApiError_Details) MergeValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnavailableDetails returns the union data inside the ApiError_Details as a UnavailableDetails
func (t ApiError_Details) AsUnavailableDetails() (UnavailableDetails, error) {
	var body UnavailableDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnavailableDetails overwrites any union data inside the ApiError_Details as the provided UnavailableDetails
func (t *ApiError_Details) FromUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnavailableDetails performs a merge with any union data inside the ApiError_Details, using the provided UnavailableDetails
func (t *ApiError_Details) MergeUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDailyLimitDetails returns the union data inside the ApiError_Details as a DailyLimitDetails
func (t ApiError_Details) AsDailyLimitDetails() (DailyLimitDetails, error) {
	var body DailyLimitDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDailyLimitDetails overwrites any union data inside the ApiError_Details as the provided DailyLimitDetails
func (t *ApiError_Details) FromDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDailyLimitDetails performs a merge with any union data inside the ApiError_Details, using the provided DailyLimitDetails
func (t *ApiError_Details) MergeDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApiError_Details) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiError_Details) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSetTelemetryState returns the union data inside the DemoAction as a SetTelemetryState
func (t DemoAction) AsSetTelemetryState() (SetTelemetryState, error) {
	var body SetTelemetryState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetTelemetryState overwrites any union data inside the DemoAction as the provided SetTelemetryState
func (t *DemoAction) FromSetTelemetryState(v SetTelemetryState) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_telemetry_state"}`))
	t.union = b
	return err
}

// MergeSetTelemetryState performs a merge with any union data inside the DemoAction, using the provided SetTelemetryState
func (t *DemoAction) MergeSetTelemetryState(v SetTelemetryState) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_telemetry_state"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetPosition returns the union data inside the DemoAction as a SetPosition
func (t DemoAction) AsSetPosition() (SetPosition, error) {
	var body SetPosition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetPosition overwrites any union data inside the DemoAction as the provided SetPosition
func (t *DemoAction) FromSetPosition(v SetPosition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_position"}`))
	t.union = b
	return err
}

// MergeSetPosition performs a merge with any union data inside the DemoAction, using the provided SetPosition
func (t *DemoAction) MergeSetPosition(v SetPosition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_position"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetEnergyRemaining returns the union data inside the DemoAction as a SetEnergyRemaining
func (t DemoAction) AsSetEnergyRemaining() (SetEnergyRemaining, error) {
	var body SetEnergyRemaining
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetEnergyRemaining overwrites any union data inside the DemoAction as the provided SetEnergyRemaining
func (t *DemoAction) FromSetEnergyRemaining(v SetEnergyRemaining) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_energy_remaining"}`))
	t.union = b
	return err
}

// MergeSetEnergyRemaining performs a merge with any union data inside the DemoAction, using the provided SetEnergyRemaining
func (t *DemoAction) MergeSetEnergyRemaining(v SetEnergyRemaining) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_energy_remaining"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMarkServiced returns the union data inside the DemoAction as a MarkServiced
func (t DemoAction) AsMarkServiced() (MarkServiced, error) {
	var body MarkServiced
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMarkServiced overwrites any union data inside the DemoAction as the provided MarkServiced
func (t *DemoAction) FromMarkServiced(v MarkServiced) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"mark_serviced"}`))
	t.union = b
	return err
}

// MergeMarkServiced performs a merge with any union data inside the DemoAction, using the provided MarkServiced
func (t *DemoAction) MergeMarkServiced(v MarkServiced) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"mark_serviced"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetNextPaymentOutcome returns the union data inside the DemoAction as a SetNextPaymentOutcome
func (t DemoAction) AsSetNextPaymentOutcome() (SetNextPaymentOutcome, error) {
	var body SetNextPaymentOutcome
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetNextPaymentOutcome overwrites any union data inside the DemoAction as the provided SetNextPaymentOutcome
func (t *DemoAction) FromSetNextPaymentOutcome(v SetNextPaymentOutcome) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_next_payment_outcome"}`))
	t.union = b
	return err
}

// MergeSetNextPaymentOutcome performs a merge with any union data inside the DemoAction, using the provided SetNextPaymentOutcome
func (t *DemoAction) MergeSetNextPaymentOutcome(v SetNextPaymentOutcome) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_next_payment_outcome"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DemoAction) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"action"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DemoAction) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "mark_serviced":
		return t.AsMarkServiced()
	case "set_energy_remaining":
		return t.AsSetEnergyRemaining()
	case "set_next_payment_outcome":
		return t.AsSetNextPaymentOutcome()
	case "set_position":
		return t.AsSetPosition()
	case "set_telemetry_state":
		return t.AsSetTelemetryState()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DemoAction) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DemoAction) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBodyViolation returns the union data inside the Violation as a BodyViolation
func (t Violation) AsBodyViolation() (BodyViolation, error) {
	var body BodyViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBodyViolation overwrites any union data inside the Violation as the provided BodyViolation
func (t *Violation) FromBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBodyViolation performs a merge with any union data inside the Violation, using the provided BodyViolation
func (t *Violation) MergeBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterViolation returns the union data inside the Violation as a ParameterViolation
func (t Violation) AsParameterViolation() (ParameterViolation, error) {
	var body ParameterViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterViolation overwrites any union data inside the Violation as the provided ParameterViolation
func (t *Violation) FromParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterViolation performs a merge with any union data inside the Violation, using the provided ParameterViolation
func (t *Violation) MergeParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Violation) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Violation) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ApplyDemoAction apply Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyDemoAction(w http.ResponseWriter, r *http.Request, params ApplyDemoActionParams)
	// SimulationTick simulation Tick
	// (POST /internal/v1/simulation/tick)
	SimulationTick(w http.ResponseWriter, r *http.Request, params SimulationTickParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ApplyDemoAction apply Demo Action
// (POST /internal/v1/demo/actions)
func (_ Unimplemented) ApplyDemoAction(w http.ResponseWriter, r *http.Request, params ApplyDemoActionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SimulationTick simulation Tick
// (POST /internal/v1/simulation/tick)
func (_ Unimplemented) SimulationTick(w http.ResponseWriter, r *http.Request, params SimulationTickParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApplyDemoAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyDemoAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyDemoActionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyDemoAction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SimulationTick operation middleware
func (siw *ServerInterfaceWrapper) SimulationTick(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SimulationTickParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SimulationTick(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/demo/actions", wrapper.ApplyDemoAction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/simulation/tick", wrapper.SimulationTick)
	})

	return r
}

type ApplyDemoActionRequestObject struct {
	Params ApplyDemoActionParams
	Body   *ApplyDemoActionJSONRequestBody
}

type ApplyDemoActionResponseObject interface {
	VisitApplyDemoActionResponse(w http.ResponseWriter) error
}

type ApplyDemoAction200ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type ApplyDemoAction200JSONResponse struct {
	Body    DemoResult
	Headers ApplyDemoAction200ResponseHeaders
}

func (response ApplyDemoAction200JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction400JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction400ResponseHeaders
}

func (response ApplyDemoAction400JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction401JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction401ResponseHeaders
}

func (response ApplyDemoAction401JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction404ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction404JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction404ResponseHeaders
}

func (response ApplyDemoAction404JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction409ResponseHeaders struct {
	CacheControl *string
	RetryAfter   *int
	XRequestID   *RequestId
}

type ApplyDemoAction409JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction409ResponseHeaders
}

func (response ApplyDemoAction409JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction413JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction413ResponseHeaders
}

func (response ApplyDemoAction413JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction415JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction415ResponseHeaders
}

func (response ApplyDemoAction415JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction422JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction422ResponseHeaders
}

func (response ApplyDemoAction422JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction500JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction500ResponseHeaders
}

func (response ApplyDemoAction500JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction503JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction503ResponseHeaders
}

func (response ApplyDemoAction503JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTickRequestObject struct {
	Params SimulationTickParams
	Body   *SimulationTickJSONRequestBody
}

type SimulationTickResponseObject interface {
	VisitSimulationTickResponse(w http.ResponseWriter) error
}

type SimulationTick200ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type SimulationTick200JSONResponse struct {
	Body    TickResult
	Headers SimulationTick200ResponseHeaders
}

func (response SimulationTick200JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick400JSONResponse struct {
	Body    ApiError
	Headers SimulationTick400ResponseHeaders
}

func (response SimulationTick400JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick401JSONResponse struct {
	Body    ApiError
	Headers SimulationTick401ResponseHeaders
}

func (response SimulationTick401JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick409ResponseHeaders struct {
	CacheControl *string
	RetryAfter   *int
	XRequestID   *RequestId
}

type SimulationTick409JSONResponse struct {
	Body    ApiError
	Headers SimulationTick409ResponseHeaders
}

func (response SimulationTick409JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick413JSONResponse struct {
	Body    ApiError
	Headers SimulationTick413ResponseHeaders
}

func (response SimulationTick413JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick415JSONResponse struct {
	Body    ApiError
	Headers SimulationTick415ResponseHeaders
}

func (response SimulationTick415JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick422JSONResponse struct {
	Body    ApiError
	Headers SimulationTick422ResponseHeaders
}

func (response SimulationTick422JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick500JSONResponse struct {
	Body    ApiError
	Headers SimulationTick500ResponseHeaders
}

func (response SimulationTick500JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick503JSONResponse struct {
	Body    ApiError
	Headers SimulationTick503ResponseHeaders
}

func (response SimulationTick503JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ApplyDemoAction apply Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyDemoAction(ctx context.Context, request ApplyDemoActionRequestObject) (ApplyDemoActionResponseObject, error)
	// SimulationTick simulation Tick
	// (POST /internal/v1/simulation/tick)
	SimulationTick(ctx context.Context, request SimulationTickRequestObject) (SimulationTickResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ApplyDemoAction operation middleware
func (sh *strictHandler) ApplyDemoAction(w http.ResponseWriter, r *http.Request, params ApplyDemoActionParams) {
	var request ApplyDemoActionRequestObject

	request.Params = params

	var body ApplyDemoActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyDemoAction(ctx, request.(ApplyDemoActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyDemoAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyDemoActionResponseObject); ok {
		if err := validResponse.VisitApplyDemoActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SimulationTick operation middleware
func (sh *strictHandler) SimulationTick(w http.ResponseWriter, r *http.Request, params SimulationTickParams) {
	var request SimulationTickRequestObject

	request.Params = params

	var body SimulationTickJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SimulationTick(ctx, request.(SimulationTickRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SimulationTick")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SimulationTickResponseObject); ok {
		if err := validResponse.VisitSimulationTickResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7c+K4lv8qKu+t2nvv2oQ8+hH6jy0G3N3sEMgC6Ts96axL2AJ0Y0seSaTDzPLdt47kNyZAKj3F3Ur+",
	"SMDW47x0dPQ7R/nD8nkUc0aYklbrD2tBcECE/tjB/oJ0OFOCh/A9INIXNFaUM6tljYiMOZNEomgpFWJc",
	"oSlBPvQJGpZtSX9BIgz9CFtGVuvWYtyRigti3dmWWsXEallSCcrm1nptW72ARDFXhPmrEYlDvCLB5qRK",
	"LAniLFyhGRcII6FbIj5DakGQxA8kQFzQOWU4RFJhtZQIswBNebAqE5UQMOU8JJhpCkbktyWRqlczby8g",
	"TNEZJcLMRSX6PJlcI6wUiWLVQIZkiQRRmDJNTUYHTI6EGdyjFeH8RZCZ1bL+7SRXw4l5K09yggx5Sqza",
	"M0VEnTKUWCEMLxFnBEnicxYYITFEmTML6XyhkM+jCLN6/ZzmaqFMkTkR1nq9Thtqi2jH1BWCawJwEFCY",
	"HYfXgsdEKEqk1ZrhUBLbiguPwMICsotXPW4HGq5tKwAphrovZ2Q4s1q3T/f+gkMaYCCnm3Rd20/3uGH4",
	"AdMQT0Oyb5cupuGqTyOqsh53a9uKiJR4TjaVMsYzglw2D6lcoKTVB+SHFEZFSmAmQ6wIumf8O0MgJNmw",
	"Mh2kS8O2ctM5zGCgHxWwjG6NCnJaS4PmeufTfxJfwZw/8WD1hfIQG16epe4NRkLuZ+OlTgEWR41DKIl1",
	"413MwUJr1sF/jYcDdG3eou9ULfhS6cU4E3geEaZQhMU9ESDnGBavgF7/89eTxt//9p9/ser8UlGKGQM5",
	"CXZVtHXS7JhlZzwLecRRHEKD0+TH0b8u4Nf79Gv6Y9nWjIsIK6tlLZc0KBN+23QusTO7++P92sk+X6yd",
	"i+zL+dq5fX+Jp3elJ+nn07P1Jte29ejMubMh9U3732UXZeVMwEXHoAQchvw7Zj7Rzhn0E3GtHaoQBSeq",
	"94nA1g4MXgsyW0ocIrXACpw+F0oiqrQaS7YXAI1eCETuWiw5O2OFFdlQdnGoOqVW+x8uDD1DQRh8hmaC",
	"ALeSiAdtadJGguAAfV8QtQDnLvROCzsfUzgEaflLAV8aqKeFFxBBYRucCR6ZXVHLsjRoumFi3+dLpmyU",
	"bFnQgvoEKRqR3zkjNhJYT6sWmOUj4qkkCb04nT4haFMjmZvdXK3/SJjS+2lCC4rwCklFwxD5goB7xBtC",
	"SclNp07IdlKyUYBXDfQRxI4igpnUrQO8+ndZkDaVxho/JFZn5ApBA9G2iKep80jnSYyUi+QdRiF9IAnn",
	"NiLYX4BMvi+ov8jkSQTyF8S/lwjPITT4viAMxGZcAsIC1FV0/FlIAuYoiZIe1raMw3CPnXBCIyIVjmJr",
	"fVdncwkPWo2ZKARRSwG2NiWUzROrwUKldsLIowL5bbOT1PYKK1lxFFCpozNgkxEQBEY6UHF0FNOC0GTJ",
	"ZpRRuSBBLhEmvxMhtfsuBDN2ItdEU1qMMJ9eoNCZSDTF/n1jYyHnFliUaO2SJhFv++kWFVAQXkQZVibk",
	"iXAcgy/UH8W9l4gh2KaLKyzux2kb25JEeYQRMV95gkSYMj1WfdcxUa5uOspamgFAFV6MVyBkjy8VMP7E",
	"IAPyqK5N62HS2IwTc0kTs9jW9zptYnooEpII1OdJ4++2dpykLRPHmrmE1QBrarGR8dreM7yrG3Nnj4z8",
	"PdpWZb2rS0mze4xfo4b1XWJwIyKXoTowxjIS3CMkzEMPCOW1P/Jg2Vqtvf1IdTllU5cHrFtQRq5d4tMI",
	"15whB5wxMscKvKiPGWfUxyEKTHMbYXC5UiFJHyGA841sUEDnVEkbMQ5BNA3BZRVe/04El+CkyaNhCnxr",
	"Ieg6azYbp2dvKhFg839vT51LHSXd/f1vf/32raE//tG036z1m9r40Lbyc0shqL1q9z8OR1du14OA1LKt",
	"3uBLu9/rep/ddtcdFR50bkbjITz4adj96k2GQ6/fHn1yLdu6GYxvrq+Ho4nb9a7cbq/tTb5ewwvdsT3p",
	"DQfex3av73Yt27pyJ5+HXW8wnHjtfn/4D/2wfTP57A4mvY5pPHL/+6Y3crvF2UduF1q0+2PLttyrdq/v",
	"tfsjt9396o3cT73xxDUdhqPep96gMn5nPProJUPpQSfuaNDue0/M23WvrocTd9D56v3sfn3qVWHcwpvO",
	"cPCx3+tMKo97A+96NPw0csfAx8gdD29GHVeT+3F4M4BRvrife52+690M2l/avX77pz7Ist2Z9L643sgd",
	"TNp9z/2lN57ACN12r//V6/euehNv5LY7n40QbibjSXvQ7Q0+AXnDXsc1s7mjL4ZV95frhJ1kxM7w6rrv",
	"TkpCT16NJ+2Jm4za67oejNLruN6vwwE8nrh998qdjL5CQ03rdfvrlTuYVJjtuv3eF3dUEs2oPXEN9UZP",
	"/WHnZ294M/GGH73x10EHng0HnZvRSEtvpKdxf/ncvhmbHiktZWFlCnZHo+Go9tBW8ou7PFq2JlN3ZrUq",
	"+6pd9HP7HpceyIL6ITF9mqeXlxfnF2fO2yl+57xrNpvOe/jVzH9OCxtUybsWV3SZrjrWn+eRi8TuOttL",
	"vhQ+qTncFz2y+VwWQ51nvsYCR0QR8aec8n9bErEyHndh2QnIePixP6W55u0TJ/Ws115ndY0eHCwLLgKI",
	"E4ncpcZCVJLMnUvJTH23C4XQb+3SpPWMJDNtnrs+jd9foNuQszlVy4DYCCwAPt01UD/5aGDdKdFxOGXI",
	"uWw2GpdN2EypIpE0UfAjjYD20/dN24ooM98c/TUhiC2jKRFatfixZ3qe6cb5l6QpFgKvNPyQ8+ZwAabS",
	"sjJqnZRYq4rZ5pt88slJUC4H/EKEH/uEzdXCap2evdcUZN/LoErb+RU7vzedy4bn3P1H7bZfWI2liffy",
	"N8+CdN79CEinJvR9jteuPdk8y3kXD0ZNy7aMlL17ymCQqRbT6kc5+Vo2Xs7Xi6KMn+pVjprXFSnsOGzo",
	"pj9T9udtL2X6bKtOdrlbqj8NPdfqao/Dz7K8/Cw9wzQkhhEAdl7exmqJfjk747lM01ljrPWUcHZXm2TI",
	"eH1ZQ8kHzinbYhfFHetZ1hDniMUzLCAuTF/a0W/fXTTe2hdnjffvcsrNZr3+ga4oo+flTKPI4tNRSg1z",
	"P9CB1LBasowK+vNc+6hCWM8yk00cjM9mIWXkR25L1UlfziQ22Mkn5ixhK2WwbtY/yUK2C6BgKPneV8ww",
	"ZkHDHEuecBRQIklo2VYYQ6Tib9noJ9S/T0LMA48Eivr3h6miGuUnA9Qxash6BmzoLzCbk8DLRasfZwH9",
	"vuqrhOxrW1eRhESRwMsc/ksNHQvuEylJkCRC9oQtnwt32i+nuzIJFU7sWm1skWS9FaQ0b5zwbiYdNPrY",
	"OT8/v7QRecS+Clf1MOoHFHAI19L0i0RLCbkyhadYmgxPGT89a569dZqXzunZpPmudfqmdQ5w6vnFm7e/",
	"Fg82AZzdUrbz0823bwEcZuDPWfpnYv60Sn++fWvAh7frX/c/zdTUdBy2PJb5AJ4gWHK2vw0XJh/prta6",
	"eMo93TjlLhn9bUmS10osSdWK6qips4PNmQvejzK5nM2oTwlLDzdVb6oTY3ypJA1IinF5kNZL7Be+ZnRB",
	"X3+hgXqvQGCt99ysyjlMHQ8pNLW/FnI060npV0VdmKlOwiWMbL+UVbmAZleKqAaNW9+ttQvzl4Kq1Rga",
	"GqlAzmjC70kNsBOQiHu+qdjzlG6T1G/pxDLBQqNgCX8LpbS7G9NoGUKOc8uoMn2/75BAOGUzvjnUdYgZ",
	"IwG6+nKNNJ3YVx8gkRMLHiy1Z0ILzIKQCNlAuppHZHWG4Jh0TaKTFCWitKKwgYZQEwigX4iMTKFkhAjC",
	"fCIRFkmymwQN1GPgi3CIGFHfubjX5YQfEHlMHseCP67SjDi6aF400E88oMkwOttMAkhvn709O724QNOV",
	"IrKBftKSQFpCpqkkgDwqgmIoAcAxntKQqpWd5MJ9zu9hVC4QJFJsnSZPMTddMUACNCUzLgiKsZBpYj5x",
	"1zFehRwHDXRFpX4H3Sl7gCWXUrGiJAwQ1bWLIJmL5inalaVpoBsml3HMBbAZEbXggeHnovkGbeaZTJq+",
	"DdL9gJZM17KdANF0zpBI9nVThLlkFPYQOPWSoKhxQIXTOS7QZvqmgXSWzVhAWoNoo1+cJDRzel09QW4O",
	"4xVT+PHE4MyImN5mguYHLU6okNHiKb48O2ug3GmhpAwRgS8lWpU4DBFlAYkJA6mGK2hDfAUuEOVOBOok",
	"4IUASFQq6usa0BONgp8AtyllQHVSSXaS4dRIQ566IoQqved2sBgvMLhVRFPzTVYl0AmjwNJH7euejpuF",
	"NMvttNFsNDUkEBOGY2q1rPNGs3GeIPHanZykI548nJ7AKCcmQtAvYy7V5ioeE+Uo7jzgEKpxYxCN5hrU",
	"k5S8wM6v6UoqdPPyXKHjVlOamkb9H1ASCqVmDc5hFlJfyQYCtAglaAlKEARdvOPz2KxEKBJJi3DM4pqH",
	"fIrDBkoMxJTg6soy4/NBuBnhgOFa7TgOV4X6j0LeQGpnT4FzozbLtpgpZCia4LPKeu+ySkzYMAzywBRJ",
	"MhBxHFKTxzj5Z7qvm0BM1hSh/GFpjRxBPm29rdiljsR/CfB4/VT1zTaujgycXFcrf7bR/a8Co623FCZt",
	"4+sY4Z+8wn5nvWrunNbl+FUfHmwri5RgpLNmc39vUqko2lcUpfP1kwfDg5hMkA3NZGXjWfpwfp4twyws",
	"bGTp5PzOilO4tFI3WdL+pHTBpXwFxSneQXlqjLprK2u7vDHsGKK4H6xt6+IQzWmmK9VFRfs3Wfpqi0Ka",
	"Pc2gIp8vwyC7xpNiEOWbAnWJVSC5Uu9UQ0ClxcsSsLd1ZfdXamyrLCIbbVD8Ulb2XNMA1EMHqw7IFPzp",
	"plorRN9pczo92Jx2FHLVGtiOPkep8Z00H6XOd1BtlH5xoNI3T111aq5pdYSKraXyCFVZQ6dR3uWhK7au",
	"RLJulda1e+nNYFth5g56ik2P0VnUiM5G2xl4KXMrXJjYbW3ZBdEXdjmHVeBqGz49P9CGKwXQNdZSaXGE",
	"RrJB4RE6nQqNRllvDlTWluL0GqVtaXmEyttK6REqcQutWplnZwcqc/NCQY0eNxuVrmkXUzW3WadC1iiv",
	"CjZXfqsGAM2QnhRwusiA2oV7ti3rBNCdsHLn+liMp048R2g3m2SCNN8848RZugrw1IHAtDjm8D+l8JiD",
	"/eTKhVbWoTtr3W2OGo3VNTtCtdWTeYS6qyO0lNPVnrKQzb29g3SAXEYRFiurpfW6Ql2d2EmTEo8OeE8n",
	"ueBuUpDwNMusaTNwzL8+sVpWbBKumsJSpidPH51Atcr2ZE9b8Qiyh3BT3dd+GnFWqRDRVSg2wsGDudQf",
	"ltJTQEySAoQUEIL5UK9ro6wcJr00bBJGgP7p/6hCsMoSsaX/qGLaZP/ggTwqgVHE9Wxw8U9nEyAd1UBj",
	"HBHUS9KUmHF94bwuy8ST/8yRM3RI+micsQu1WceePSoVqO2H9u69doslcz8Cp64tYbvdD22/21andntX",
	"LTPbUee0P/Rt/2BJv2Llr1j5K1b+ipW/YuXPxspf4dZXuPUVbn2FW1/h1le49RVufYVbX+HWV7j1FW79",
	"fwm3Vu+6VDHXAmyZAHnPR1zX6/8bAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
