// Package internalapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package internalapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BodyViolationLocation.
const (
	Body BodyViolationLocation = "body"
)

// Valid indicates whether the value is a known member of the BodyViolationLocation enum.
func (e BodyViolationLocation) Valid() bool {
	switch e {
	case Body:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ACTIVERENTALEXISTS             ErrorCode = "ACTIVE_RENTAL_EXISTS"
	AUTHENTICATIONREQUIRED         ErrorCode = "AUTHENTICATION_REQUIRED"
	BODYTOOLARGE                   ErrorCode = "BODY_TOO_LARGE"
	CLOCKOUTOFSYNC                 ErrorCode = "CLOCK_OUT_OF_SYNC"
	CONCURRENCYRETRYEXHAUSTED      ErrorCode = "CONCURRENCY_RETRY_EXHAUSTED"
	CSRFINVALID                    ErrorCode = "CSRF_INVALID"
	DAILYLIMITREACHED              ErrorCode = "DAILY_LIMIT_REACHED"
	DELIVERYCONFLICT               ErrorCode = "DELIVERY_CONFLICT"
	EMAILALREADYREGISTERED         ErrorCode = "EMAIL_ALREADY_REGISTERED"
	IDEMPOTENCYCONFLICT            ErrorCode = "IDEMPOTENCY_CONFLICT"
	IDEMPOTENCYINPROGRESS          ErrorCode = "IDEMPOTENCY_IN_PROGRESS"
	IDEMPOTENCYKEYINVALID          ErrorCode = "IDEMPOTENCY_KEY_INVALID"
	IDEMPOTENCYKEYREQUIRED         ErrorCode = "IDEMPOTENCY_KEY_REQUIRED"
	INTERNALAUTHENTICATIONREQUIRED ErrorCode = "INTERNAL_AUTHENTICATION_REQUIRED"
	INTERNALERROR                  ErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS             ErrorCode = "INVALID_CREDENTIALS"
	INVALIDCURSOR                  ErrorCode = "INVALID_CURSOR"
	INVALIDHEADER                  ErrorCode = "INVALID_HEADER"
	INVALIDRENTALSTATE             ErrorCode = "INVALID_RENTAL_STATE"
	MALFORMEDJSON                  ErrorCode = "MALFORMED_JSON"
	METHODNOTALLOWED               ErrorCode = "METHOD_NOT_ALLOWED"
	ORIGINNOTALLOWED               ErrorCode = "ORIGIN_NOT_ALLOWED"
	OUTSIDESERVICEZONE             ErrorCode = "OUTSIDE_SERVICE_ZONE"
	OUTSTANDINGINVOICE             ErrorCode = "OUTSTANDING_INVOICE"
	PAYMENTINPROGRESS              ErrorCode = "PAYMENT_IN_PROGRESS"
	RATELIMITED                    ErrorCode = "RATE_LIMITED"
	RENTALCOMPLETED                ErrorCode = "RENTAL_COMPLETED"
	RESERVATIONEXPIRED             ErrorCode = "RESERVATION_EXPIRED"
	RESOURCENOTFOUND               ErrorCode = "RESOURCE_NOT_FOUND"
	SERVICEUNAVAILABLE             ErrorCode = "SERVICE_UNAVAILABLE"
	SOURCECAPACITYEXCEEDED         ErrorCode = "SOURCE_CAPACITY_EXCEEDED"
	SOURCENOTCARRIED               ErrorCode = "SOURCE_NOT_CARRIED"
	TELEMETRYSTALE                 ErrorCode = "TELEMETRY_STALE"
	UNSUPPORTEDMEDIATYPE           ErrorCode = "UNSUPPORTED_MEDIA_TYPE"
	VALIDATIONFAILED               ErrorCode = "VALIDATION_FAILED"
	VEHICLEINUSE                   ErrorCode = "VEHICLE_IN_USE"
	VEHICLEUNAVAILABLE             ErrorCode = "VEHICLE_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ACTIVERENTALEXISTS:
		return true
	case AUTHENTICATIONREQUIRED:
		return true
	case BODYTOOLARGE:
		return true
	case CLOCKOUTOFSYNC:
		return true
	case CONCURRENCYRETRYEXHAUSTED:
		return true
	case CSRFINVALID:
		return true
	case DAILYLIMITREACHED:
		return true
	case DELIVERYCONFLICT:
		return true
	case EMAILALREADYREGISTERED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case IDEMPOTENCYINPROGRESS:
		return true
	case IDEMPOTENCYKEYINVALID:
		return true
	case IDEMPOTENCYKEYREQUIRED:
		return true
	case INTERNALAUTHENTICATIONREQUIRED:
		return true
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDCURSOR:
		return true
	case INVALIDHEADER:
		return true
	case INVALIDRENTALSTATE:
		return true
	case MALFORMEDJSON:
		return true
	case METHODNOTALLOWED:
		return true
	case ORIGINNOTALLOWED:
		return true
	case OUTSIDESERVICEZONE:
		return true
	case OUTSTANDINGINVOICE:
		return true
	case PAYMENTINPROGRESS:
		return true
	case RATELIMITED:
		return true
	case RENTALCOMPLETED:
		return true
	case RESERVATIONEXPIRED:
		return true
	case RESOURCENOTFOUND:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case SOURCECAPACITYEXCEEDED:
		return true
	case SOURCENOTCARRIED:
		return true
	case TELEMETRYSTALE:
		return true
	case UNSUPPORTEDMEDIATYPE:
		return true
	case VALIDATIONFAILED:
		return true
	case VEHICLEINUSE:
		return true
	case VEHICLEUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for MarkServicedAction.
const (
	MarkServicedActionMarkServiced MarkServicedAction = "mark_serviced"
)

// Valid indicates whether the value is a known member of the MarkServicedAction enum.
func (e MarkServicedAction) Valid() bool {
	switch e {
	case MarkServicedActionMarkServiced:
		return true
	default:
		return false
	}
}

// Defines values for ParameterViolationLocation.
const (
	Header ParameterViolationLocation = "header"
	Path   ParameterViolationLocation = "path"
	Query  ParameterViolationLocation = "query"
)

// Valid indicates whether the value is a known member of the ParameterViolationLocation enum.
func (e ParameterViolationLocation) Valid() bool {
	switch e {
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for PointType.
const (
	PointTypePoint PointType = "Point"
)

// Valid indicates whether the value is a known member of the PointType enum.
func (e PointType) Valid() bool {
	switch e {
	case PointTypePoint:
		return true
	default:
		return false
	}
}

// Defines values for SetEnergyRemainingAction.
const (
	SetEnergyRemainingActionSetEnergyRemaining SetEnergyRemainingAction = "set_energy_remaining"
)

// Valid indicates whether the value is a known member of the SetEnergyRemainingAction enum.
func (e SetEnergyRemainingAction) Valid() bool {
	switch e {
	case SetEnergyRemainingActionSetEnergyRemaining:
		return true
	default:
		return false
	}
}

// Defines values for SetNextPaymentOutcomeAction.
const (
	SetNextPaymentOutcomeActionSetNextPaymentOutcome SetNextPaymentOutcomeAction = "set_next_payment_outcome"
)

// Valid indicates whether the value is a known member of the SetNextPaymentOutcomeAction enum.
func (e SetNextPaymentOutcomeAction) Valid() bool {
	switch e {
	case SetNextPaymentOutcomeActionSetNextPaymentOutcome:
		return true
	default:
		return false
	}
}

// Defines values for SetNextPaymentOutcomeOutcome.
const (
	Failed SetNextPaymentOutcomeOutcome = "failed"
	Paid   SetNextPaymentOutcomeOutcome = "paid"
)

// Valid indicates whether the value is a known member of the SetNextPaymentOutcomeOutcome enum.
func (e SetNextPaymentOutcomeOutcome) Valid() bool {
	switch e {
	case Failed:
		return true
	case Paid:
		return true
	default:
		return false
	}
}

// Defines values for SetPositionAction.
const (
	SetPositionActionSetPosition SetPositionAction = "set_position"
)

// Valid indicates whether the value is a known member of the SetPositionAction enum.
func (e SetPositionAction) Valid() bool {
	switch e {
	case SetPositionActionSetPosition:
		return true
	default:
		return false
	}
}

// Defines values for SetTelemetryStateAction.
const (
	SetTelemetryStateActionSetTelemetryState SetTelemetryStateAction = "set_telemetry_state"
)

// Valid indicates whether the value is a known member of the SetTelemetryStateAction enum.
func (e SetTelemetryStateAction) Valid() bool {
	switch e {
	case SetTelemetryStateActionSetTelemetryState:
		return true
	default:
		return false
	}
}

// Defines values for SetTelemetryStateTelemetryState.
const (
	Offline SetTelemetryStateTelemetryState = "offline"
	Online  SetTelemetryStateTelemetryState = "online"
)

// Valid indicates whether the value is a known member of the SetTelemetryStateTelemetryState enum.
func (e SetTelemetryStateTelemetryState) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	default:
		return false
	}
}

// Defines values for SourceKind.
const (
	Battery  SourceKind = "battery"
	Cng      SourceKind = "cng"
	Diesel   SourceKind = "diesel"
	Gasoline SourceKind = "gasoline"
	Lpg      SourceKind = "lpg"
)

// Valid indicates whether the value is a known member of the SourceKind enum.
func (e SourceKind) Valid() bool {
	switch e {
	case Battery:
		return true
	case Cng:
		return true
	case Diesel:
		return true
	case Gasoline:
		return true
	case Lpg:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	InsufficientEnergy   UnavailableReason = "insufficient_energy"
	OutsideServiceZone   UnavailableReason = "outside_service_zone"
	ServiceRequired      UnavailableReason = "service_required"
	TechnicalUnavailable UnavailableReason = "technical_unavailable"
	TelemetryStale       UnavailableReason = "telemetry_stale"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case InsufficientEnergy:
		return true
	case OutsideServiceZone:
		return true
	case ServiceRequired:
		return true
	case TechnicalUnavailable:
		return true
	case TelemetryStale:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Code    ErrorCode         `json:"code"`
	Details *ApiError_Details `json:"details,omitempty"`

	// Message Safe English message; clients translate known codes.
	Message string `json:"message"`

	// RequestId Example: example-request-1
	RequestId RequestId `json:"request_id"`
}

// ApiError_Details defines model for ApiError.Details.
type ApiError_Details struct {
	union json.RawMessage
}

// BodyViolation defines model for BodyViolation.
type BodyViolation struct {
	Code     string                `json:"code"`
	Location BodyViolationLocation `json:"location"`
	Message  string                `json:"message"`

	// Pointer JSON Pointer without the fragment marker.
	Pointer string `json:"pointer"`
}

// BodyViolationLocation defines model for BodyViolation.Location.
type BodyViolationLocation string

// CommandId Example: 11111111-1111-4111-8111-111111111111
type CommandId = string

// DailyLimitDetails The spent allowance and the moment it is restored, for the refusal that reports it.
type DailyLimitDetails struct {
	// DailyLimit The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
	DailyLimit DailyLimitState `json:"daily_limit"`
}

// DailyLimitState The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
type DailyLimitState struct {
	// Available Whether this account may still create a free reservation in the current service-timezone day. False means the day's allowance is spent; it is not a statement about the current moment or about a live rental, each of which the server checks again when a command arrives.
	Available bool `json:"available"`

	// ResetsAt The moment the allowance returns, being the start of the next day in the service timezone. It is the moment to display and never a Retry-After: an unfinished command answers with one second, which is not when the limit comes back.
	ResetsAt Timestamp `json:"resets_at"`
}

// DemoAction defines model for DemoAction.
type DemoAction struct {
	union json.RawMessage
}

// DemoResult defines model for DemoResult.
type DemoResult struct {
	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`
}

// EnergyDecimal Nonnegative canonical decimal, at most six fractional digits, no trailing fractional zeros or exponent.
//
// Example: 1200.125
type EnergyDecimal = string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// MarkServiced Example: {"action":"mark_serviced","action_id":"11111111-1111-4111-8111-111111111111","vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type MarkServiced struct {
	Action MarkServicedAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// MarkServicedAction defines model for MarkServiced.Action.
type MarkServicedAction string

// ParameterViolation defines model for ParameterViolation.
type ParameterViolation struct {
	Code      string                     `json:"code"`
	Location  ParameterViolationLocation `json:"location"`
	Message   string                     `json:"message"`
	Parameter string                     `json:"parameter"`
}

// ParameterViolationLocation defines model for ParameterViolation.Location.
type ParameterViolationLocation string

// Point defines model for Point.
type Point struct {
	// Coordinates WGS84 [longitude, latitude]. Latitude must be within -90..90.
	Coordinates Position  `json:"coordinates"`
	Type        PointType `json:"type"`
}

// PointType defines model for Point.Type.
type PointType string

// Position WGS84 [longitude, latitude]. Latitude must be within -90..90.
type Position = []float32

// RequestId Example: example-request-1
type RequestId = string

// ResourceId Example: 01994342-6ba7-7000-8000-000000000001
type ResourceId = string

// SetEnergyRemaining Example: {"action":"set_energy_remaining","action_id":"11111111-1111-4111-8111-111111111111","remaining":"0","source_kind":"battery","vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type SetEnergyRemaining struct {
	Action SetEnergyRemainingAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// Remaining Nonnegative canonical decimal, at most six fractional digits, no trailing fractional zeros or exponent.
	//
	// Example: 1200.125
	Remaining  EnergyDecimal `json:"remaining"`
	SourceKind SourceKind    `json:"source_kind"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// SetEnergyRemainingAction defines model for SetEnergyRemaining.Action.
type SetEnergyRemainingAction string

// SetNextPaymentOutcome Example: {"action":"set_next_payment_outcome","action_id":"11111111-1111-4111-8111-111111111111","outcome":"failed","rental_id":"01994342-6ba7-7000-8000-000000000001"}
type SetNextPaymentOutcome struct {
	Action SetNextPaymentOutcomeAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId                    `json:"action_id"`
	Outcome  SetNextPaymentOutcomeOutcome `json:"outcome"`

	// RentalId Example: 01994342-6ba7-7000-8000-000000000001
	RentalId ResourceId `json:"rental_id"`
}

// SetNextPaymentOutcomeAction defines model for SetNextPaymentOutcome.Action.
type SetNextPaymentOutcomeAction string

// SetNextPaymentOutcomeOutcome defines model for SetNextPaymentOutcome.Outcome.
type SetNextPaymentOutcomeOutcome string

// SetPosition Example: {"action":"set_position","action_id":"11111111-1111-4111-8111-111111111111","position":{"coordinates":[74.6,42.87],"type":"Point"},"vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type SetPosition struct {
	Action SetPositionAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`
	Position Point     `json:"position"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// SetPositionAction defines model for SetPosition.Action.
type SetPositionAction string

// SetTelemetryState Example: {"action":"set_telemetry_state","action_id":"11111111-1111-4111-8111-111111111111","telemetry_state":"offline","vehicle_id":"01994342-6ba7-7000-8000-000000000001"}
type SetTelemetryState struct {
	Action SetTelemetryStateAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId       CommandId                       `json:"action_id"`
	TelemetryState SetTelemetryStateTelemetryState `json:"telemetry_state"`

	// VehicleId Example: 01994342-6ba7-7000-8000-000000000001
	VehicleId ResourceId `json:"vehicle_id"`
}

// SetTelemetryStateAction defines model for SetTelemetryState.Action.
type SetTelemetryStateAction string

// SetTelemetryStateTelemetryState defines model for SetTelemetryState.TelemetryState.
type SetTelemetryStateTelemetryState string

// SourceKind defines model for SourceKind.
type SourceKind string

// TickRequest defines model for TickRequest.
type TickRequest struct {
	// TickId Example: 11111111-1111-4111-8111-111111111111
	TickId CommandId `json:"tick_id"`
}

// TickResult defines model for TickResult.
type TickResult struct {
	ChangedVehicleIds  []ResourceId `json:"changed_vehicle_ids"`
	CompletedRentalIds []ResourceId `json:"completed_rental_ids"`

	// ProcessedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ProcessedAt Timestamp `json:"processed_at"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`

	// TickId Example: 11111111-1111-4111-8111-111111111111
	TickId CommandId `json:"tick_id"`
}

// Timestamp UTC RFC3339, exactly six fractional digits; domain commands use database time.
//
// Example: 2026-09-12T07:15:30.123456Z
type Timestamp = string

// UnavailableDetails defines model for UnavailableDetails.
type UnavailableDetails struct {
	UnavailableReasons []UnavailableReason `json:"unavailable_reasons"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// ValidationDetails defines model for ValidationDetails.
type ValidationDetails struct {
	Violations []Violation `json:"violations"`
}

// Violation defines model for Violation.
type Violation struct {
	union json.RawMessage
}

// ApplyDemoActionParams defines parameters for ApplyDemoAction.
type ApplyDemoActionParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// SimulationTickParams defines parameters for SimulationTick.
type SimulationTickParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ApplyDemoActionJSONRequestBody defines body for ApplyDemoAction for application/json ContentType.
type ApplyDemoActionJSONRequestBody = DemoAction

// SimulationTickJSONRequestBody defines body for SimulationTick for application/json ContentType.
type SimulationTickJSONRequestBody = TickRequest

// AsValidationDetails returns the union data inside the ApiError_Details as a ValidationDetails
func (t ApiError_Details) AsValidationDetails() (ValidationDetails, error) {
	var body ValidationDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationDetails overwrites any union data inside the ApiError_Details as the provided ValidationDetails
func (t *ApiError_Details) FromValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationDetails performs a merge with any union data inside the ApiError_Details, using the provided ValidationDetails
func (t *ApiError_Details) MergeValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnavailableDetails returns the union data inside the ApiError_Details as a UnavailableDetails
func (t ApiError_Details) AsUnavailableDetails() (UnavailableDetails, error) {
	var body UnavailableDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnavailableDetails overwrites any union data inside the ApiError_Details as the provided UnavailableDetails
func (t *ApiError_Details) FromUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnavailableDetails performs a merge with any union data inside the ApiError_Details, using the provided UnavailableDetails
func (t *ApiError_Details) MergeUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDailyLimitDetails returns the union data inside the ApiError_Details as a DailyLimitDetails
func (t ApiError_Details) AsDailyLimitDetails() (DailyLimitDetails, error) {
	var body DailyLimitDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDailyLimitDetails overwrites any union data inside the ApiError_Details as the provided DailyLimitDetails
func (t *ApiError_Details) FromDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDailyLimitDetails performs a merge with any union data inside the ApiError_Details, using the provided DailyLimitDetails
func (t *ApiError_Details) MergeDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApiError_Details) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiError_Details) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSetTelemetryState returns the union data inside the DemoAction as a SetTelemetryState
func (t DemoAction) AsSetTelemetryState() (SetTelemetryState, error) {
	var body SetTelemetryState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetTelemetryState overwrites any union data inside the DemoAction as the provided SetTelemetryState
func (t *DemoAction) FromSetTelemetryState(v SetTelemetryState) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_telemetry_state"}`))
	t.union = b
	return err
}

// MergeSetTelemetryState performs a merge with any union data inside the DemoAction, using the provided SetTelemetryState
func (t *DemoAction) MergeSetTelemetryState(v SetTelemetryState) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_telemetry_state"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetPosition returns the union data inside the DemoAction as a SetPosition
func (t DemoAction) AsSetPosition() (SetPosition, error) {
	var body SetPosition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetPosition overwrites any union data inside the DemoAction as the provided SetPosition
func (t *DemoAction) FromSetPosition(v SetPosition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_position"}`))
	t.union = b
	return err
}

// MergeSetPosition performs a merge with any union data inside the DemoAction, using the provided SetPosition
func (t *DemoAction) MergeSetPosition(v SetPosition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_position"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetEnergyRemaining returns the union data inside the DemoAction as a SetEnergyRemaining
func (t DemoAction) AsSetEnergyRemaining() (SetEnergyRemaining, error) {
	var body SetEnergyRemaining
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetEnergyRemaining overwrites any union data inside the DemoAction as the provided SetEnergyRemaining
func (t *DemoAction) FromSetEnergyRemaining(v SetEnergyRemaining) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_energy_remaining"}`))
	t.union = b
	return err
}

// MergeSetEnergyRemaining performs a merge with any union data inside the DemoAction, using the provided SetEnergyRemaining
func (t *DemoAction) MergeSetEnergyRemaining(v SetEnergyRemaining) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_energy_remaining"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMarkServiced returns the union data inside the DemoAction as a MarkServiced
func (t DemoAction) AsMarkServiced() (MarkServiced, error) {
	var body MarkServiced
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMarkServiced overwrites any union data inside the DemoAction as the provided MarkServiced
func (t *DemoAction) FromMarkServiced(v MarkServiced) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"mark_serviced"}`))
	t.union = b
	return err
}

// MergeMarkServiced performs a merge with any union data inside the DemoAction, using the provided MarkServiced
func (t *DemoAction) MergeMarkServiced(v MarkServiced) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"mark_serviced"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetNextPaymentOutcome returns the union data inside the DemoAction as a SetNextPaymentOutcome
func (t DemoAction) AsSetNextPaymentOutcome() (SetNextPaymentOutcome, error) {
	var body SetNextPaymentOutcome
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetNextPaymentOutcome overwrites any union data inside the DemoAction as the provided SetNextPaymentOutcome
func (t *DemoAction) FromSetNextPaymentOutcome(v SetNextPaymentOutcome) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_next_payment_outcome"}`))
	t.union = b
	return err
}

// MergeSetNextPaymentOutcome performs a merge with any union data inside the DemoAction, using the provided SetNextPaymentOutcome
func (t *DemoAction) MergeSetNextPaymentOutcome(v SetNextPaymentOutcome) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"action":"set_next_payment_outcome"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DemoAction) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"action"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DemoAction) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "mark_serviced":
		return t.AsMarkServiced()
	case "set_energy_remaining":
		return t.AsSetEnergyRemaining()
	case "set_next_payment_outcome":
		return t.AsSetNextPaymentOutcome()
	case "set_position":
		return t.AsSetPosition()
	case "set_telemetry_state":
		return t.AsSetTelemetryState()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DemoAction) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DemoAction) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBodyViolation returns the union data inside the Violation as a BodyViolation
func (t Violation) AsBodyViolation() (BodyViolation, error) {
	var body BodyViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBodyViolation overwrites any union data inside the Violation as the provided BodyViolation
func (t *Violation) FromBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBodyViolation performs a merge with any union data inside the Violation, using the provided BodyViolation
func (t *Violation) MergeBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterViolation returns the union data inside the Violation as a ParameterViolation
func (t Violation) AsParameterViolation() (ParameterViolation, error) {
	var body ParameterViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterViolation overwrites any union data inside the Violation as the provided ParameterViolation
func (t *Violation) FromParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterViolation performs a merge with any union data inside the Violation, using the provided ParameterViolation
func (t *Violation) MergeParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Violation) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Violation) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ApplyDemoAction apply Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyDemoAction(w http.ResponseWriter, r *http.Request, params ApplyDemoActionParams)
	// SimulationTick simulation Tick
	// (POST /internal/v1/simulation/tick)
	SimulationTick(w http.ResponseWriter, r *http.Request, params SimulationTickParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ApplyDemoAction apply Demo Action
// (POST /internal/v1/demo/actions)
func (_ Unimplemented) ApplyDemoAction(w http.ResponseWriter, r *http.Request, params ApplyDemoActionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SimulationTick simulation Tick
// (POST /internal/v1/simulation/tick)
func (_ Unimplemented) SimulationTick(w http.ResponseWriter, r *http.Request, params SimulationTickParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApplyDemoAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyDemoAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyDemoActionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyDemoAction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SimulationTick operation middleware
func (siw *ServerInterfaceWrapper) SimulationTick(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SimulationTickParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SimulationTick(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/demo/actions", wrapper.ApplyDemoAction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/simulation/tick", wrapper.SimulationTick)
	})

	return r
}

type ApplyDemoActionRequestObject struct {
	Params ApplyDemoActionParams
	Body   *ApplyDemoActionJSONRequestBody
}

type ApplyDemoActionResponseObject interface {
	VisitApplyDemoActionResponse(w http.ResponseWriter) error
}

type ApplyDemoAction200ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type ApplyDemoAction200JSONResponse struct {
	Body    DemoResult
	Headers ApplyDemoAction200ResponseHeaders
}

func (response ApplyDemoAction200JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction400JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction400ResponseHeaders
}

func (response ApplyDemoAction400JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction401JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction401ResponseHeaders
}

func (response ApplyDemoAction401JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction404ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction404JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction404ResponseHeaders
}

func (response ApplyDemoAction404JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction409ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	RetryAfter          *int
	XRequestID          *RequestId
}

type ApplyDemoAction409JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction409ResponseHeaders
}

func (response ApplyDemoAction409JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction413JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction413ResponseHeaders
}

func (response ApplyDemoAction413JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction415JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction415ResponseHeaders
}

func (response ApplyDemoAction415JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction422JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction422ResponseHeaders
}

func (response ApplyDemoAction422JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction500JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction500ResponseHeaders
}

func (response ApplyDemoAction500JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDemoAction503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyDemoAction503JSONResponse struct {
	Body    ApiError
	Headers ApplyDemoAction503ResponseHeaders
}

func (response ApplyDemoAction503JSONResponse) VisitApplyDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTickRequestObject struct {
	Params SimulationTickParams
	Body   *SimulationTickJSONRequestBody
}

type SimulationTickResponseObject interface {
	VisitSimulationTickResponse(w http.ResponseWriter) error
}

type SimulationTick200ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type SimulationTick200JSONResponse struct {
	Body    TickResult
	Headers SimulationTick200ResponseHeaders
}

func (response SimulationTick200JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick400JSONResponse struct {
	Body    ApiError
	Headers SimulationTick400ResponseHeaders
}

func (response SimulationTick400JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick401JSONResponse struct {
	Body    ApiError
	Headers SimulationTick401ResponseHeaders
}

func (response SimulationTick401JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick409ResponseHeaders struct {
	CacheControl *string
	RetryAfter   *int
	XRequestID   *RequestId
}

type SimulationTick409JSONResponse struct {
	Body    ApiError
	Headers SimulationTick409ResponseHeaders
}

func (response SimulationTick409JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick413JSONResponse struct {
	Body    ApiError
	Headers SimulationTick413ResponseHeaders
}

func (response SimulationTick413JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick415JSONResponse struct {
	Body    ApiError
	Headers SimulationTick415ResponseHeaders
}

func (response SimulationTick415JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick422JSONResponse struct {
	Body    ApiError
	Headers SimulationTick422ResponseHeaders
}

func (response SimulationTick422JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick500JSONResponse struct {
	Body    ApiError
	Headers SimulationTick500ResponseHeaders
}

func (response SimulationTick500JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SimulationTick503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type SimulationTick503JSONResponse struct {
	Body    ApiError
	Headers SimulationTick503ResponseHeaders
}

func (response SimulationTick503JSONResponse) VisitSimulationTickResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ApplyDemoAction apply Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyDemoAction(ctx context.Context, request ApplyDemoActionRequestObject) (ApplyDemoActionResponseObject, error)
	// SimulationTick simulation Tick
	// (POST /internal/v1/simulation/tick)
	SimulationTick(ctx context.Context, request SimulationTickRequestObject) (SimulationTickResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ApplyDemoAction operation middleware
func (sh *strictHandler) ApplyDemoAction(w http.ResponseWriter, r *http.Request, params ApplyDemoActionParams) {
	var request ApplyDemoActionRequestObject

	request.Params = params

	var body ApplyDemoActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyDemoAction(ctx, request.(ApplyDemoActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyDemoAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyDemoActionResponseObject); ok {
		if err := validResponse.VisitApplyDemoActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SimulationTick operation middleware
func (sh *strictHandler) SimulationTick(w http.ResponseWriter, r *http.Request, params SimulationTickParams) {
	var request SimulationTickRequestObject

	request.Params = params

	var body SimulationTickJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SimulationTick(ctx, request.(SimulationTickRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SimulationTick")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SimulationTickResponseObject); ok {
		if err := validResponse.VisitSimulationTickResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7cyI5kv8qirqNuN29Kowf/TD9xwUD1d3cYPAB7h2P21chVwnQukqqkYTbTB/ffSOlelMY8LonmAj3",
	"H22o0uOXD6VSmSm+Wz6PYs4IU9JqfbfmBAdE6I8d7M9JhzMleAjfAyJ9QWNFObNa1ojImDNJJIoWUiHG",
	"FbojyIc+QcOyLenPSYShH2GLyGrdWIw7UnFBrFvbUsuYWC1LKkHZzFqtbKsXkCjmijB/OSJxiJckWJ9U",
	"iQVBnIVLNOUCYSR0S8SnSM0JkviBBIgLOqMMh0gqrBYSYRagOx4sy6ASAHechwQzjWBEflsQqXo18/YC",
	"whSdUiLMXFSiz5PJJcJKkShWDWQgSySIwpRpNBkOmBwJM7hHK8z5iyBTq2X9x1EuhiPzVh7lgAw8JZbt",
	"qSKiThhKLBGGl4gzgiTxOQsMkxiizJmGdDZXyOdRhFm9fI5zsVCmyIwIa7VapQ21RrRj6grBNQAcBBRm",
	"x+Gl4DERihJptaY4lMS24sIj0LCAbKNVj9uBhivbCoCLoe7LGRlOrdbN072/4JAGGOB0k64r++keVww/",
	"YBriu5Ds2qWLabjs04iqrMftyrYiIiWekXWhjPGUIJfNQirnKGn1AfkhhVGREpjJECuC7hn/xhAwSTas",
	"TAbp0rCtXHX2UxjoRwUsoxsjghxradBc7vzun8RXMOdPPFh+oTzEhpZniXuNkJD72XipUYDFUWMQSmxd",
	"exdz0NCadfA/4+EAXZq36BtVc75QejFOBZ5FhCkUYXFPBPA5hsUroNf//fWo8fe//fdfrDq7VORiRkAO",
	"wa6yto6bHbPsjGUhjziKQ2hwnPxz9H9n8N/79Gv6z7KtKRcRVlbLWixoUAZ+03TOsTO9/f5+5WSfz1bO",
	"WfbldOXcvD/Hd7elJ+nn45PVOtW29ejMuLPG9XX936YXZeFMwETHIAQchvwbZj7RxhnkE3EtHaoQBSOq",
	"94nA1gYMXgsyXUgcIjXHCow+F0oiqrQYS7oXAEYvBJDbFktOzlhhRdaEXRyqTqjV/vszQ89QYAafoqkg",
	"QK0k4kFrmrSRIDhA3+ZEzcG4C73Tws7HFA6BW/5CwJcG6mnmBURQ2AangkdmV9S8LA2abpjY9/mCKRsl",
	"Wxa0oD5Bikbkd86IjQTW06o5ZvmI+E6SBC9Op08ArUskM7Prq/UfCVF6P02woAgvkVQ0DJEvCJhHvMaU",
	"FG46dQLbSWGjAC8b6COwHUUEM6lbB3j5n7LAbSqNNn5ItM7wFZwGonUR36XGI50nUVIukncYhfSBJJTb",
	"iGB/Djz5Nqf+POMnEcifE/9eIjwD1+DbnDBgmzEJCAsQV9HwZy4JqKMkSnpY6zIOwx12wgmNiFQ4iq3V",
	"bZ3OJTRoMWasEEQtBOjaHaFslmgNFirVE0YeFfBvk56kuldYyYqjgErtnQGZjAAjMNKOiqO9mBa4Jgs2",
	"pYzKOQlyjjD5jQipzXfBmbETviaS0myE+fQChc5Eojvs3zfWFnKugUWO1i5pEvG2n25RAQXmRZRhZVye",
	"CMcx2EL9Udx7CRuCTbK4wOJ+nLaxLUmURxgRs6UnSIQp02PVdx0T5eqmo6ylGQBE4cV4CUz2+EIB4U8M",
	"MiCP6tK0HiaNzTgxlzRRi019L9MmpociIYlAfJ409m5jx0naMjGsmUlYDrBGiw2PV/aO7l3dmFt7ZPB3",
	"aFvl9bYuJcnuMH6NGFa3icKNiFyEak8fy3BwB5cwdz3Aldf2yINla7V2tiPV5ZRNXR6wbkEZvnaJTyNc",
	"c4YccMbIDCuwoj5mnFEfhygwzW2EweRKhSR9BAfON7xBAZ1RJW3EODjRNASTVXj9OxFcgpEmj4YosK0F",
	"p+uk2Wwcn7ypeIDN/785ds61l3T797/99evXhv74vWm/Wek3tf6hbeXnloJTe9HufxyOLtyuBw6pZVu9",
	"wZd2v9f1PrvtrjsqPOhcjcZDePDTsHvtTYZDr98efXIt27oajK8uL4ejidv1Ltxur+1Nri/hhe7YnvSG",
	"A+9ju9d3u5ZtXbiTz8OuNxhOvHa/P/yHfti+mnx2B5NexzQeuf971Ru53eLsI7cLLdr9sWVb7kW71/fa",
	"/ZHb7l57I/dTbzxxTYfhqPepN6iM3xmPPnrJUHrQiTsatPveE/N23YvL4cQddK69n93rp14Vxi286QwH",
	"H/u9zqTyuDfwLkfDTyN3DHSM3PHwatRxNdyPw6sBjPLF/dzr9F3vatD+0u712z/13cLT3sC7GsODQs9O",
	"ezTqud38Yad92e70Jtee+0vHdbuGx51J74vrjdzBpN333F964wlA6LZ7/Wuv37voTbyR2+58Nly8mown",
	"7UG3N/gE9A17HdfAdUdfDK/cXy4TfiQjdoYXl313UpJa8mo8aU/cZNRe1/VglF7H9X4dDuDxxO27F+5k",
	"dA0NNbGX7esLdzCpcKvr9ntf3FGJt6P2xDXojaD7w87P3vBq4g0/euPrQQeeDQedq9FIs3+kp3F/+dy+",
	"GpseKZYytzMNcUej4aj21FcyrNtMYraoU3totSobs100lLuetx7InPohMX2ax+fnZ6dnJ87bO/zOedds",
	"Np338F8z/3dc2OFK5rloEsq46kh/nkkvgt0WHJB8IXxSEx0omnTzucyGOtN+iQWOiCLiDwkT/LYgYmlM",
	"9tyykyjl/nGDFHPN2yeO+lmvnQ77OvywNy+4CMDRJHKbGAtuTTJ3ziUz9e22MIZ+a5cmrSckmWn94PZp",
	"/P4M3YSczahaBMRGoAHw6baB+slHExe+I9qRpww5581G47wJuzFVJJLGjX6kEWA/ft+0rYgy883RXxNA",
	"bBHdEaFFix97pueJbpx/SZpiIfBSxy9y2hwuQFVaVobWScFa1aBv7iUkn5wkTOaAXYjwY5+wmZpbreOT",
	"9xpB9r0clWk7v2Ln96Zz3vCc2/+q9RsKq7E08U725lkxoXc/IiZU4zs/x2rXHo2eZbyLJ6umZVuGy949",
	"ZTDInWbT8kcZ+VoyXs7WiyKPn+pVdrtXFS5sOa3opj9T9sdtL2V8tlXHu9ws1R+nnqt1tefpZ2lefhif",
	"YhoSQwhEhl5ex2pBv5ye8Zyn6awx1nJKKLutzVJktL6souQD58g26EVxx3qWNsR5yOMZGhAXpi/t6Dfv",
	"zhpv7bOTxvt3OXKzWa9+oCnK8LycahRJfNpLqSHuBxqQGlJLmlEJHz1XP6oxsGepyXogjU+nIWXkR25L",
	"1UlfTiXWyMkn5iwhKyWwbtY/SEM2M6CgKPneV0xRZk7DDEueUBRQIklo2VYYg6fib9joJ9S/T1zMPY8E",
	"ivr3+4mi6uUnA9QRamA9I+7ozzGbkcDLWasfZw79ruKruOwrW5ehhESRwMsM/ksNHQvuEylJkGRSdox7",
	"Pjdear+c7MoQKpTYtdLYwMl6LUgxr53wriYdNPrYOT09PbcRecS+Cpf1cdgPKODgrqX5G4kWEpJtCt9h",
	"aVJE5QDsSfPkrdM8d45PJs13reM3rVOIx56evXn7a/FgE8DZLSU7P918/RrAYQb+nKR/JuZPq/Tn69cG",
	"fHi7+nX300xNUch+y2ORD+AJgiVnu+twYfKR7mqtiqfc47VT7oLR3xYkea3EglS1qA5NnR6sz1ywfpTJ",
	"xXRKfUpYeripWlOdWeMLJWlA0hiXB3nBRH/ha4YL+vpzHen3CgBrred6Wc9+4nhIQ1O7SyGPZj3J/Sqr",
	"CzPVcbgUI9st51WuwNmWY6qJxq1uV9qE+QtB1XIMDQ1XIOk04fekJrATkIh7vin585RukxSA6cw0wUJH",
	"wRL65kppczem0SKEJOmGUWX6ftchAThlU74+1GWIGSMBuvhyiTRO7KsPkAmKBQ8W2jKhOWZBSIRsIF0O",
	"JLJCRTBMuqjRSaoaUVqS2EBDKCqEoF+IDE+h5oQIwnwiERZJtpwEDdRjYItwiBhR37i41/WIHxB5TB7H",
	"gj8u05Q6OmueNdBPPKDJMDpdTQLIj5+8PTk+O0N3S0VkA/2kOYE0h0xTSSDyqAiKoYYAx/iOhlQt7SSZ",
	"7nN+D6NygSATY+s8expz0yUHJEB3ZMoFQTEWMs3sJ+Y6xsuQ46CBLqjU76A7ZQ+w5FIUS0rCAFFd/Aic",
	"OWseo21pnga6YnIRx1wAmRFRcx4Yes6ab9B6osrk+dvA3Q9owXQx3BGApjOGRLKvmyrOBaOwh8CplwRF",
	"iUNUOJ3jDK3nfxpIp+mMBqRFjDb6xUlcM6fX1RPk6jBeMoUfj0ycGRHT20zQ/KDZCSU2mj3FlycnDZQb",
	"LZTUMSKwpUSLEochoiwgMWHA1XAJbYivwASi3IhAoQW8EBASlYr6uoj0SEfBj4DaFBmgTkrRjrI4NdIh",
	"T11SQpXecztYjOcYzCqiqfomqxJwwiiw9FH7sqf9ZiHNcjtuNBtNHRKICcMxtVrWaaPZOE0i8dqcHKUj",
	"Hj0cH8EoR8ZD0C9jLtX6Kh4T5SjuPOAQynljYI2mGsST1MzAzq9xJSW+eX2v0H6rqW1Nvf4PKHGFUrUG",
	"4zANqa9kA0G0CCXREpREEHT1j89jsxKhyiSt4jGLaxbyOxw2UKIgpoZXl6YZmw/MzYBDDNdqx3G4LBSQ",
	"FPIGUht7CpQbsVm2xUwlRFEFn1UXfJuVcsKGYSIPTJEkAxHHITV5jKN/pvu6ccRkTRXLd0tL5ADyaatN",
	"1TJ1EP8UwePVU+U7m6g6sODkqlo6tAn3nyWMttpQ2bSJrkMM/+Ql+lsLXnPjtCr7r/rwYFuZpwQjnTSb",
	"u1uTSknSrqwona+fPBjuRWQS2dBEVjaehQ/n5+kizNzCRpZOzi+9OIVbL3WTJe2PSjdkyndYnOIllqfG",
	"qLv3srLLG8OWIYr7wcq2zvaRnCa6Up5U1H+Tpa+2KKTZ0wwq8vkiDLJ7QGkMonzVoC6xCpArBVM1ACot",
	"XhbAztqVXYCp0a0yi2y0hviltOy5qgFRD+2sOsBTsKfrYq2AvtXqdLy3Om2pBKtVsC19DlLiWzEfpMy3",
	"oDZCP9tT6Ounrjox17Q6QMHWojxAUdbgNMI733fF1tVY1q3SunYvvRlsquzcgqfY9KUhbawArcG0se0P",
	"AlWsVd0Mp9jqpYFUqmhrQFRaHKItr9FsG23QLxuVCbLROpdt9IQiHKDDWbiZs90qZTeRX3hr2rfU+9+s",
	"39bG8vh0T2NZKdWvUfdKiwNU9zWEB7i7VTAaYb3ZU1gbrlHUCG1DywMU3kakByjEDVi1ME9O9hTm+tWX",
	"ur1mrVHpBwWKOcGbrFMhPZmXn5vL6VUFgGZITwoB4chkTwo3wlvWEYQRw8qvAxyK8tSx5wD1Zh0mcPPN",
	"M0IbpTsnT508TYtDPmemCA/5VJnc7dHC2ndnrbs2VOfS1jQ7QLHVwzxA2dUBLRUPaEtZKBu4uYW8k1xE",
	"ERZLq6XlukRdnUFMs1+PDlhPJ/kpBpPrhqdZClergWN+pMdqWTRP7WqUpbRinqs8gtKozZnFtuIRpKrh",
	"dxV8basRZ5VyJF3yZCMcPJifoAhLuVAAlOSbId+IYD7U69ooq71Kr7ib7CSEmvXv/xCssqx/6fd/TJvs",
	"50jIoxIYRVzPBtdUdeoKcp8NNMYRQb0kJ44Z1z+PUJfS5MnvyOQE7ZOrHGfkQiHgoacqS9WQu6UWdl6/",
	"xfrMH5EUqa2XvNkttXO7qSjy5rZa07ilqG73PIv9gzn9mph5Tcy8JmZeEzOviZlnJ2ZeY/t/7uDxCyrf",
	"nzBm+xpyfQ25voZcX0OuryHX15Dra8j1NeT6GnJ9IuRavVhVjbsWwpZJIO/fi7quVv8aAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
