// Package mailstubapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package mailstubapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BodyViolationLocation.
const (
	Body BodyViolationLocation = "body"
)

// Valid indicates whether the value is a known member of the BodyViolationLocation enum.
func (e BodyViolationLocation) Valid() bool {
	switch e {
	case Body:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ACTIVERENTALEXISTS             ErrorCode = "ACTIVE_RENTAL_EXISTS"
	AUTHENTICATIONREQUIRED         ErrorCode = "AUTHENTICATION_REQUIRED"
	BODYTOOLARGE                   ErrorCode = "BODY_TOO_LARGE"
	CLOCKOUTOFSYNC                 ErrorCode = "CLOCK_OUT_OF_SYNC"
	CONCURRENCYRETRYEXHAUSTED      ErrorCode = "CONCURRENCY_RETRY_EXHAUSTED"
	CSRFINVALID                    ErrorCode = "CSRF_INVALID"
	DAILYLIMITREACHED              ErrorCode = "DAILY_LIMIT_REACHED"
	DELIVERYCONFLICT               ErrorCode = "DELIVERY_CONFLICT"
	EMAILALREADYREGISTERED         ErrorCode = "EMAIL_ALREADY_REGISTERED"
	IDEMPOTENCYCONFLICT            ErrorCode = "IDEMPOTENCY_CONFLICT"
	IDEMPOTENCYINPROGRESS          ErrorCode = "IDEMPOTENCY_IN_PROGRESS"
	IDEMPOTENCYKEYINVALID          ErrorCode = "IDEMPOTENCY_KEY_INVALID"
	IDEMPOTENCYKEYREQUIRED         ErrorCode = "IDEMPOTENCY_KEY_REQUIRED"
	INTERNALAUTHENTICATIONREQUIRED ErrorCode = "INTERNAL_AUTHENTICATION_REQUIRED"
	INTERNALERROR                  ErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS             ErrorCode = "INVALID_CREDENTIALS"
	INVALIDCURSOR                  ErrorCode = "INVALID_CURSOR"
	INVALIDHEADER                  ErrorCode = "INVALID_HEADER"
	INVALIDRENTALSTATE             ErrorCode = "INVALID_RENTAL_STATE"
	MALFORMEDJSON                  ErrorCode = "MALFORMED_JSON"
	METHODNOTALLOWED               ErrorCode = "METHOD_NOT_ALLOWED"
	ORIGINNOTALLOWED               ErrorCode = "ORIGIN_NOT_ALLOWED"
	OUTSIDESERVICEZONE             ErrorCode = "OUTSIDE_SERVICE_ZONE"
	OUTSTANDINGINVOICE             ErrorCode = "OUTSTANDING_INVOICE"
	PAYMENTINPROGRESS              ErrorCode = "PAYMENT_IN_PROGRESS"
	RATELIMITED                    ErrorCode = "RATE_LIMITED"
	RENTALCOMPLETED                ErrorCode = "RENTAL_COMPLETED"
	RESERVATIONEXPIRED             ErrorCode = "RESERVATION_EXPIRED"
	RESOURCENOTFOUND               ErrorCode = "RESOURCE_NOT_FOUND"
	SERVICEUNAVAILABLE             ErrorCode = "SERVICE_UNAVAILABLE"
	SOURCECAPACITYEXCEEDED         ErrorCode = "SOURCE_CAPACITY_EXCEEDED"
	SOURCENOTCARRIED               ErrorCode = "SOURCE_NOT_CARRIED"
	TELEMETRYSTALE                 ErrorCode = "TELEMETRY_STALE"
	UNSUPPORTEDMEDIATYPE           ErrorCode = "UNSUPPORTED_MEDIA_TYPE"
	VALIDATIONFAILED               ErrorCode = "VALIDATION_FAILED"
	VEHICLEINUSE                   ErrorCode = "VEHICLE_IN_USE"
	VEHICLEUNAVAILABLE             ErrorCode = "VEHICLE_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ACTIVERENTALEXISTS:
		return true
	case AUTHENTICATIONREQUIRED:
		return true
	case BODYTOOLARGE:
		return true
	case CLOCKOUTOFSYNC:
		return true
	case CONCURRENCYRETRYEXHAUSTED:
		return true
	case CSRFINVALID:
		return true
	case DAILYLIMITREACHED:
		return true
	case DELIVERYCONFLICT:
		return true
	case EMAILALREADYREGISTERED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case IDEMPOTENCYINPROGRESS:
		return true
	case IDEMPOTENCYKEYINVALID:
		return true
	case IDEMPOTENCYKEYREQUIRED:
		return true
	case INTERNALAUTHENTICATIONREQUIRED:
		return true
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDCURSOR:
		return true
	case INVALIDHEADER:
		return true
	case INVALIDRENTALSTATE:
		return true
	case MALFORMEDJSON:
		return true
	case METHODNOTALLOWED:
		return true
	case ORIGINNOTALLOWED:
		return true
	case OUTSIDESERVICEZONE:
		return true
	case OUTSTANDINGINVOICE:
		return true
	case PAYMENTINPROGRESS:
		return true
	case RATELIMITED:
		return true
	case RENTALCOMPLETED:
		return true
	case RESERVATIONEXPIRED:
		return true
	case RESOURCENOTFOUND:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case SOURCECAPACITYEXCEEDED:
		return true
	case SOURCENOTCARRIED:
		return true
	case TELEMETRYSTALE:
		return true
	case UNSUPPORTEDMEDIATYPE:
		return true
	case VALIDATIONFAILED:
		return true
	case VEHICLEINUSE:
		return true
	case VEHICLEUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for MailDemoActionAction.
const (
	DropNextResponseAfterAccept MailDemoActionAction = "drop_next_response_after_accept"
)

// Valid indicates whether the value is a known member of the MailDemoActionAction enum.
func (e MailDemoActionAction) Valid() bool {
	switch e {
	case DropNextResponseAfterAccept:
		return true
	default:
		return false
	}
}

// Defines values for ParameterViolationLocation.
const (
	Header ParameterViolationLocation = "header"
	Path   ParameterViolationLocation = "path"
	Query  ParameterViolationLocation = "query"
)

// Valid indicates whether the value is a known member of the ParameterViolationLocation enum.
func (e ParameterViolationLocation) Valid() bool {
	switch e {
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	InsufficientEnergy   UnavailableReason = "insufficient_energy"
	OutsideServiceZone   UnavailableReason = "outside_service_zone"
	ServiceRequired      UnavailableReason = "service_required"
	TechnicalUnavailable UnavailableReason = "technical_unavailable"
	TelemetryStale       UnavailableReason = "telemetry_stale"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case InsufficientEnergy:
		return true
	case OutsideServiceZone:
		return true
	case ServiceRequired:
		return true
	case TechnicalUnavailable:
		return true
	case TelemetryStale:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Code    ErrorCode         `json:"code"`
	Details *ApiError_Details `json:"details,omitempty"`

	// Message Safe English message; clients translate known codes.
	Message string `json:"message"`

	// RequestId Example: example-request-1
	RequestId RequestId `json:"request_id"`
}

// ApiError_Details defines model for ApiError.Details.
type ApiError_Details struct {
	union json.RawMessage
}

// BodyViolation defines model for BodyViolation.
type BodyViolation struct {
	Code     string                `json:"code"`
	Location BodyViolationLocation `json:"location"`
	Message  string                `json:"message"`

	// Pointer JSON Pointer without the fragment marker.
	Pointer string `json:"pointer"`
}

// BodyViolationLocation defines model for BodyViolation.Location.
type BodyViolationLocation string

// CommandId Example: 11111111-1111-4111-8111-111111111111
type CommandId = string

// Cursor Versioned Base64URL cursor signed with HMAC-SHA256 over endpoint, position, user scope and query parameters. Forward only; no TTL; rotation invalidates cursors. Any syntax, signature or scope failure returns INVALID_CURSOR.
//
// Example: eyJ2IjoxfQ
type Cursor = string

// DailyLimitDetails The spent allowance and the moment it is restored, for the refusal that reports it.
type DailyLimitDetails struct {
	// DailyLimit The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
	DailyLimit DailyLimitState `json:"daily_limit"`
}

// DailyLimitState The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
type DailyLimitState struct {
	// Available Whether this account may still create a free reservation in the current service-timezone day. False means the day's allowance is spent; it is not a statement about the current moment or about a live rental, each of which the server checks again when a command arrives.
	Available bool `json:"available"`

	// ResetsAt The moment the allowance returns, being the start of the next day in the service timezone. It is the moment to display and never a Retry-After: an unfinished command answers with one second, which is not when the limit comes back.
	ResetsAt Timestamp `json:"resets_at"`
}

// DeliveryReceipt defines model for DeliveryReceipt.
type DeliveryReceipt struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id ResourceId `json:"id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// MailDemoAction defines model for MailDemoAction.
type MailDemoAction struct {
	Action MailDemoActionAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`
}

// MailDemoActionAction defines model for MailDemoAction.Action.
type MailDemoActionAction string

// MailDemoResult defines model for MailDemoResult.
type MailDemoResult struct {
	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`
}

// Message defines model for Message.
type Message struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id      ResourceId          `json:"id"`
	Subject string              `json:"subject"`
	Text    string              `json:"text"`
	To      openapi_types.Email `json:"to"`
}

// MessageCollection defines model for MessageCollection.
type MessageCollection struct {
	Items []MessageSummary `json:"items"`

	// NextCursor Required; null on the last or empty page. Signed cursor; see Cursor.
	NextCursor *string `json:"next_cursor"`
}

// MessageRequest defines model for MessageRequest.
type MessageRequest struct {
	Subject string `json:"subject"`

	// Text Plain text only; never interpreted as HTML. The total UTF-8 request body is also limited to 262144 bytes.
	Text string              `json:"text"`
	To   openapi_types.Email `json:"to"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id      ResourceId          `json:"id"`
	Subject string              `json:"subject"`
	To      openapi_types.Email `json:"to"`
}

// ParameterViolation defines model for ParameterViolation.
type ParameterViolation struct {
	Code      string                     `json:"code"`
	Location  ParameterViolationLocation `json:"location"`
	Message   string                     `json:"message"`
	Parameter string                     `json:"parameter"`
}

// ParameterViolationLocation defines model for ParameterViolation.Location.
type ParameterViolationLocation string

// RequestId Example: example-request-1
type RequestId = string

// ResourceId Example: 01994342-6ba7-7000-8000-000000000001
type ResourceId = string

// Timestamp UTC RFC3339, exactly six fractional digits; domain commands use database time.
//
// Example: 2026-09-12T07:15:30.123456Z
type Timestamp = string

// UnavailableDetails defines model for UnavailableDetails.
type UnavailableDetails struct {
	UnavailableReasons []UnavailableReason `json:"unavailable_reasons"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// ValidationDetails defines model for ValidationDetails.
type ValidationDetails struct {
	Violations []Violation `json:"violations"`
}

// Violation defines model for Violation.
type Violation struct {
	union json.RawMessage
}

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	Limit      *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor     *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetMessageParams defines parameters for GetMessage.
type GetMessageParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ApplyMailDemoActionParams defines parameters for ApplyMailDemoAction.
type ApplyMailDemoActionParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// DeliverMessageParams defines parameters for DeliverMessage.
type DeliverMessageParams struct {
	XRequestID  *RequestId `json:"X-Request-ID,omitempty"`
	DeliveryKey string     `json:"Delivery-Key"`
}

// ApplyMailDemoActionJSONRequestBody defines body for ApplyMailDemoAction for application/json ContentType.
type ApplyMailDemoActionJSONRequestBody = MailDemoAction

// DeliverMessageJSONRequestBody defines body for DeliverMessage for application/json ContentType.
type DeliverMessageJSONRequestBody = MessageRequest

// AsValidationDetails returns the union data inside the ApiError_Details as a ValidationDetails
func (t ApiError_Details) AsValidationDetails() (ValidationDetails, error) {
	var body ValidationDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationDetails overwrites any union data inside the ApiError_Details as the provided ValidationDetails
func (t *ApiError_Details) FromValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationDetails performs a merge with any union data inside the ApiError_Details, using the provided ValidationDetails
func (t *ApiError_Details) MergeValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnavailableDetails returns the union data inside the ApiError_Details as a UnavailableDetails
func (t ApiError_Details) AsUnavailableDetails() (UnavailableDetails, error) {
	var body UnavailableDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnavailableDetails overwrites any union data inside the ApiError_Details as the provided UnavailableDetails
func (t *ApiError_Details) FromUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnavailableDetails performs a merge with any union data inside the ApiError_Details, using the provided UnavailableDetails
func (t *ApiError_Details) MergeUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDailyLimitDetails returns the union data inside the ApiError_Details as a DailyLimitDetails
func (t ApiError_Details) AsDailyLimitDetails() (DailyLimitDetails, error) {
	var body DailyLimitDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDailyLimitDetails overwrites any union data inside the ApiError_Details as the provided DailyLimitDetails
func (t *ApiError_Details) FromDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDailyLimitDetails performs a merge with any union data inside the ApiError_Details, using the provided DailyLimitDetails
func (t *ApiError_Details) MergeDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApiError_Details) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiError_Details) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBodyViolation returns the union data inside the Violation as a BodyViolation
func (t Violation) AsBodyViolation() (BodyViolation, error) {
	var body BodyViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBodyViolation overwrites any union data inside the Violation as the provided BodyViolation
func (t *Violation) FromBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBodyViolation performs a merge with any union data inside the Violation, using the provided BodyViolation
func (t *Violation) MergeBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterViolation returns the union data inside the Violation as a ParameterViolation
func (t Violation) AsParameterViolation() (ParameterViolation, error) {
	var body ParameterViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterViolation overwrites any union data inside the Violation as the provided ParameterViolation
func (t *Violation) FromParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterViolation performs a merge with any union data inside the Violation, using the provided ParameterViolation
func (t *Violation) MergeParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Violation) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Violation) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMessages get Messages
	// (GET /api/v1/messages)
	GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams)
	// GetMessage get Message
	// (GET /api/v1/messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams)
	// ApplyMailDemoAction apply Mail Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams)
	// DeliverMessage deliver Message
	// (POST /internal/v1/messages)
	DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetMessages get Messages
// (GET /api/v1/messages)
func (_ Unimplemented) GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMessage get Message
// (GET /api/v1/messages/{id})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApplyMailDemoAction apply Mail Demo Action
// (POST /internal/v1/demo/actions)
func (_ Unimplemented) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeliverMessage deliver Message
// (POST /internal/v1/messages)
func (_ Unimplemented) DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMessages operation middleware
func (siw *ServerInterfaceWrapper) GetMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ResourceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessageParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyMailDemoAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyMailDemoActionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyMailDemoAction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeliverMessage operation middleware
func (siw *ServerInterfaceWrapper) DeliverMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeliverMessageParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	// ------------- Required header parameter "Delivery-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Delivery-Key")]; found {
		var DeliveryKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Delivery-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Delivery-Key", valueList[0], &DeliveryKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Delivery-Key", Err: err})
			return
		}

		params.DeliveryKey = DeliveryKey

	} else {
		err := fmt.Errorf("Header parameter Delivery-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Delivery-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeliverMessage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/messages", wrapper.GetMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/messages/{id}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/demo/actions", wrapper.ApplyMailDemoAction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/messages", wrapper.DeliverMessage)
	})

	return r
}

type GetMessagesRequestObject struct {
	Params GetMessagesParams
}

type GetMessagesResponseObject interface {
	VisitGetMessagesResponse(w http.ResponseWriter) error
}

type GetMessages200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages200JSONResponse struct {
	Body    MessageCollection
	Headers GetMessages200ResponseHeaders
}

func (response GetMessages200JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages400JSONResponse struct {
	Body    ApiError
	Headers GetMessages400ResponseHeaders
}

func (response GetMessages400JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages413JSONResponse struct {
	Body    ApiError
	Headers GetMessages413ResponseHeaders
}

func (response GetMessages413JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages422JSONResponse struct {
	Body    ApiError
	Headers GetMessages422ResponseHeaders
}

func (response GetMessages422JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages500JSONResponse struct {
	Body    ApiError
	Headers GetMessages500ResponseHeaders
}

func (response GetMessages500JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages503JSONResponse struct {
	Body    ApiError
	Headers GetMessages503ResponseHeaders
}

func (response GetMessages503JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessageRequestObject struct {
	Id     ResourceId `json:"id"`
	Params GetMessageParams
}

type GetMessageResponseObject interface {
	VisitGetMessageResponse(w http.ResponseWriter) error
}

type GetMessage200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage200JSONResponse struct {
	Body    Message
	Headers GetMessage200ResponseHeaders
}

func (response GetMessage200JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage400JSONResponse struct {
	Body    ApiError
	Headers GetMessage400ResponseHeaders
}

func (response GetMessage400JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage404ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage404JSONResponse struct {
	Body    ApiError
	Headers GetMessage404ResponseHeaders
}

func (response GetMessage404JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage413JSONResponse struct {
	Body    ApiError
	Headers GetMessage413ResponseHeaders
}

func (response GetMessage413JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage422JSONResponse struct {
	Body    ApiError
	Headers GetMessage422ResponseHeaders
}

func (response GetMessage422JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage500JSONResponse struct {
	Body    ApiError
	Headers GetMessage500ResponseHeaders
}

func (response GetMessage500JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage503JSONResponse struct {
	Body    ApiError
	Headers GetMessage503ResponseHeaders
}

func (response GetMessage503JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoActionRequestObject struct {
	Params ApplyMailDemoActionParams
	Body   *ApplyMailDemoActionJSONRequestBody
}

type ApplyMailDemoActionResponseObject interface {
	VisitApplyMailDemoActionResponse(w http.ResponseWriter) error
}

type ApplyMailDemoAction200ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type ApplyMailDemoAction200JSONResponse struct {
	Body    MailDemoResult
	Headers ApplyMailDemoAction200ResponseHeaders
}

func (response ApplyMailDemoAction200JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction400JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction400ResponseHeaders
}

func (response ApplyMailDemoAction400JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction401JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction401ResponseHeaders
}

func (response ApplyMailDemoAction401JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction409ResponseHeaders struct {
	CacheControl *string
	RetryAfter   *int
	XRequestID   *RequestId
}

type ApplyMailDemoAction409JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction409ResponseHeaders
}

func (response ApplyMailDemoAction409JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction413JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction413ResponseHeaders
}

func (response ApplyMailDemoAction413JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction415JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction415ResponseHeaders
}

func (response ApplyMailDemoAction415JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction422JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction422ResponseHeaders
}

func (response ApplyMailDemoAction422JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction500JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction500ResponseHeaders
}

func (response ApplyMailDemoAction500JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction503JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction503ResponseHeaders
}

func (response ApplyMailDemoAction503JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessageRequestObject struct {
	Params DeliverMessageParams
	Body   *DeliverMessageJSONRequestBody
}

type DeliverMessageResponseObject interface {
	VisitDeliverMessageResponse(w http.ResponseWriter) error
}

type DeliverMessage201ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type DeliverMessage201JSONResponse struct {
	Body    DeliveryReceipt
	Headers DeliverMessage201ResponseHeaders
}

func (response DeliverMessage201JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage400JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage400ResponseHeaders
}

func (response DeliverMessage400JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage401JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage401ResponseHeaders
}

func (response DeliverMessage401JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage409ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage409JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage409ResponseHeaders
}

func (response DeliverMessage409JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage413JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage413ResponseHeaders
}

func (response DeliverMessage413JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage415JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage415ResponseHeaders
}

func (response DeliverMessage415JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage422JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage422ResponseHeaders
}

func (response DeliverMessage422JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage500JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage500ResponseHeaders
}

func (response DeliverMessage500JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage503JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage503ResponseHeaders
}

func (response DeliverMessage503JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMessages get Messages
	// (GET /api/v1/messages)
	GetMessages(ctx context.Context, request GetMessagesRequestObject) (GetMessagesResponseObject, error)
	// GetMessage get Message
	// (GET /api/v1/messages/{id})
	GetMessage(ctx context.Context, request GetMessageRequestObject) (GetMessageResponseObject, error)
	// ApplyMailDemoAction apply Mail Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyMailDemoAction(ctx context.Context, request ApplyMailDemoActionRequestObject) (ApplyMailDemoActionResponseObject, error)
	// DeliverMessage deliver Message
	// (POST /internal/v1/messages)
	DeliverMessage(ctx context.Context, request DeliverMessageRequestObject) (DeliverMessageResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMessages operation middleware
func (sh *strictHandler) GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams) {
	var request GetMessagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMessages(ctx, request.(GetMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMessagesResponseObject); ok {
		if err := validResponse.VisitGetMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMessage operation middleware
func (sh *strictHandler) GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams) {
	var request GetMessageRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMessage(ctx, request.(GetMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMessageResponseObject); ok {
		if err := validResponse.VisitGetMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyMailDemoAction operation middleware
func (sh *strictHandler) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams) {
	var request ApplyMailDemoActionRequestObject

	request.Params = params

	var body ApplyMailDemoActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyMailDemoAction(ctx, request.(ApplyMailDemoActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyMailDemoAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyMailDemoActionResponseObject); ok {
		if err := validResponse.VisitApplyMailDemoActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeliverMessage operation middleware
func (sh *strictHandler) DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams) {
	var request DeliverMessageRequestObject

	request.Params = params

	var body DeliverMessageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeliverMessage(ctx, request.(DeliverMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeliverMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeliverMessageResponseObject); ok {
		if err := validResponse.VisitDeliverMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fz/d+I4kv9X9Hzz3u3ema9JerrJD3cMON3sEMgakp1MT85P2CJo2kgeSU6H7cf/fq8kGWxwEujp6aF3",
	"6R86YOtLqapUqvqUik9OyOcJZ4Qp6bQ+OTOCIyL0xw4OZ6TDmRI8hu8RkaGgiaKcOS3HJzLhTBKJ5qlU",
	"iHGFJgSF0CeqOq4jwxmZY+hHWDp3Wu8dxitScUGcO9dRi4Q4LUcqQdm9s1y6Ti8i84QrwsKFT5IYL0i0",
	"PakSKUGcxQs05QJhJHRLxKdIzQiS+IFEiAt6TxmOkVRYpRJhFqEJjxZFoiwBE85jgpmmwCe/pUSqXsm8",
	"vYgwRaeUCDMXlejdeHyFsFJknqgqMiRLJIjClGlqVnTA5EiYwQO6wZzvBJk6Lec/amsx1MxbWVsTZMhT",
	"YtGeKiLKhKHEAmF4iTgjSJKQs8gwiSHKKtOY3s8UCvl8jlm5fBprsVCmyD0RznK5zBpqjWgn1BOCawJw",
	"FFGYHcdXgidEKEqk05riWBLXSXKPQMMi8tJa9bgdaLh0nQi4GOu+nJHh1Gm9f773DY5phIGcru26dJ/v",
	"cc3wA6YxnsRk1y5dTONFn86pWvW4W7rOnEiJ78m2UEZ4SpDH7mMqZ8i2OkdhTGFUpARmMsaKoA+Mf2QI",
	"mCSrzkoG2dZwnbXq7Kcw0I8K2EbvjQjWtBYGXcudT34loYI5f+DR4obyGJu1fJa4txYS83A1XmYUYHOU",
	"GIQCW7feJRw0tGQf/G00HKAr8xZ9pGrGU6U341Tg+zlhCs2x+EAE8DmBzSug1//9pVb9r7/+z3dOmV3K",
	"c3G1gDUJ7iZry7jZMdvOWBbyiOdJDA0a9l9F/3cK/73Ovmb/HNeZcjHHymk5aUqjIuHv65U3uDK9+/R6",
	"WVl9Pl1WTldfTpaV96/f4Mld4Un2udFcbq/adR4r97yyxfVOKiQvYfoNEZJyRiL0A5bk1em130ehbosk",
	"vYfnIAn07rLdqYzetZtnrxB/IAIRFmkuuijhUiuXi1JJBJIhT4i227+lRCxQggWeE0WErKILLj5iEelD",
	"4Bwxjsbj/jkSXGnBIMoejCkg0tIgq6jNFkgumMKPrqYIq1SAfbYTTTGN4YEgKhVMot7gpt3vdYPOtT8a",
	"+qAqa5GRxd+avV/54/TvIHLK+oTdq5nTahTF0q78jCv/rFfeBJW7//6ubFNvG5OXNlmR6WM47xLQaBzH",
	"/CNmoeEYKPuca1WnClE4kfShG7n6NIDXgkxTiWOkZljBCcqFkogqvScKGzkCGoMYiHzJ8qyXM1JYka2d",
	"kx+qbIds9t+fGXqGHDP4FE0FgdVKIh60dkgXCYIj9HFG1AxOSqHdFnAjmMIxcCtMBXypop5mXkQEBZ9i",
	"KvjcuBial4VBM+8DhyFPQZvt+Q8taEiQonPyT86IiwTW06oZZusR8UQSSy/OprcEbUtkdWZt78J/2EVp",
	"58TSguZ4gaSicYxCQeCswVtMycjNprZkVzKyUYQXVXQBbEdzgpnUrSO8+E+Z4zaVRhvPrdYZvoIHRrQu",
	"4klmibN5rJJyYd9hFNMHYlfuIoLDGfDk44yGsxU/iUDhjIQfJML34Gd9nBEGbDP2FWEB4sqfoiv/DtRR",
	"EiUDrHUZx/EObsWYzolUeJ44y7synbNr0GJcscKaERdNCGX3VmuwUJmeMPKogH9P6Umme7mdrDiKqNSu",
	"LiyTEWAERtrrq2iXsAV+XsqmlFE5I9GaI0x+JEIaC7z2DF3LVyspzUaYT29Q6EwkmuDwQ3VrI681MM/R",
	"0i1NQKBi4ZOQ0ETt6UTgMCSJIpGV145Scp1dnCTJUxGSEi9JH6/5mcvWtfZUc27MZbt/MfQvvW4ALojj",
	"Otkh8s5rdz0/98CcKo7r/DDs3gbj4TDot/23nuM614PR9dXV0B973eDS6/bawfj2Cl7oju1xbzgILtq9",
	"vtd1XOfSG78bdoPBcBy0+/3hP/TD9vX4nTcY9zqmse/9/brne9387L7XhRbt/shxHe+y3esH7b7vtbu3",
	"ge+97Y3Gnukw9Htve4ON8Tsj/yKwQ+lBx54/aPeDZ+btepdXw7E36NwGP3q3z73KjZt70xkOLvq9znjj",
	"cW8QXPnDt743gnX43mh47Xc8Te7F8HoAo9x473qdvhdcD9o37V6//UPfyz3tDYLrETzI9ey0fb/nddcP",
	"O+2rdqc3vg28nzqe1zU87ox7N17ge4Nxux94P/VGYyCh2+71b4N+77I3Dnyv3XlnuHg9Ho3bg25v8BbW",
	"N+x1PEOu598YXnk/XVl+2BE7w8urvjcuSM2+Go3bY8+O2ut6AYzS63jBz8MBPB57fe/SG/u30FAv9qp9",
	"e+kNxhvc6nr93o3nF3jrt8eeod4Iuj/s/BgMr8fB8CIY3Q468Gw46Fz7vma/r6fxfnrXvh6ZHhktRW6v",
	"NMTz/aFf6udfYhp3yZy3w88INXC4GU9EgicBmNhAWIAi0GFxYLZ1KQlmlB3iq7Ufv2UWV0Nkw5Xajmyx",
	"PpFprD5rsfuR6Trm2AzgdNnDkD6zvPyApWtcB24HZ+9dR6aG0LKwUpHHJ15weLyKw8gc0xj8f/yY+f/N",
	"s9OXgkfNPMWdNQ3Fs8bO/wxLOzyOyedsE6rIvPjhOYbZ2UbpfI7FwlmuCMJCYP1d76/wiXDQt2s+RyyN",
	"Y8StZ4GldvYALoOI7p5U0chEh2agcyQJQSbGrG4FVzCU8XsBAtwv2NqUg+ZBcRHPMN1iKntyPKdmxYU8",
	"qXRFJl7FGkYEV9FGutrn05hDIogiEcKAQV72qwg8UcUhgLkeX1ReZ1CjwR0hGIglN54dicCVbL5qNk5P",
	"0WShjKucV2P9yv2DdsCG8r+k7pkCfoOG5GvYizLOXWVIyVfB7jQ6YwCpmePa1MH+YF5Gc8nbZ/C3Va+d",
	"ELgCtp+Dc8ynit0ylUZRSo3m651QnuqTME9OZwoT1xtv3pyenDYrryb4+8r39Xq98hr+q6//fSb09/0f",
	"Af2td8qWpboed5B/0Tk5OXnjIvKIQxUvkKSPALmGRutQRO+pkuco4nMwazY4lYD2oQgrPMHSxL9FsK1Z",
	"b76q1N9UGs1x/ftW46x1Uq82mienZ69+zvMmwsrAFUUG/fJLBPyAP83sz9j8aRX+/PJLFT68Wv68O0NK",
	"0gf7bbR0PUAgCJac7X5A5yb3dVe9xSjrmc6NjQPbdVJGf0uJfQ0H6ObGKqOmbBttz5wzB5TJdDqlISVM",
	"BYQRcb/QVj4mcwAqAqmwhg14qiSNSGCBjwBAD+tXwtcVXdA3nDEa4jjIEVhqYLYTQPuJ4yGzl7tLYW1i",
	"n+X+JqtzM5VxuGC4d0t+FXM1L2WxSo6I5d1SBwphKqhajKCh4UoG4Yz5B8K2tz4ca1KlkyCy7QKlG9qc",
	"ocbfCBbaRtuFzpRK8oHQyyPP+a6jwiIom/JSb4qBp3l5c4VCSGjjUOnkQSJ4lGorhWaYRbFOMegkklil",
	"t8FI6VR4xebCUZbIrqIhpKLhVIqR4S+A60QQFhKJsLCwIImqaETgxFIAsUkFm0O2jDen7aPlX22K01gZ",
	"EnmMKIN9YlBTziCxTARiRH3k4sM5woyzxZynUoPaFZ0Vp2zCH8HlBo60arVG8/tqvVqvNlqv680zgwIy",
	"jjpDf+RaSNiF2YnS+RAN6FVRL6NrwiNqF/KU/4g6gMcaGnGCJzSmalGRCQnplIbISAppCaIJmXJBslMg",
	"wYuY4+gczamUlN3XbO4GTbiaWRQVvQQxVZFnjxzOCBIkJMBI+MBFhBIiVrxFH8jiXNMJ7CMCSQJHkMmZ",
	"w4lENUJL2QOnIanxVE34I4D5EUkIiwjTk0yB7LnOEFyZD0CpAC5FXGOpK6Dd5uBhC8ZEq5j2A6vomsk0",
	"gawLidCcqBmPDItP62doG9YzQmuDHp2jlOlkcQ34SO8ZEta9MLccUkZhLqCKRHndBgctm+MUbaNlVaRB",
	"TaPrWZLfRT9VrNtU6XX1BGvFH+l0Ws24fIiY3maC+jkk7CRkTSiJo8LLZrOK1qYa2Tw/ghOE6N2B43iD",
	"5RFRJFRg+NHadAJ2Di/EHABvBYrGo0VNO6Q1WG1GGVBtU7W1lcuIuIhMDlhRpT2NDhajGYbDBGWmZ604",
	"MMbGFnNc58FkPZ2W04AtBkaNJ4ThhDot56Rar55Yz1hb0hpOaO2hUbM+qn52T1RZ9JxNtN7f2sDMuFRm",
	"8ioaAv3oL7loAHW9UcdFNNIf/qqTfas8adWG1SBeiTCKSERDrNUvWywkZ2GHmNsyFHZGpluGqyZXWkUD",
	"vhVfJiAGpSDFSFkYpxGwETMb6mtras434DgculqG4BE7b4m6zDiS8+mlPvMo8MPI0XEdhrXpz+vk512k",
	"sQNnwYsd16Qm8wNGRFtjp9Ws66CAzsHNadTr+rS330quzDwxgUUadiXZSMxZQuJpdRZBp2a9bgI1pggz",
	"sESSxNQERrVfM58sc6JXzsz7jdD4Be+aRrtHKatQ2OkZ64molCmx8WvLgaT+/1qKqopIpdNpBRAJ8J3l",
	"rrzZhsP02b9x+yYNQyLlNI1XZ3l1FaSu77dVchfcyua07WuFy3BLt6iHL/TNq9/SdU73kaCmdCN3BP4q",
	"jlOyDti3s0uriDsLfVHI0zha3dMzp5KWUf5+UUlEDCRvZLOeIWCV7/qSBOysGdnZVaYQRQpdtMWyP1s1",
	"INbUh2UFeApb9sUsItw/O22c7KlOG5nHEmlu5SYPTppbFB6g9DZo1MJqNvcU1nbyt0ReZRni3CXKfHT7",
	"ftUpF2iv0T1zIW9T4NAM6UnhwLcOe+4WXMupGZCzeCPyUJSljD0HqC/bZAI3zz7juChkXUutdaHFQVrr",
	"DQoP0joXs9taWPsa47LEeYnEyvPrBye2cjIPUHZlhBZgMKf1/g5cW5uDgmgN5WKVxwoYyoq9HPnq7Ozk",
	"FTxcBeBa4BVTguC0nMQgULpjhgDpqAGCSZh2M0CsfaLRcococSs27NqLYjp3mF2BhkThOnmoafvjQrmv",
	"HcnZ9JMdlmbKbgBXky7edfDczbDfHXf9GdGWziU7Po1ye7+lL1UH2dXAKhpDrriFTur1OlILumDVZwK1",
	"PWOyf5dI7F8nEPomAh/tOtdP9xRWybXAEoGVXh48OKGVUnmAgiuh8xikHoPUY5B6DFKPQeoxSD0GqV8r",
	"SP0jYtTswgIEqhGZ85q54aV5lnBZGqiaqqXs/vgqIsWQur1fp8l1rs3cZTUFUln21aTmoUBRZmn97B6B",
	"4EmSlViFnDGTDFpPsQ43UDvL+gtdKW8vCshiob4wlUpVZMWyCouzQ2g76m0nSbzYKGH4SuHv3Wq7wAWg",
	"fWNTK5+XyiUKxRG7FSzvHjIW2bZcLjcD9+Xvj8H3JH6jXuLZsH3vhdqqj68fIud+W6OS/3GN58Yo+z2O",
	"f7No290s6yshYKvw7+DznlsUfwt5zw2iDR7Q+FyX86l6xeec0KdrHA/XLX2a5kN2VJ+i2gj9zb5CLysm",
	"LRN0edHpF75H8UQJ6wv0FOs3D0/fSljnoqcX8KWUL1f//rLurX486Qtr7X61ykcs7FvDwhpnewrriTL+",
	"EqE9WfB/cMJ7ktIDFOITtB6BzSOweQQ2j8DmEdj8RoDNT5tFYu/vlgWwE2S7QNAIQSu0gt+KuGdW0/4Z",
	"wKdBO7exz3wVRznu2VZ8DoWLUAurNFiZK0OydbLI6qmuuZCmxGUFQY7wnEDbmv31UPPzoiuosllvZG1N",
	"gVAZxIMAQ9OFYvqXwexI5kfutn4EpmouCemaHVOtA2qcXWLZBxO1VYN/0m2gzYGzGsbKj2Tx7M2gXOmw",
	"LQJrfYEa65a5nFP2sxS/B8A96EtAViy7IbqNQ7hVtfMKN3/UrMQId3QBYHTEb4/47RG/PeK3R/z29+G3",
	"W45KmZS3Gx2gWMuIPEA5bpN5BC2PoOURtDyClkfQ8ghaHkHLI2h5BC2fAS03fjNrE7S0OOCTtzS/BFq5",
	"XP7/AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
