// Package mailstubapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package mailstubapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BodyViolationLocation.
const (
	Body BodyViolationLocation = "body"
)

// Valid indicates whether the value is a known member of the BodyViolationLocation enum.
func (e BodyViolationLocation) Valid() bool {
	switch e {
	case Body:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ACTIVERENTALEXISTS             ErrorCode = "ACTIVE_RENTAL_EXISTS"
	AUTHENTICATIONREQUIRED         ErrorCode = "AUTHENTICATION_REQUIRED"
	BODYTOOLARGE                   ErrorCode = "BODY_TOO_LARGE"
	CLOCKOUTOFSYNC                 ErrorCode = "CLOCK_OUT_OF_SYNC"
	CONCURRENCYRETRYEXHAUSTED      ErrorCode = "CONCURRENCY_RETRY_EXHAUSTED"
	CSRFINVALID                    ErrorCode = "CSRF_INVALID"
	DAILYLIMITREACHED              ErrorCode = "DAILY_LIMIT_REACHED"
	DELIVERYCONFLICT               ErrorCode = "DELIVERY_CONFLICT"
	EMAILALREADYREGISTERED         ErrorCode = "EMAIL_ALREADY_REGISTERED"
	IDEMPOTENCYCONFLICT            ErrorCode = "IDEMPOTENCY_CONFLICT"
	IDEMPOTENCYINPROGRESS          ErrorCode = "IDEMPOTENCY_IN_PROGRESS"
	IDEMPOTENCYKEYINVALID          ErrorCode = "IDEMPOTENCY_KEY_INVALID"
	IDEMPOTENCYKEYREQUIRED         ErrorCode = "IDEMPOTENCY_KEY_REQUIRED"
	INTERNALAUTHENTICATIONREQUIRED ErrorCode = "INTERNAL_AUTHENTICATION_REQUIRED"
	INTERNALERROR                  ErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS             ErrorCode = "INVALID_CREDENTIALS"
	INVALIDCURSOR                  ErrorCode = "INVALID_CURSOR"
	INVALIDHEADER                  ErrorCode = "INVALID_HEADER"
	INVALIDRENTALSTATE             ErrorCode = "INVALID_RENTAL_STATE"
	MALFORMEDJSON                  ErrorCode = "MALFORMED_JSON"
	METHODNOTALLOWED               ErrorCode = "METHOD_NOT_ALLOWED"
	ORIGINNOTALLOWED               ErrorCode = "ORIGIN_NOT_ALLOWED"
	OUTSIDESERVICEZONE             ErrorCode = "OUTSIDE_SERVICE_ZONE"
	OUTSTANDINGINVOICE             ErrorCode = "OUTSTANDING_INVOICE"
	PAYMENTINPROGRESS              ErrorCode = "PAYMENT_IN_PROGRESS"
	RATELIMITED                    ErrorCode = "RATE_LIMITED"
	RENTALCOMPLETED                ErrorCode = "RENTAL_COMPLETED"
	RESERVATIONEXPIRED             ErrorCode = "RESERVATION_EXPIRED"
	RESOURCENOTFOUND               ErrorCode = "RESOURCE_NOT_FOUND"
	SERVICEUNAVAILABLE             ErrorCode = "SERVICE_UNAVAILABLE"
	SOURCECAPACITYEXCEEDED         ErrorCode = "SOURCE_CAPACITY_EXCEEDED"
	SOURCENOTCARRIED               ErrorCode = "SOURCE_NOT_CARRIED"
	TELEMETRYSTALE                 ErrorCode = "TELEMETRY_STALE"
	UNSUPPORTEDMEDIATYPE           ErrorCode = "UNSUPPORTED_MEDIA_TYPE"
	VALIDATIONFAILED               ErrorCode = "VALIDATION_FAILED"
	VEHICLEINUSE                   ErrorCode = "VEHICLE_IN_USE"
	VEHICLEUNAVAILABLE             ErrorCode = "VEHICLE_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ACTIVERENTALEXISTS:
		return true
	case AUTHENTICATIONREQUIRED:
		return true
	case BODYTOOLARGE:
		return true
	case CLOCKOUTOFSYNC:
		return true
	case CONCURRENCYRETRYEXHAUSTED:
		return true
	case CSRFINVALID:
		return true
	case DAILYLIMITREACHED:
		return true
	case DELIVERYCONFLICT:
		return true
	case EMAILALREADYREGISTERED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case IDEMPOTENCYINPROGRESS:
		return true
	case IDEMPOTENCYKEYINVALID:
		return true
	case IDEMPOTENCYKEYREQUIRED:
		return true
	case INTERNALAUTHENTICATIONREQUIRED:
		return true
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDCURSOR:
		return true
	case INVALIDHEADER:
		return true
	case INVALIDRENTALSTATE:
		return true
	case MALFORMEDJSON:
		return true
	case METHODNOTALLOWED:
		return true
	case ORIGINNOTALLOWED:
		return true
	case OUTSIDESERVICEZONE:
		return true
	case OUTSTANDINGINVOICE:
		return true
	case PAYMENTINPROGRESS:
		return true
	case RATELIMITED:
		return true
	case RENTALCOMPLETED:
		return true
	case RESERVATIONEXPIRED:
		return true
	case RESOURCENOTFOUND:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case SOURCECAPACITYEXCEEDED:
		return true
	case SOURCENOTCARRIED:
		return true
	case TELEMETRYSTALE:
		return true
	case UNSUPPORTEDMEDIATYPE:
		return true
	case VALIDATIONFAILED:
		return true
	case VEHICLEINUSE:
		return true
	case VEHICLEUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for MailDemoActionAction.
const (
	DropNextResponseAfterAccept MailDemoActionAction = "drop_next_response_after_accept"
)

// Valid indicates whether the value is a known member of the MailDemoActionAction enum.
func (e MailDemoActionAction) Valid() bool {
	switch e {
	case DropNextResponseAfterAccept:
		return true
	default:
		return false
	}
}

// Defines values for ParameterViolationLocation.
const (
	Header ParameterViolationLocation = "header"
	Path   ParameterViolationLocation = "path"
	Query  ParameterViolationLocation = "query"
)

// Valid indicates whether the value is a known member of the ParameterViolationLocation enum.
func (e ParameterViolationLocation) Valid() bool {
	switch e {
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	InsufficientEnergy   UnavailableReason = "insufficient_energy"
	OutsideServiceZone   UnavailableReason = "outside_service_zone"
	ServiceRequired      UnavailableReason = "service_required"
	TechnicalUnavailable UnavailableReason = "technical_unavailable"
	TelemetryStale       UnavailableReason = "telemetry_stale"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case InsufficientEnergy:
		return true
	case OutsideServiceZone:
		return true
	case ServiceRequired:
		return true
	case TechnicalUnavailable:
		return true
	case TelemetryStale:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Code    ErrorCode         `json:"code"`
	Details *ApiError_Details `json:"details,omitempty"`

	// Message Safe English message; clients translate known codes.
	Message string `json:"message"`

	// RequestId Example: example-request-1
	RequestId RequestId `json:"request_id"`
}

// ApiError_Details defines model for ApiError.Details.
type ApiError_Details struct {
	union json.RawMessage
}

// BodyViolation defines model for BodyViolation.
type BodyViolation struct {
	Code     string                `json:"code"`
	Location BodyViolationLocation `json:"location"`
	Message  string                `json:"message"`

	// Pointer JSON Pointer without the fragment marker.
	Pointer string `json:"pointer"`
}

// BodyViolationLocation defines model for BodyViolation.Location.
type BodyViolationLocation string

// CommandId Example: 11111111-1111-4111-8111-111111111111
type CommandId = string

// Cursor Versioned Base64URL cursor signed with HMAC-SHA256 over endpoint, position, user scope and query parameters. Forward only; no TTL; rotation invalidates cursors. Any syntax, signature or scope failure returns INVALID_CURSOR.
//
// Example: eyJ2IjoxfQ
type Cursor = string

// DailyLimitDetails The spent allowance and the moment it is restored, for the refusal that reports it.
type DailyLimitDetails struct {
	// DailyLimit The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
	DailyLimit DailyLimitState `json:"daily_limit"`
}

// DailyLimitState The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
type DailyLimitState struct {
	// Available Whether this account may still create a free reservation in the current service-timezone day. False means the day's allowance is spent; it is not a statement about the current moment or about a live rental, each of which the server checks again when a command arrives.
	Available bool `json:"available"`

	// ResetsAt The moment the allowance returns, being the start of the next day in the service timezone. It is the moment to display and never a Retry-After: an unfinished command answers with one second, which is not when the limit comes back.
	ResetsAt Timestamp `json:"resets_at"`
}

// DeliveryReceipt defines model for DeliveryReceipt.
type DeliveryReceipt struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id ResourceId `json:"id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// MailDemoAction defines model for MailDemoAction.
type MailDemoAction struct {
	Action MailDemoActionAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`
}

// MailDemoActionAction defines model for MailDemoAction.Action.
type MailDemoActionAction string

// MailDemoResult defines model for MailDemoResult.
type MailDemoResult struct {
	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`
}

// Message defines model for Message.
type Message struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id      ResourceId          `json:"id"`
	Subject string              `json:"subject"`
	Text    string              `json:"text"`
	To      openapi_types.Email `json:"to"`
}

// MessageCollection defines model for MessageCollection.
type MessageCollection struct {
	Items []MessageSummary `json:"items"`

	// NextCursor Required; null on the last or empty page. Signed cursor; see Cursor.
	NextCursor *string `json:"next_cursor"`
}

// MessageRequest defines model for MessageRequest.
type MessageRequest struct {
	Subject string `json:"subject"`

	// Text Plain text only; never interpreted as HTML. The total UTF-8 request body is also limited to 262144 bytes.
	Text string              `json:"text"`
	To   openapi_types.Email `json:"to"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id      ResourceId          `json:"id"`
	Subject string              `json:"subject"`
	To      openapi_types.Email `json:"to"`
}

// ParameterViolation defines model for ParameterViolation.
type ParameterViolation struct {
	Code      string                     `json:"code"`
	Location  ParameterViolationLocation `json:"location"`
	Message   string                     `json:"message"`
	Parameter string                     `json:"parameter"`
}

// ParameterViolationLocation defines model for ParameterViolation.Location.
type ParameterViolationLocation string

// RequestId Example: example-request-1
type RequestId = string

// ResourceId Example: 01994342-6ba7-7000-8000-000000000001
type ResourceId = string

// Timestamp UTC RFC3339, exactly six fractional digits; domain commands use database time.
//
// Example: 2026-09-12T07:15:30.123456Z
type Timestamp = string

// UnavailableDetails defines model for UnavailableDetails.
type UnavailableDetails struct {
	UnavailableReasons []UnavailableReason `json:"unavailable_reasons"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// ValidationDetails defines model for ValidationDetails.
type ValidationDetails struct {
	Violations []Violation `json:"violations"`
}

// Violation defines model for Violation.
type Violation struct {
	union json.RawMessage
}

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	Limit      *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor     *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetMessageParams defines parameters for GetMessage.
type GetMessageParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ApplyMailDemoActionParams defines parameters for ApplyMailDemoAction.
type ApplyMailDemoActionParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// DeliverMessageParams defines parameters for DeliverMessage.
type DeliverMessageParams struct {
	XRequestID  *RequestId `json:"X-Request-ID,omitempty"`
	DeliveryKey string     `json:"Delivery-Key"`
}

// ApplyMailDemoActionJSONRequestBody defines body for ApplyMailDemoAction for application/json ContentType.
type ApplyMailDemoActionJSONRequestBody = MailDemoAction

// DeliverMessageJSONRequestBody defines body for DeliverMessage for application/json ContentType.
type DeliverMessageJSONRequestBody = MessageRequest

// AsValidationDetails returns the union data inside the ApiError_Details as a ValidationDetails
func (t ApiError_Details) AsValidationDetails() (ValidationDetails, error) {
	var body ValidationDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationDetails overwrites any union data inside the ApiError_Details as the provided ValidationDetails
func (t *ApiError_Details) FromValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationDetails performs a merge with any union data inside the ApiError_Details, using the provided ValidationDetails
func (t *ApiError_Details) MergeValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnavailableDetails returns the union data inside the ApiError_Details as a UnavailableDetails
func (t ApiError_Details) AsUnavailableDetails() (UnavailableDetails, error) {
	var body UnavailableDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnavailableDetails overwrites any union data inside the ApiError_Details as the provided UnavailableDetails
func (t *ApiError_Details) FromUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnavailableDetails performs a merge with any union data inside the ApiError_Details, using the provided UnavailableDetails
func (t *ApiError_Details) MergeUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDailyLimitDetails returns the union data inside the ApiError_Details as a DailyLimitDetails
func (t ApiError_Details) AsDailyLimitDetails() (DailyLimitDetails, error) {
	var body DailyLimitDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDailyLimitDetails overwrites any union data inside the ApiError_Details as the provided DailyLimitDetails
func (t *ApiError_Details) FromDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDailyLimitDetails performs a merge with any union data inside the ApiError_Details, using the provided DailyLimitDetails
func (t *ApiError_Details) MergeDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApiError_Details) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiError_Details) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBodyViolation returns the union data inside the Violation as a BodyViolation
func (t Violation) AsBodyViolation() (BodyViolation, error) {
	var body BodyViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBodyViolation overwrites any union data inside the Violation as the provided BodyViolation
func (t *Violation) FromBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBodyViolation performs a merge with any union data inside the Violation, using the provided BodyViolation
func (t *Violation) MergeBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterViolation returns the union data inside the Violation as a ParameterViolation
func (t Violation) AsParameterViolation() (ParameterViolation, error) {
	var body ParameterViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterViolation overwrites any union data inside the Violation as the provided ParameterViolation
func (t *Violation) FromParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterViolation performs a merge with any union data inside the Violation, using the provided ParameterViolation
func (t *Violation) MergeParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Violation) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Violation) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMessages get Messages
	// (GET /api/v1/messages)
	GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams)
	// GetMessage get Message
	// (GET /api/v1/messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams)
	// ApplyMailDemoAction apply Mail Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams)
	// DeliverMessage deliver Message
	// (POST /internal/v1/messages)
	DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetMessages get Messages
// (GET /api/v1/messages)
func (_ Unimplemented) GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMessage get Message
// (GET /api/v1/messages/{id})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApplyMailDemoAction apply Mail Demo Action
// (POST /internal/v1/demo/actions)
func (_ Unimplemented) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeliverMessage deliver Message
// (POST /internal/v1/messages)
func (_ Unimplemented) DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMessages operation middleware
func (siw *ServerInterfaceWrapper) GetMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ResourceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessageParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyMailDemoAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyMailDemoActionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyMailDemoAction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeliverMessage operation middleware
func (siw *ServerInterfaceWrapper) DeliverMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeliverMessageParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	// ------------- Required header parameter "Delivery-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Delivery-Key")]; found {
		var DeliveryKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Delivery-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Delivery-Key", valueList[0], &DeliveryKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Delivery-Key", Err: err})
			return
		}

		params.DeliveryKey = DeliveryKey

	} else {
		err := fmt.Errorf("Header parameter Delivery-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Delivery-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeliverMessage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/messages", wrapper.GetMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/messages/{id}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/demo/actions", wrapper.ApplyMailDemoAction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/messages", wrapper.DeliverMessage)
	})

	return r
}

type GetMessagesRequestObject struct {
	Params GetMessagesParams
}

type GetMessagesResponseObject interface {
	VisitGetMessagesResponse(w http.ResponseWriter) error
}

type GetMessages200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages200JSONResponse struct {
	Body    MessageCollection
	Headers GetMessages200ResponseHeaders
}

func (response GetMessages200JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages400JSONResponse struct {
	Body    ApiError
	Headers GetMessages400ResponseHeaders
}

func (response GetMessages400JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages413JSONResponse struct {
	Body    ApiError
	Headers GetMessages413ResponseHeaders
}

func (response GetMessages413JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages422JSONResponse struct {
	Body    ApiError
	Headers GetMessages422ResponseHeaders
}

func (response GetMessages422JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages500JSONResponse struct {
	Body    ApiError
	Headers GetMessages500ResponseHeaders
}

func (response GetMessages500JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages503JSONResponse struct {
	Body    ApiError
	Headers GetMessages503ResponseHeaders
}

func (response GetMessages503JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessageRequestObject struct {
	Id     ResourceId `json:"id"`
	Params GetMessageParams
}

type GetMessageResponseObject interface {
	VisitGetMessageResponse(w http.ResponseWriter) error
}

type GetMessage200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage200JSONResponse struct {
	Body    Message
	Headers GetMessage200ResponseHeaders
}

func (response GetMessage200JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage400JSONResponse struct {
	Body    ApiError
	Headers GetMessage400ResponseHeaders
}

func (response GetMessage400JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage404ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage404JSONResponse struct {
	Body    ApiError
	Headers GetMessage404ResponseHeaders
}

func (response GetMessage404JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage413JSONResponse struct {
	Body    ApiError
	Headers GetMessage413ResponseHeaders
}

func (response GetMessage413JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage422JSONResponse struct {
	Body    ApiError
	Headers GetMessage422ResponseHeaders
}

func (response GetMessage422JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage500JSONResponse struct {
	Body    ApiError
	Headers GetMessage500ResponseHeaders
}

func (response GetMessage500JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage503JSONResponse struct {
	Body    ApiError
	Headers GetMessage503ResponseHeaders
}

func (response GetMessage503JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoActionRequestObject struct {
	Params ApplyMailDemoActionParams
	Body   *ApplyMailDemoActionJSONRequestBody
}

type ApplyMailDemoActionResponseObject interface {
	VisitApplyMailDemoActionResponse(w http.ResponseWriter) error
}

type ApplyMailDemoAction200ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type ApplyMailDemoAction200JSONResponse struct {
	Body    MailDemoResult
	Headers ApplyMailDemoAction200ResponseHeaders
}

func (response ApplyMailDemoAction200JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction400JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction400ResponseHeaders
}

func (response ApplyMailDemoAction400JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction401JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction401ResponseHeaders
}

func (response ApplyMailDemoAction401JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction409ResponseHeaders struct {
	CacheControl *string
	RetryAfter   *int
	XRequestID   *RequestId
}

type ApplyMailDemoAction409JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction409ResponseHeaders
}

func (response ApplyMailDemoAction409JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction413JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction413ResponseHeaders
}

func (response ApplyMailDemoAction413JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction415JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction415ResponseHeaders
}

func (response ApplyMailDemoAction415JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction422JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction422ResponseHeaders
}

func (response ApplyMailDemoAction422JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction500JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction500ResponseHeaders
}

func (response ApplyMailDemoAction500JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type ApplyMailDemoAction503JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction503ResponseHeaders
}

func (response ApplyMailDemoAction503JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessageRequestObject struct {
	Params DeliverMessageParams
	Body   *DeliverMessageJSONRequestBody
}

type DeliverMessageResponseObject interface {
	VisitDeliverMessageResponse(w http.ResponseWriter) error
}

type DeliverMessage201ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type DeliverMessage201JSONResponse struct {
	Body    DeliveryReceipt
	Headers DeliverMessage201ResponseHeaders
}

func (response DeliverMessage201JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage400JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage400ResponseHeaders
}

func (response DeliverMessage400JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage401ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage401JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage401ResponseHeaders
}

func (response DeliverMessage401JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage409ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage409JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage409ResponseHeaders
}

func (response DeliverMessage409JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage413ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage413JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage413ResponseHeaders
}

func (response DeliverMessage413JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage415ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage415JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage415ResponseHeaders
}

func (response DeliverMessage415JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage422ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage422JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage422ResponseHeaders
}

func (response DeliverMessage422JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage500ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage500JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage500ResponseHeaders
}

func (response DeliverMessage500JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage503ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage503JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage503ResponseHeaders
}

func (response DeliverMessage503JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMessages get Messages
	// (GET /api/v1/messages)
	GetMessages(ctx context.Context, request GetMessagesRequestObject) (GetMessagesResponseObject, error)
	// GetMessage get Message
	// (GET /api/v1/messages/{id})
	GetMessage(ctx context.Context, request GetMessageRequestObject) (GetMessageResponseObject, error)
	// ApplyMailDemoAction apply Mail Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyMailDemoAction(ctx context.Context, request ApplyMailDemoActionRequestObject) (ApplyMailDemoActionResponseObject, error)
	// DeliverMessage deliver Message
	// (POST /internal/v1/messages)
	DeliverMessage(ctx context.Context, request DeliverMessageRequestObject) (DeliverMessageResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMessages operation middleware
func (sh *strictHandler) GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams) {
	var request GetMessagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMessages(ctx, request.(GetMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMessagesResponseObject); ok {
		if err := validResponse.VisitGetMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMessage operation middleware
func (sh *strictHandler) GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams) {
	var request GetMessageRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMessage(ctx, request.(GetMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMessageResponseObject); ok {
		if err := validResponse.VisitGetMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyMailDemoAction operation middleware
func (sh *strictHandler) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams) {
	var request ApplyMailDemoActionRequestObject

	request.Params = params

	var body ApplyMailDemoActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyMailDemoAction(ctx, request.(ApplyMailDemoActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyMailDemoAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyMailDemoActionResponseObject); ok {
		if err := validResponse.VisitApplyMailDemoActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeliverMessage operation middleware
func (sh *strictHandler) DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams) {
	var request DeliverMessageRequestObject

	request.Params = params

	var body DeliverMessageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeliverMessage(ctx, request.(DeliverMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeliverMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeliverMessageResponseObject); ok {
		if err := validResponse.VisitDeliverMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fz/d+I4kv9X9Hzz3u3ema9JfyM/3DHgdLNDIGtItjM9OT9hi6BpI3kkOR22H//7vZJksMFJoKenh96l",
	"f+iArS+lqlKp6lMqPjshnyecEaak0/rszAiOiNAfOzickQ5nSvAYvkdEhoIminLmtByfyIQzSSSap1Ih",
	"xhWaEBRCn6jquI4MZ2SOoR9h6dxpfXAYr0jFBXFuXUctEuK0HKkEZXfOcuk6vYjME64ICxc+SWK8INH2",
	"pEqkBHEWL9CUC4SR0C0RnyI1I0jiexIhLugdZThGUmGVSoRZhCY8WhSJsgRMOI8JZpoCn/yWEql6JfP2",
	"IsIUnVIizFxUonfj8SXCSpF5oqrIkCyRIApTpqlZ0QGTI2EGD+gGc34QZOq0nP+orcVQM29lbU2QIU+J",
	"RXuqiCgThhILhOEl4owgSULOIsMkhiirTGN6N1Mo5PM5ZuXyaazFQpkid0Q4y+Uya6g1op1QTwiuCcBR",
	"RGF2HF8KnhChKJFOa4pjSVwnyT0CDYvIc2vV43ag4dJ1IuBirPtyRoZTp/Xh6d7XOKYRBnK6tuvSfbrH",
	"FcP3mMZ4EpNdu3QxjRd9Oqdq1eN26TpzIiW+I9tCGeEpQR67i6mcIdvqDIUxhVGREpjJGCuCPjL+iSFg",
	"kqw6KxlkW8N11qqzn8JAPypgG30wIljTWhh0LXc++ZWECub8kUeLa8pjbNbyReLeWkjMw9V4mVGAzVFi",
	"EAps3XqXcNDQkn3wt9FwgC7NW/SJqhlPld6MU4Hv5oQpNMfiIxHA5wQ2r4Be//eXWvW//vo/PzhldinP",
	"xdUC1iS4m6wt42bHbDtjWcgDnicxNGjYfxX93yn89zr7mv1zXGfKxRwrp+WkKY2KhH+oV97gyvT28+tl",
	"ZfX5dFk5XX05WVY+vH6DJ7eFJ9nnRnO5vWrXeajc8coW1zupkLyE6ddESMoZidCPWJKXp1d+H4W6LZL0",
	"Dp6DJNC7i3anMnrXbr54ifg9EYiwSHPRRQmXWrlclEoikAx5QrTd/i0lYoESLPCcKCJkFZ1z8QmLSB8C",
	"Z4hxNB73z5DgSgsGUXZvTAGRlgZZRW22QHLBFH5wNUVYpQLss51oimkMDwRRqWAS9QbX7X6vG3Su/NHQ",
	"B1VZi4ws/tbs/cofpn8HkVPWJ+xOzZxWoyiWduVnXPlnvfImqNz+9w9lm3rbmDy3yYpMH8N5l4BG4zjm",
	"nzALDcdA2edcqzpViMKJpA/dyNWnAbwWZJpKHCM1wwpOUC6URFTpPVHYyBHQGMRA5HOWZ72ckcKKbO2c",
	"/FBlO2Sz//7M0DPkmMGnaCoIrFYSca+1Q7pIEByhTzOiZnBSCu22gBvBFI6BW2Eq4EsV9TTzIiIo+BRT",
	"wefGxdC8LAyaeR84DHkK2mzPf2hBQ4IUnZN/ckZcJLCeVs0wW4+IJ5JYenE2vSVoWyKrM2t7F/7DLko7",
	"J5YWNMcLJBWNYxQKAmcN3mJKRm42tSW7kpGNIryoonNgO5oTzKRuHeHFf8oct6k02nhmtc7wFTwwonUR",
	"TzJLnM1jlZQL+w6jmN4Tu3IXERzOgCefZjScrfhJBApnJPwoEb4DP+vTjDBgm7GvCAsQV/4UXfl3oI6S",
	"KBlgrcs4jndwK8Z0TqTC88RZ3pbpnF2DFuOKFdaMuGhCKLuzWoOFyvSEkQcF/HtMTzLdy+1kxVFEpXZ1",
	"YZmMACMw0l5fRbuELfDzUjaljMoZidYcYfITEdJY4LVn6Fq+WklpNsJ8eoNCZyLRBIcfq1sbea2BeY6W",
	"bmkCAhULn4SEJmpPJwKHIUkUiay8dpSS6+ziJEmeipCUeEn6eM3PXLautaeac2Mu2v3zoX/hdQNwQRzX",
	"yQ6Rd1676/m5B+ZUcVznx2H3JhgPh0G/7b/1HNe5GoyuLi+H/tjrBhdet9cOxjeX8EJ3bI97w0Fw3u71",
	"va7jOhfe+N2wGwyG46Dd7w//oR+2r8bvvMG41zGNfe/vVz3f6+Zn970utGj3R47reBftXj9o932v3b0J",
	"fO9tbzT2TIeh33vbG2yM3xn554EdSg869vxBux88MW/Xu7gcjr1B5yb4ybt56lVu3NybznBw3u91xhuP",
	"e4Pg0h++9b0RrMP3RsMrv+Npcs+HVwMY5dp71+v0veBq0L5u9/rtH/te7mlvEFyN4EGuZ6ft+z2vu37Y",
	"aV+2O73xTeC973he1/C4M+5de4HvDcbtfuC9743GQEK33evfBP3eRW8c+F67885w8Wo8GrcH3d7gLaxv",
	"2Ot4hlzPvza88t5fWn7YETvDi8u+Ny5Izb4ajdtjz47a63oBjNLreMHPwwE8Hnt978Ib+zfQUC/2sn1z",
	"4Q3GG9zqev3etecXeOu3x56h3gi6P+z8FAyvxsHwPBjdDDrwbDjoXPm+Zr+vp/Hev2tfjUyPjJYit1ca",
	"4vn+0C/18y8wjbtkztvhF4QaONyMJyLBkwBMbCAsQBHosDgw27qUBDPKDvHV2o/fMourIbLhSm1Htlif",
	"yDRWX7TY/ch0HXNsBnC67GFIn1hefsDSNa4Dt4Oz964jU0NoWVipyMMjLzg8XsVhZI5pDP4/fsj8/+aL",
	"0+eCR808xZ01DcWzxs7/BEs7PI7Jl2wTqsi8+OEphtnZRul8jsXCWa4IwkJg/V3vr/CRcNC3az5DLI1j",
	"xK1ngaV29gAug4jujlTRyESHZqAzJAlBJsasbgVXMJTxewEC3C/Y2pSD5kFxEU8w3WIqe3I8p2bFhTyq",
	"dEUmXsYaRgRX0Ua62ufTmEMiiCIRwoBBXvSrCDxRxSGAuRqfV15nUKPBHSEYiCU3nh2JwJVsvmw2Tk/R",
	"ZKGMq5xXY/3K/YN2wIbyP6fumQJ+h4bkW9iLMs5dZkjJN8HuNDpjAKmZ49rUwf5gXkZzydsn8LdVr50Q",
	"uAK2n4NzzKeK3TKVRlFKjebrnVCe6qMwT05nChPXG2/enJ6cNisvJ/hV5VW9Xq+8hv/q639fCP29+iOg",
	"v/VO2bJUV+MO8s87Jycnb1xEHnCo4gWS9AEg19BoHYroHVXyDEV8DmbNBqcS0D4UYYUnWJr4twi2NevN",
	"l5X6m0qjOa6/ajVetE7q1Ubz5PTFy5/zvImwMnBFkUG//BIBP+BPM/szNn9ahT+//FKFDy+XP+/OkJL0",
	"wX4bLV0PEAiCJWe7H9C5yX3dVW8xynqmc2PjwHadlNHfUmJfwwG6ubHKqCnbRtsz58wBZTKdTmlICVMB",
	"YUTcLbSVj8kcgIpAKqxhA54qSSMSWOAjANDD+pXwdUUX9A1njIY4DnIElhqY7QTQfuK4z+zl7lJYm9gn",
	"ub/J6txMZRwuGO7dkl/FXM1zWaySI2J5u9SBQpgKqhYjaGi4kkE4Y/6RsO2tD8eaVOkkiGy7QOmGNmeo",
	"8TeChbbRdqEzpZJ8IPT8yHO+66iwCMqmvNSbYuBpXlxfohAS2jhUOnmQCB6l2kqhGWZRrFMMOokkVult",
	"MFI6FV6xuXCUJbKraAipaDiVYmT4C+A6EYSFRCIsLCxIoioaETixFEBsUsHmkC3jzWn7aPlXm+I0VoZE",
	"HiPKYJ8Y1JQzSCwTgRhRn7j4eIYw42wx56nUoHZFZ8Upm/AHcLmBI61ardF8Va1X69VG63W9+cKggIyj",
	"ztAfuRYSdmF2onQ+RAN6VdTL6JrwiNqFPOY/og7gsYZGnOAJjalaVGRCQjqlITKSQlqCaEKmXJDsFEjw",
	"IuY4OkNzKiVldzWbu0ETrmYWRUXPQUxV5NkjhzOCBAkJMBI+cBGhhIgVb9FHsjjTdAL7iECSwBFkcuZw",
	"IlGN0FJ2z2lIajxVE/4AYH5EEsIiwvQkUyB7rjMEl+YDUCqASxHXWOoKaLc5eNiCMdEqpv3AKrpiMk0g",
	"60IiNCdqxiPD4tP6C7QN6xmhtUGPzlDKdLK4BnykdwwJ616YWw4pozAXUEWivG6Dg5bNcYq20bIq0qCm",
	"0fUsye+i9xXrNlV6XT3BWvFHOp1WMy4fIqa3maB+Bgk7CVkTSuKo8LLZrKK1qUY2z4/gBCF6d+A43mB5",
	"RBQJFRh+tDadgJ3DCzEHwFuBovFoUdMOaQ1Wm1EGVNtUbW3lMiIuIpMDVlRpT6ODxWiG4TBBmelZKw6M",
	"sbHFHNe5N1lPp+U0YIuBUeMJYTihTss5qdarJ9Yz1pa0hhNau2/UrI+qn90RVRY9ZxOt97c2MDMulZm8",
	"ioZAP/pLLhpAXW/UcRGN9Ie/6mTfKk9atWE1iFcijCIS0RBr9csWC8lZ2CHmtgyFnZHpluGqyZVW0YBv",
	"xZcJiEEpSDFSFsZpBGzEzIb62pqa8w04DoeuliF4xM5boi4yjuR8eqnPPAr8MHJ0XIdhbfrzOvllF2ns",
	"wFnwYsc1qcn8gBHR1thpNes6KKBzcHMa9bo+7e23kiszj0xgkYZdSTYSc5aQeFqdRdCpWa+bQI0pwgws",
	"kSQxNYFR7dfMJ8uc6JUz82EjNH7Gu6bR7lHKKhR2esZ6IiplSmz82nIgqf+/lqKqIlLpdFoBRAJ8Z7kr",
	"b7bhMH32b9y+ScOQSDlN49VZXl0Fqev7bZXcBbeyOW37WuEy3NIt6uEzffPqt3Sd030kqCndyB2Bv4rj",
	"lKwD9u3s0irizkJfFPI0jlb39MyppGWUv19UEhEDyRvZrCcIWOW7viYBO2tGdnaVKUSRQhdtsezPVg2I",
	"NfVhWQGewpZ9NosI989OGyd7qtNG5rFEmlu5yYOT5haFByi9DRq1sJrNPYW1nfwtkVdZhjh3iTIf3X5Y",
	"dcoF2mt0z1zI2xQ4NEN6UjjwrcOeuwXXcmoG5CzeiDwUZSljzwHqyzaZwM0XX3BcFLKupda60OIgrfUG",
	"hQdpnYvZbS2sfY1xWeK8RGLl+fWDE1s5mQcouzJCCzCY0/pwC66tzUFBtIZyscpDBQxlxV6OrMODVfCt",
	"hV0x5QdOy6HroFx3zBAgeKWDSZh2M0CsfabRcococSs27NqLYjp3mF2BhkThOnmo6fvjQrlvHcnZ9JMd",
	"lmbKbgBXky7edfDczbDfHXf9GdGWziU7Po1ye7+lL1UH2dXAKhpDrriFTur1OlILumDVJwK1PWOyf5dI",
	"7F8nEPouAh/tOtdP9xRWybXAEoGVXh48OKGVUnmAgiuh8xikHoPUY5B6DFKPQeoxSD0Gqd8qSP0jYtTs",
	"wgIEqhGZ85q54aV5lnBZGqiaqqXs/vgqIsWQur1bp8l1rs3cZTUFUln21aTmoUBRZmn97B6B4EmSlViF",
	"nDGTDFpPsQ43UDvL+gtdKW8vCshiob4wlUpVZMWyCouzQ2g76m0nSbzYKGH4RuHv7Wq7wAWgfWNTK5/n",
	"yiUKxRG7FSzvHjIW2bZcLjcD9+Xvj8H3JH6jXuLJsH3vhdqqj28fIud+W6OS/3GNp8Yo+z2Of7No290s",
	"6yshYKvw7+DznlsUfw95zw2iDR7Q+FKX87F6xaec0MdrHA/XLX2c5kN2VB+j2gj9zb5CLysmLRN0edHp",
	"V75H8UgJ6zP0FOs3D0/fSljnoscX8LWUL1f//rzurX486Str7X61ykcs7HvDwhov9hTWI2X8JUJ7tOD/",
	"4IT3KKUHKMRHaD0Cm0dg8whsHoHNI7D5nQCbnzeLxD7cLgtgJ8h2gaARglZoBb8Vcc+spv0LwU+DeG7j",
	"n/lKjnLss634HIoXoR5WacAyV4pka2WR1VVddyFNmcsKhhzhOYG2NfsLouYnRldwZbPeyNqaIqEymAcB",
	"jqaLxfSvg9mRzA/dbf0QTNVcFNJ1O6ZiB1Q5u8iyDy5qKwf/pBtBmwNndYyVn8jiydtBufJhWwjW+gp1",
	"1i1zQafspyl+D4h70BeBrFh2Q3Ubh3CzaucVbv6wWYkh7ugiwOiI4R4x3COGe8Rwjxju78NwtxyVMilv",
	"NzpAsZYReYBy3CbzCFwegcsjcHkELo/A5RG4PAKXR+DyCFw+AVxu/G7WJnBpccBHb2p+LcRyufz/AQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
