// Package mailstubapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package mailstubapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BodyViolationLocation.
const (
	Body BodyViolationLocation = "body"
)

// Valid indicates whether the value is a known member of the BodyViolationLocation enum.
func (e BodyViolationLocation) Valid() bool {
	switch e {
	case Body:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ACTIVERENTALEXISTS             ErrorCode = "ACTIVE_RENTAL_EXISTS"
	AUTHENTICATIONREQUIRED         ErrorCode = "AUTHENTICATION_REQUIRED"
	BODYTOOLARGE                   ErrorCode = "BODY_TOO_LARGE"
	CLOCKOUTOFSYNC                 ErrorCode = "CLOCK_OUT_OF_SYNC"
	CONCURRENCYRETRYEXHAUSTED      ErrorCode = "CONCURRENCY_RETRY_EXHAUSTED"
	CSRFINVALID                    ErrorCode = "CSRF_INVALID"
	DAILYLIMITREACHED              ErrorCode = "DAILY_LIMIT_REACHED"
	DELIVERYCONFLICT               ErrorCode = "DELIVERY_CONFLICT"
	EMAILALREADYREGISTERED         ErrorCode = "EMAIL_ALREADY_REGISTERED"
	IDEMPOTENCYCONFLICT            ErrorCode = "IDEMPOTENCY_CONFLICT"
	IDEMPOTENCYINPROGRESS          ErrorCode = "IDEMPOTENCY_IN_PROGRESS"
	IDEMPOTENCYKEYINVALID          ErrorCode = "IDEMPOTENCY_KEY_INVALID"
	IDEMPOTENCYKEYREQUIRED         ErrorCode = "IDEMPOTENCY_KEY_REQUIRED"
	INTERNALAUTHENTICATIONREQUIRED ErrorCode = "INTERNAL_AUTHENTICATION_REQUIRED"
	INTERNALERROR                  ErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS             ErrorCode = "INVALID_CREDENTIALS"
	INVALIDCURSOR                  ErrorCode = "INVALID_CURSOR"
	INVALIDHEADER                  ErrorCode = "INVALID_HEADER"
	INVALIDRENTALSTATE             ErrorCode = "INVALID_RENTAL_STATE"
	MALFORMEDJSON                  ErrorCode = "MALFORMED_JSON"
	METHODNOTALLOWED               ErrorCode = "METHOD_NOT_ALLOWED"
	ORIGINNOTALLOWED               ErrorCode = "ORIGIN_NOT_ALLOWED"
	OUTSIDESERVICEZONE             ErrorCode = "OUTSIDE_SERVICE_ZONE"
	OUTSTANDINGINVOICE             ErrorCode = "OUTSTANDING_INVOICE"
	PAYMENTINPROGRESS              ErrorCode = "PAYMENT_IN_PROGRESS"
	RATELIMITED                    ErrorCode = "RATE_LIMITED"
	RENTALCOMPLETED                ErrorCode = "RENTAL_COMPLETED"
	RESERVATIONEXPIRED             ErrorCode = "RESERVATION_EXPIRED"
	RESOURCENOTFOUND               ErrorCode = "RESOURCE_NOT_FOUND"
	SERVICEUNAVAILABLE             ErrorCode = "SERVICE_UNAVAILABLE"
	SOURCECAPACITYEXCEEDED         ErrorCode = "SOURCE_CAPACITY_EXCEEDED"
	SOURCENOTCARRIED               ErrorCode = "SOURCE_NOT_CARRIED"
	TELEMETRYSTALE                 ErrorCode = "TELEMETRY_STALE"
	UNSUPPORTEDMEDIATYPE           ErrorCode = "UNSUPPORTED_MEDIA_TYPE"
	VALIDATIONFAILED               ErrorCode = "VALIDATION_FAILED"
	VEHICLEINUSE                   ErrorCode = "VEHICLE_IN_USE"
	VEHICLEUNAVAILABLE             ErrorCode = "VEHICLE_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ACTIVERENTALEXISTS:
		return true
	case AUTHENTICATIONREQUIRED:
		return true
	case BODYTOOLARGE:
		return true
	case CLOCKOUTOFSYNC:
		return true
	case CONCURRENCYRETRYEXHAUSTED:
		return true
	case CSRFINVALID:
		return true
	case DAILYLIMITREACHED:
		return true
	case DELIVERYCONFLICT:
		return true
	case EMAILALREADYREGISTERED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case IDEMPOTENCYINPROGRESS:
		return true
	case IDEMPOTENCYKEYINVALID:
		return true
	case IDEMPOTENCYKEYREQUIRED:
		return true
	case INTERNALAUTHENTICATIONREQUIRED:
		return true
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDCURSOR:
		return true
	case INVALIDHEADER:
		return true
	case INVALIDRENTALSTATE:
		return true
	case MALFORMEDJSON:
		return true
	case METHODNOTALLOWED:
		return true
	case ORIGINNOTALLOWED:
		return true
	case OUTSIDESERVICEZONE:
		return true
	case OUTSTANDINGINVOICE:
		return true
	case PAYMENTINPROGRESS:
		return true
	case RATELIMITED:
		return true
	case RENTALCOMPLETED:
		return true
	case RESERVATIONEXPIRED:
		return true
	case RESOURCENOTFOUND:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case SOURCECAPACITYEXCEEDED:
		return true
	case SOURCENOTCARRIED:
		return true
	case TELEMETRYSTALE:
		return true
	case UNSUPPORTEDMEDIATYPE:
		return true
	case VALIDATIONFAILED:
		return true
	case VEHICLEINUSE:
		return true
	case VEHICLEUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for MailDemoActionAction.
const (
	DropNextResponseAfterAccept MailDemoActionAction = "drop_next_response_after_accept"
)

// Valid indicates whether the value is a known member of the MailDemoActionAction enum.
func (e MailDemoActionAction) Valid() bool {
	switch e {
	case DropNextResponseAfterAccept:
		return true
	default:
		return false
	}
}

// Defines values for ParameterViolationLocation.
const (
	Header ParameterViolationLocation = "header"
	Path   ParameterViolationLocation = "path"
	Query  ParameterViolationLocation = "query"
)

// Valid indicates whether the value is a known member of the ParameterViolationLocation enum.
func (e ParameterViolationLocation) Valid() bool {
	switch e {
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	InsufficientEnergy   UnavailableReason = "insufficient_energy"
	OutsideServiceZone   UnavailableReason = "outside_service_zone"
	ServiceRequired      UnavailableReason = "service_required"
	TechnicalUnavailable UnavailableReason = "technical_unavailable"
	TelemetryStale       UnavailableReason = "telemetry_stale"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case InsufficientEnergy:
		return true
	case OutsideServiceZone:
		return true
	case ServiceRequired:
		return true
	case TechnicalUnavailable:
		return true
	case TelemetryStale:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Code    ErrorCode         `json:"code"`
	Details *ApiError_Details `json:"details,omitempty"`

	// Message Safe English message; clients translate known codes.
	Message string `json:"message"`

	// RequestId Example: example-request-1
	RequestId RequestId `json:"request_id"`
}

// ApiError_Details defines model for ApiError.Details.
type ApiError_Details struct {
	union json.RawMessage
}

// BodyViolation defines model for BodyViolation.
type BodyViolation struct {
	Code     string                `json:"code"`
	Location BodyViolationLocation `json:"location"`
	Message  string                `json:"message"`

	// Pointer JSON Pointer without the fragment marker.
	Pointer string `json:"pointer"`
}

// BodyViolationLocation defines model for BodyViolation.Location.
type BodyViolationLocation string

// CommandId Example: 11111111-1111-4111-8111-111111111111
type CommandId = string

// Cursor Versioned Base64URL cursor signed with HMAC-SHA256 over endpoint, position, user scope and query parameters. Forward only; no TTL; rotation invalidates cursors. Any syntax, signature or scope failure returns INVALID_CURSOR.
//
// Example: eyJ2IjoxfQ
type Cursor = string

// DailyLimitDetails The spent allowance and the moment it is restored, for the refusal that reports it.
type DailyLimitDetails struct {
	// DailyLimit The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
	DailyLimit DailyLimitState `json:"daily_limit"`
}

// DailyLimitState The daily allowance of free reservations, read whether or not a rental is current. It is derived from the stored reservations of the account, in the service timezone, rather than from the absence of a current rental.
type DailyLimitState struct {
	// Available Whether this account may still create a free reservation in the current service-timezone day. False means the day's allowance is spent; it is not a statement about the current moment or about a live rental, each of which the server checks again when a command arrives.
	Available bool `json:"available"`

	// ResetsAt The moment the allowance returns, being the start of the next day in the service timezone. It is the moment to display and never a Retry-After: an unfinished command answers with one second, which is not when the limit comes back.
	ResetsAt Timestamp `json:"resets_at"`
}

// DeliveryReceipt defines model for DeliveryReceipt.
type DeliveryReceipt struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id ResourceId `json:"id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// MailDemoAction defines model for MailDemoAction.
type MailDemoAction struct {
	Action MailDemoActionAction `json:"action"`

	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`
}

// MailDemoActionAction defines model for MailDemoAction.Action.
type MailDemoActionAction string

// MailDemoResult defines model for MailDemoResult.
type MailDemoResult struct {
	// ActionId Example: 11111111-1111-4111-8111-111111111111
	ActionId CommandId `json:"action_id"`

	// ServerTime UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	ServerTime Timestamp `json:"server_time"`
}

// Message defines model for Message.
type Message struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id      ResourceId          `json:"id"`
	Subject string              `json:"subject"`
	Text    string              `json:"text"`
	To      openapi_types.Email `json:"to"`
}

// MessageCollection defines model for MessageCollection.
type MessageCollection struct {
	Items []MessageSummary `json:"items"`

	// NextCursor Required; null on the last or empty page. Signed cursor; see Cursor.
	NextCursor *string `json:"next_cursor"`
}

// MessageRequest defines model for MessageRequest.
type MessageRequest struct {
	Subject string `json:"subject"`

	// Text Plain text only; never interpreted as HTML. The total UTF-8 request body is also limited to 262144 bytes.
	Text string              `json:"text"`
	To   openapi_types.Email `json:"to"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	// AcceptedAt UTC RFC3339, exactly six fractional digits; domain commands use database time.
	//
	// Example: 2026-09-12T07:15:30.123456Z
	AcceptedAt Timestamp `json:"accepted_at"`

	// Id Example: 01994342-6ba7-7000-8000-000000000001
	Id      ResourceId          `json:"id"`
	Subject string              `json:"subject"`
	To      openapi_types.Email `json:"to"`
}

// ParameterViolation defines model for ParameterViolation.
type ParameterViolation struct {
	Code      string                     `json:"code"`
	Location  ParameterViolationLocation `json:"location"`
	Message   string                     `json:"message"`
	Parameter string                     `json:"parameter"`
}

// ParameterViolationLocation defines model for ParameterViolation.Location.
type ParameterViolationLocation string

// RequestId Example: example-request-1
type RequestId = string

// ResourceId Example: 01994342-6ba7-7000-8000-000000000001
type ResourceId = string

// Timestamp UTC RFC3339, exactly six fractional digits; domain commands use database time.
//
// Example: 2026-09-12T07:15:30.123456Z
type Timestamp = string

// UnavailableDetails defines model for UnavailableDetails.
type UnavailableDetails struct {
	UnavailableReasons []UnavailableReason `json:"unavailable_reasons"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// ValidationDetails defines model for ValidationDetails.
type ValidationDetails struct {
	Violations []Violation `json:"violations"`
}

// Violation defines model for Violation.
type Violation struct {
	union json.RawMessage
}

// BodyTooLarge defines model for BodyTooLarge.
type BodyTooLarge = ApiError

// InternalAuthenticationRequired defines model for InternalAuthenticationRequired.
type InternalAuthenticationRequired = ApiError

// InternalError defines model for InternalError.
type InternalError = ApiError

// MalformedJson defines model for MalformedJson.
type MalformedJson = ApiError

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ApiError

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ApiError

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = ApiError

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	Limit      *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor     *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetMessageParams defines parameters for GetMessage.
type GetMessageParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ApplyMailDemoActionParams defines parameters for ApplyMailDemoAction.
type ApplyMailDemoActionParams struct {
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// DeliverMessageParams defines parameters for DeliverMessage.
type DeliverMessageParams struct {
	XRequestID  *RequestId `json:"X-Request-ID,omitempty"`
	DeliveryKey string     `json:"Delivery-Key"`
}

// ApplyMailDemoActionJSONRequestBody defines body for ApplyMailDemoAction for application/json ContentType.
type ApplyMailDemoActionJSONRequestBody = MailDemoAction

// DeliverMessageJSONRequestBody defines body for DeliverMessage for application/json ContentType.
type DeliverMessageJSONRequestBody = MessageRequest

// AsValidationDetails returns the union data inside the ApiError_Details as a ValidationDetails
func (t ApiError_Details) AsValidationDetails() (ValidationDetails, error) {
	var body ValidationDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationDetails overwrites any union data inside the ApiError_Details as the provided ValidationDetails
func (t *ApiError_Details) FromValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationDetails performs a merge with any union data inside the ApiError_Details, using the provided ValidationDetails
func (t *ApiError_Details) MergeValidationDetails(v ValidationDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnavailableDetails returns the union data inside the ApiError_Details as a UnavailableDetails
func (t ApiError_Details) AsUnavailableDetails() (UnavailableDetails, error) {
	var body UnavailableDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnavailableDetails overwrites any union data inside the ApiError_Details as the provided UnavailableDetails
func (t *ApiError_Details) FromUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnavailableDetails performs a merge with any union data inside the ApiError_Details, using the provided UnavailableDetails
func (t *ApiError_Details) MergeUnavailableDetails(v UnavailableDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDailyLimitDetails returns the union data inside the ApiError_Details as a DailyLimitDetails
func (t ApiError_Details) AsDailyLimitDetails() (DailyLimitDetails, error) {
	var body DailyLimitDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDailyLimitDetails overwrites any union data inside the ApiError_Details as the provided DailyLimitDetails
func (t *ApiError_Details) FromDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDailyLimitDetails performs a merge with any union data inside the ApiError_Details, using the provided DailyLimitDetails
func (t *ApiError_Details) MergeDailyLimitDetails(v DailyLimitDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApiError_Details) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiError_Details) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBodyViolation returns the union data inside the Violation as a BodyViolation
func (t Violation) AsBodyViolation() (BodyViolation, error) {
	var body BodyViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBodyViolation overwrites any union data inside the Violation as the provided BodyViolation
func (t *Violation) FromBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBodyViolation performs a merge with any union data inside the Violation, using the provided BodyViolation
func (t *Violation) MergeBodyViolation(v BodyViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParameterViolation returns the union data inside the Violation as a ParameterViolation
func (t Violation) AsParameterViolation() (ParameterViolation, error) {
	var body ParameterViolation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParameterViolation overwrites any union data inside the Violation as the provided ParameterViolation
func (t *Violation) FromParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParameterViolation performs a merge with any union data inside the Violation, using the provided ParameterViolation
func (t *Violation) MergeParameterViolation(v ParameterViolation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Violation) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Violation) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMessages get Messages
	// (GET /api/v1/messages)
	GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams)
	// GetMessage get Message
	// (GET /api/v1/messages/{id})
	GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams)
	// ApplyMailDemoAction apply Mail Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams)
	// DeliverMessage deliver Message
	// (POST /internal/v1/messages)
	DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetMessages get Messages
// (GET /api/v1/messages)
func (_ Unimplemented) GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMessage get Message
// (GET /api/v1/messages/{id})
func (_ Unimplemented) GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApplyMailDemoAction apply Mail Demo Action
// (POST /internal/v1/demo/actions)
func (_ Unimplemented) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeliverMessage deliver Message
// (POST /internal/v1/messages)
func (_ Unimplemented) DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMessages operation middleware
func (siw *ServerInterfaceWrapper) GetMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessage operation middleware
func (siw *ServerInterfaceWrapper) GetMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ResourceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessageParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessage(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyMailDemoAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyMailDemoActionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyMailDemoAction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeliverMessage operation middleware
func (siw *ServerInterfaceWrapper) DeliverMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeliverMessageParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	// ------------- Required header parameter "Delivery-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Delivery-Key")]; found {
		var DeliveryKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Delivery-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Delivery-Key", valueList[0], &DeliveryKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Delivery-Key", Err: err})
			return
		}

		params.DeliveryKey = DeliveryKey

	} else {
		err := fmt.Errorf("Header parameter Delivery-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Delivery-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeliverMessage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/messages", wrapper.GetMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/messages/{id}", wrapper.GetMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/demo/actions", wrapper.ApplyMailDemoAction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/v1/messages", wrapper.DeliverMessage)
	})

	return r
}

type BodyTooLargeResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}
type BodyTooLargeJSONResponse struct {
	Body ApiError

	Headers BodyTooLargeResponseHeaders
}

type InternalAuthenticationRequiredResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}
type InternalAuthenticationRequiredJSONResponse struct {
	Body ApiError

	Headers InternalAuthenticationRequiredResponseHeaders
}

type InternalErrorResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}
type InternalErrorJSONResponse struct {
	Body ApiError

	Headers InternalErrorResponseHeaders
}

type MalformedJsonResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}
type MalformedJsonJSONResponse struct {
	Body ApiError

	Headers MalformedJsonResponseHeaders
}

type ServiceUnavailableResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}
type ServiceUnavailableJSONResponse struct {
	Body ApiError

	Headers ServiceUnavailableResponseHeaders
}

type UnsupportedMediaTypeResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}
type UnsupportedMediaTypeJSONResponse struct {
	Body ApiError

	Headers UnsupportedMediaTypeResponseHeaders
}

type ValidationFailedResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}
type ValidationFailedJSONResponse struct {
	Body ApiError

	Headers ValidationFailedResponseHeaders
}

type GetMessagesRequestObject struct {
	Params GetMessagesParams
}

type GetMessagesResponseObject interface {
	VisitGetMessagesResponse(w http.ResponseWriter) error
}

type GetMessages200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages200JSONResponse struct {
	Body    MessageCollection
	Headers GetMessages200ResponseHeaders
}

func (response GetMessages200JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessages400JSONResponse struct {
	Body    ApiError
	Headers GetMessages400ResponseHeaders
}

func (response GetMessages400JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages413JSONResponse struct{ BodyTooLargeJSONResponse }

func (response GetMessages413JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages422JSONResponse struct{ ValidationFailedJSONResponse }

func (response GetMessages422JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMessages500JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessages503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetMessages503JSONResponse) VisitGetMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessageRequestObject struct {
	Id     ResourceId `json:"id"`
	Params GetMessageParams
}

type GetMessageResponseObject interface {
	VisitGetMessageResponse(w http.ResponseWriter) error
}

type GetMessage200ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage200JSONResponse struct {
	Body    Message
	Headers GetMessage200ResponseHeaders
}

func (response GetMessage200JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage400ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage400JSONResponse struct {
	Body    ApiError
	Headers GetMessage400ResponseHeaders
}

func (response GetMessage400JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage404ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type GetMessage404JSONResponse struct {
	Body    ApiError
	Headers GetMessage404ResponseHeaders
}

func (response GetMessage404JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage413JSONResponse struct{ BodyTooLargeJSONResponse }

func (response GetMessage413JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage422JSONResponse struct{ ValidationFailedJSONResponse }

func (response GetMessage422JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMessage500JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMessage503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetMessage503JSONResponse) VisitGetMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoActionRequestObject struct {
	Params ApplyMailDemoActionParams
	Body   *ApplyMailDemoActionJSONRequestBody
}

type ApplyMailDemoActionResponseObject interface {
	VisitApplyMailDemoActionResponse(w http.ResponseWriter) error
}

type ApplyMailDemoAction200ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type ApplyMailDemoAction200JSONResponse struct {
	Body    MailDemoResult
	Headers ApplyMailDemoAction200ResponseHeaders
}

func (response ApplyMailDemoAction200JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction400JSONResponse struct{ MalformedJsonJSONResponse }

func (response ApplyMailDemoAction400JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction401JSONResponse struct {
	InternalAuthenticationRequiredJSONResponse
}

func (response ApplyMailDemoAction401JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction409ResponseHeaders struct {
	CacheControl *string
	RetryAfter   *int
	XRequestID   *RequestId
}

type ApplyMailDemoAction409JSONResponse struct {
	Body    ApiError
	Headers ApplyMailDemoAction409ResponseHeaders
}

func (response ApplyMailDemoAction409JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction413JSONResponse struct{ BodyTooLargeJSONResponse }

func (response ApplyMailDemoAction413JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response ApplyMailDemoAction415JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction422JSONResponse struct{ ValidationFailedJSONResponse }

func (response ApplyMailDemoAction422JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction500JSONResponse struct{ InternalErrorJSONResponse }

func (response ApplyMailDemoAction500JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyMailDemoAction503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response ApplyMailDemoAction503JSONResponse) VisitApplyMailDemoActionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessageRequestObject struct {
	Params DeliverMessageParams
	Body   *DeliverMessageJSONRequestBody
}

type DeliverMessageResponseObject interface {
	VisitDeliverMessageResponse(w http.ResponseWriter) error
}

type DeliverMessage201ResponseHeaders struct {
	CacheControl        *string
	IdempotencyReplayed *bool
	XRequestID          *RequestId
}

type DeliverMessage201JSONResponse struct {
	Body    DeliveryReceipt
	Headers DeliverMessage201ResponseHeaders
}

func (response DeliverMessage201JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.IdempotencyReplayed != nil {
		w.Header().Set("Idempotency-Replayed", fmt.Sprint(*response.Headers.IdempotencyReplayed))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage400JSONResponse struct{ MalformedJsonJSONResponse }

func (response DeliverMessage400JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage401JSONResponse struct {
	InternalAuthenticationRequiredJSONResponse
}

func (response DeliverMessage401JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage409ResponseHeaders struct {
	CacheControl *string
	XRequestID   *RequestId
}

type DeliverMessage409JSONResponse struct {
	Body    ApiError
	Headers DeliverMessage409ResponseHeaders
}

func (response DeliverMessage409JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage413JSONResponse struct{ BodyTooLargeJSONResponse }

func (response DeliverMessage413JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response DeliverMessage415JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage422JSONResponse struct{ ValidationFailedJSONResponse }

func (response DeliverMessage422JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeliverMessage500JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeliverMessage503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response DeliverMessage503JSONResponse) VisitDeliverMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.XRequestID != nil {
		w.Header().Set("X-Request-ID", fmt.Sprint(*response.Headers.XRequestID))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMessages get Messages
	// (GET /api/v1/messages)
	GetMessages(ctx context.Context, request GetMessagesRequestObject) (GetMessagesResponseObject, error)
	// GetMessage get Message
	// (GET /api/v1/messages/{id})
	GetMessage(ctx context.Context, request GetMessageRequestObject) (GetMessageResponseObject, error)
	// ApplyMailDemoAction apply Mail Demo Action
	// (POST /internal/v1/demo/actions)
	ApplyMailDemoAction(ctx context.Context, request ApplyMailDemoActionRequestObject) (ApplyMailDemoActionResponseObject, error)
	// DeliverMessage deliver Message
	// (POST /internal/v1/messages)
	DeliverMessage(ctx context.Context, request DeliverMessageRequestObject) (DeliverMessageResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMessages operation middleware
func (sh *strictHandler) GetMessages(w http.ResponseWriter, r *http.Request, params GetMessagesParams) {
	var request GetMessagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMessages(ctx, request.(GetMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMessagesResponseObject); ok {
		if err := validResponse.VisitGetMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMessage operation middleware
func (sh *strictHandler) GetMessage(w http.ResponseWriter, r *http.Request, id ResourceId, params GetMessageParams) {
	var request GetMessageRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMessage(ctx, request.(GetMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMessageResponseObject); ok {
		if err := validResponse.VisitGetMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyMailDemoAction operation middleware
func (sh *strictHandler) ApplyMailDemoAction(w http.ResponseWriter, r *http.Request, params ApplyMailDemoActionParams) {
	var request ApplyMailDemoActionRequestObject

	request.Params = params

	var body ApplyMailDemoActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyMailDemoAction(ctx, request.(ApplyMailDemoActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyMailDemoAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyMailDemoActionResponseObject); ok {
		if err := validResponse.VisitApplyMailDemoActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeliverMessage operation middleware
func (sh *strictHandler) DeliverMessage(w http.ResponseWriter, r *http.Request, params DeliverMessageParams) {
	var request DeliverMessageRequestObject

	request.Params = params

	var body DeliverMessageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeliverMessage(ctx, request.(DeliverMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeliverMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeliverMessageResponseObject); ok {
		if err := validResponse.VisitDeliverMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fz/c9u2kv9XMLzO3Ht31Fc7aSL/cKdKdKJWlvwo2q9p6uPAJGShIQEWAB3rZfS/3ywASqRE21Kapupd",
	"O9NYIglgsbvYL59d6pMT8TTjjDAlnd4nZ0FwTIT+OMDRggw4U4In8D0mMhI0U5Qzp+f4RGacSSJRmkuF",
	"GFfolqAIxsRNx3VktCAphnGE5anTe+8w3pCKC+LcuI5aZsTpOVIJyu6c1cp1RjFJM64Ii5Y+yRK8JPHu",
	"okrkBHGWLNGcC4SR0E8iPkdqQZDE9yRGXNA7ynCCpMIqlwizGN3yeFklyhJwy3lCMNMU+OTXnEg1qll3",
	"FBOm6JwSYdaiEr0NgkuElSJppprIkCyRIApTpqlZ0wGLI2EmD+kWc74RZO70nH9rbcTQMndla0OQIU+J",
	"ZX+uiKgThhJLhOEm4owgSSLOYsMkhihrzBN6t1Ao4mmKWb18OhuxUKbIHRHOCtYVhaDh2e94vAw4H2Nx",
	"R+B7xJkiTMFHnGUJjTBQ1PpFAlmfHPKA0yyxQ6fDd2EwnYbjvv/Ggyv3OMntLDEsu/WE66RESgwLFbJB",
	"Ec+TeK1sHCZXJHaAyoK/Tq9YtmEvNjpmJ/txvZ9RTwhud1/l8w6F28elUTovdYvY51uVs7VynR8bdoeN",
	"0fC5sVW1eGgQoLYBPJRwzLZovIGzxRQRDCf9XC1AkY2UYB4qSHygHEeTwPMn/XHYvwreepNgNOgHo+kk",
	"9L1/XI18b1gn2WfHHKGs96D5CKX/LNVlfTB7/0zxe74/9Z8UtnnimEVbUHjMgjQ0gtgucDLnIiXx91Yu",
	"B4ntuj8eDcO3Xn/oPSK2yhNfVmyuc9Efn0/9C28Yfj+bTuoI2HriKPWmzCIX7VB8lHq0JdYtokGxZkTc",
	"04hcMXyPaYJvk0N9+8zzr0cDL7ya9K/7o3H/u3Gtg6977AjFXE/mEcq2jlCQ5xWTeZZxoUh8QWKKg2Vm",
	"xbC3RK8ms6vLy6kfeMPwwhuO+mHw7rJWqI88eYRyfZTSIxTtI7SCdK9xQmMtuXNMk4PjN20OTFBw3h+N",
	"6wO23YeAmQrTRM9xT3miVwBa14NEEVC6TsINBTrFipc72gCPIb0oohKlVErIA10n45B7CKfntEiKaeKs",
	"blbbY49Ak+rYc4RKtEvmzWb/mtL1JkFx4pjC/nByKXhGhKIwyxwnkrhOVrpUCPxp/ul5B/DgqqI7nJHp",
	"XKvNU6M3Sj60Q1fu0yNK3mvfIUNMk+WYplStR1TUbTvNnuE5QR67S6hcIPvUGYoSCrMiJTCTCVYEfWD8",
	"I0NaDE1nnVUXYEdVSQ+BANYHrPfeiGBDa2XSTSbPb38hkYI1IXO/Lo7tZ4p7ZyObY76BefR5v6nZdYmt",
	"O/fW536b5RCjoEtzF32kasFzpeGVucB3KWEKpVh8IAL4nGEFeY3Tc/7nb63mf/z9v75x6pCmMhfXG9iQ",
	"4G6zto6bAwOkGKzImhmn53Tsfw39zyn886r4WvznuA5E8Vg5PSfPaVwl/H278Ro35jefXq0a68+nq8bp",
	"+svJqvH+1Wt8e1O5UnzudFe7uwbTcMcbO1wf5ELyGqZfEyEpZyRG32FJXp5e+WMU6WeRpHdwHSSB3l70",
	"B43Z2373xUvE74lAhMWaiy7KuNTK5aJcEoFkxDOikbhfcyKWKMMCp0QRIZvonIuPWMQa1jtDjKMgGJ8h",
	"wZUWDKLs3pgCIi0Nson6bInkkin84GqKsMoFIG52oTmmCVwQROWCSVTEwIMrfzb1QVU2IiPL77ujX/jD",
	"/B8gcsrGhN2phdPrVMXSb/yEG/9qN16HjZv//KbuUO8ak+cOWZXpASCYGWg0ThL+EbPIcAyUPeVa1akC",
	"bymIhlFjV+N7cFuQeS5xgtQCK8BEuVASUaXPROUgx0BjmACRz1mezXZmCiuyc3LKU9WdkO3xhzNDr1Bi",
	"Bp+juSCwW0nEvQk/XCQIjtHHBVELwD6FjgkAGGYKJ8CtKBfwpYlGmnkxERRQ4rngqead4WVl0gJPxlHE",
	"c9Bmi+hKkyYhRVPyL86IiwTWy6oFZpsZ8a0kll5cLG8J2pVIJeOq8uCfdlMabra0oBQvkVQ0SVAkCPga",
	"vMOUgtxiaUt2oyAbxXjZROfAdpQSzKR+OsbLf5clblNptPHMap3hqwRZal3Et4UlLtaxSsqFvYdRQu+J",
	"3bmLCI4WwJOPCxot1vwkAkULEn2QCN8Bcv5xQRiwzdhXhAWIq+xF14i9RqaJkiE2YW+S7BFWBDQlUuE0",
	"c1Y3dTpn96DFuGaFNSMuuiWU3VmtwUIVesLIgwL+PaYnhe6VTrLiKKZSFy9gm4wAIzDSOH5Dg/w9QO5z",
	"NqeMygWJNxxh8iMR0ljgDdbvWr5aSWk2wnr6gMJgItEtjj40dw7yRgPLHK090gQEKpY+iQjN1IFBBI4i",
	"kikSW3ntKSXX2SdIkjwXEamJkrR7La9ct69NpFoKY3awnR0gpepVHHe3OvBowlmXP1x4wdvpMJxMg7A/",
	"Hk//qS8+jj2vV/e9ITzRH88c1/Eu+qNx2B/7Xn/4LvS9N6NZ4JkBU3/0ZjTZmn8w889DO5XjbkDHJ9Yd",
	"eheX08CbDN6FP3jvnrpVmrd0ZzCdnI9Hg2Dr8mgSXvrTN743g3343mx65Q88Te759GoCs1x7b0eD8TYu",
	"U1wdTcKrGVwojRz0fX/kDTcXB/3L/mAUvAu9HweeNzQ8HgSjay/0vUkAcOuPo1kAJAz7o/G7cDy6GAWh",
	"7/UHbw0Xr4JZ0J8MR5M3sL/paOAZcj3/2vDK+/HS8sPOOJheXI69oCI1e2sW9APPzjoaemEB6Pw0ncDl",
	"wBt7F17gv4MH9WYv++8uvEmwxa2hNx5de36Ft34/8Az1RtDj6eCHcHoVhNPzcPZuMoBr08ngyvc1+329",
	"jPfj2/7VzIyoR8G2YemaQOgC02RIUt6PPiPVwNF2PhELnoVgYsOiEhnqQmdojnUtCWaWPfKrTRy/YxbX",
	"UxTT1dqOYrM+kXmiPmuzh5HpOsZthuBdDjCkT2yvPGHtHjeJ29HZe9eRuSG0Lq1U5OGRGxwur/MwgzW5",
	"Toofivi/++L0ueRRM09xZ0ND1dfY9Z9g6YAnCfmcY0IVSasfnmKYXW2WpykWS2e1JggLgfV3fb6iR9LB",
	"ArA7QyxPEsRtZIGlDvZIminI6O5IE81MdmgmOkOSEGRyzOZOcgVTmbhXiZwclmxty0HzoLqJJ5huMZUD",
	"OV5Ss+pGHlW6KhMvE90YAqGizXR1zKcxh0wQRWKEoavkYtxEEIkqDgnMVXDeeFU0j5hOEkgGEslNZEdi",
	"CCW7L7ud01N0u1QmVC6rsb7l/k4nYEv5n1P3QgH/hIbka9iLOs5dFkjJV8HuNDpjAKnFGtI+HMwraK65",
	"+wT+th61FwJX6dYqwTk7kH9FSp3uq71QnuajME9JZyoLtzuvX5+enHYbL2/xt41v2+124xX8097895nQ",
	"37e/B/S3OSk7luoqGCD/fHBycvLaReQBRypZIkkfAHKNjNahmN5RJc9QzFMwazY5lYD2oRgrfIulyX+r",
	"YFu33X3ZaL9udLpB+9te50XvpN3sdE9OX7z8qcybGCsDV1QZ9PPPMfAD/nSLP4H506v8+fnnJnx4ufpp",
	"f4bUlA8OO2j5ZoJQECw5299Blxb39VB9xCgbmcGdLYftOjmjv+bE3gYHun2w6qipO0a7K5fMAWUyn89p",
	"RAlTIWFE3C21lU9ICkBFKBXWsAHPlaQxCS3wEQLoYeNK+FqqCyoSLRiNcBKWCKw1MLsFoMPEUS5R7imF",
	"jYl9kvvbrC6tVMfhiuHer/hVrdU8V8WqcRErU+cjUS6oWs7gQcOVAsIJ+AfCdo8+uDWp8tswts+FSj9o",
	"a4YafyNYaBttN7pQKisnQs/PnPJ9Z4VNUDbntdEUg0jz4voSQe0bLJMuHmSCx7m2UmiBWZzoEoMuIq37",
	"WLWRqpRoUdGa3ERTaC4Gr5Qgw18A14kgLCISYWFhQRI30YyAx1IAsUkFh0P2TDSn7aPlX2uO80QZEnmC",
	"KINzYlBTzhSmjAjEiPrIxYczhBlny5TnUoPaDd3nTNktf4CQGzjSa7U63W+b7Wa72em9andfGBSQcTSY",
	"+jPXQsIurE6UrodoQK+JioY/iCCp3chj8SMaAB5raMQZvqUJVcuGzEhE5zRCRlJISxDdkjkXpPACGV4m",
	"HMdnRT2/ZWs36JarhUVR0XMQUxN51uUAuClIRICR8IGLGGVErHmLPpDlmaYT2EcEkgRckOmCBo9ENUJL",
	"2T2nEWnxXN3yBwDzY5IRFhOmF5kD2amuEFyaD0CpAC7FXGOpa6DddlXbdgNQMR0HNlGp3walRC14bFh8",
	"2n6BdmE9I7Q+6NEZypkuFreAj/SOIWHDC9O3njMKawFVJC7rNgRoxRqnaBctayINahpdL4r8Lir3FugF",
	"Noo/0+U021mAiBltFmifQcFOQtWEkiSu3Ox2m2hjqpGt8yPwIESfDpwkWyyPiSKRAsOPNqYTsHO4IVIA",
	"vBUoGo+XLR2QtmC3BWVAtS3VttYhI+IiNjVgRZWONAZYzBYYnAkqTM9GcWCOrSPmuM69qXo6PacDRwyM",
	"Gs8Iwxl1es5Js908sZGxtqQtnNHWfadlY1R97Y6ouuy5WGhzvrWBWXCpzOJNNAX60d9K2QAaerOBi2is",
	"P/xdF/vWddKmTatBvBJhFJOYRlirX7FZKM7CCTHvP1A4GYVuGa6aWmkTTfhOfpmBGJSCEiNlUZLHwEbM",
	"bKqvranxb8BxcLpahhARO2+Iuig4UorpTZ8QBX4YOTquw7A2/WWd/LxXI+zERfJi5zWlyfKEMdHW2Ol1",
	"2zopoCmEOZ12W3t7+63mJYhHFrBIw74kG4k5Kyg8Vd6p6Lbb+7dwlYKZ91up8TPRNY33z1LWqbAzMtYT",
	"USlzYvPXngNF/f+2FDUVkUqX0yogEuA7e/da7cJhdW2ZeRQRKed5svblzSPou1q5zukhEqy0Y9va0RPt",
	"2Ovq0pdtx/6D+8F/l3bsHZb9Gdqxt4iG/rPTzsljq6wNR6vyJhYM6nafH7TTOrpynRft9vMDq2+M6FF7",
	"0FjTV17OS5ze+xuwNRYUBPeJSs7joQH+qGG7VdpwYR0N6T00zBt+Ts8pRUl6YBGSwy3t3WHZbY/d+kTj",
	"1R5ue8dZD23lXoO5RU8aILcbNFfT9/v51q/tWi0eaKelsVPOgA1+v+/kpVL9b3aEf4T70+C+40Mat7Z4",
	"Pd3lFha9Gk0UAHjfQyftdhupJV2y5hOe80An+f/FNf7f8Ux/Ck+kHU/79EBh7WaedQKr7eY4OqHVUnmE",
	"gquh86+ooXCLXzxoKCA9iBwAu2yZGojWiIzL2sjB9PUVHRbrEAEDuHG3AZJ0NmqqvaaFsMAnDHglEfxv",
	"ga8CaRM8y4omxIgzZtKlzRIb+4/6BS4m9K8DWChNVn+cQF81v2BQjVMK/74bhvSzLFluNfl8pXjkZm0L",
	"QJEPDRasfJ5rKKq0D+3X0r+/D6+ybbVabUdSq98eFB1I/FZH0ZNx1MEbtX1RXz9mKf2eSKP8gyJPzVH3",
	"GyRfJPx52uBV3+vWozr7G9dHftRBT/P60Nirrk+zLgKr7+f8whDFI92hz9BTbY08vtCwhnUuenwDX+o8",
	"lFrLn9fh9S/NfOGQ87A24M+Pajovnh9U+5L0nzYk+rRdgH1/s6qESXD0lwgeQvAUWjvuasRU9It9Zthk",
	"NrcbOZWrJPVRU1/xFBoDoNdE6VCnVOazfSjImjJd05CmhLQOYGY4JfBsy/7ekvlBpnWg0213imdNAa7O",
	"QSDwwLoQq9+8sTOZl8h2mqybBvPRNTFTDdPvyFhM4pCIylbl/yBwZ3viokeg8QNZPgn0lFpzbJG19wV6",
	"mHoGa6lr+/wt4d9RYzpWLPvFg51jAMn23uH2S0M1LnGgC+zxX9HfHxz97Vi4ulBr96EjDLLqiDxCJGeX",
	"zL9CnkNCnq1utu2Qx0YQj6JDXyrWWa3+dwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
